// VIT Translation Scaffold
// Function: ReadControlParameterFileSub
// Source: ReadSetParameters.f90
// Module: ReadSetParameters
// Fortran: SUBROUTINE ReadControlParameterFileSub(CntrPar, LocalVar, accINFILE, accINFILE_size, RootName, ErrVar)
// Reference built with: -fdefault-real-8 -fdefault-double-8 -ffp-contract=off
// Source MD5: bfa4b49d65ab
// VIT: 0.1.0
// Status: unverified
// Generated: 2026-08-20T21:08:44Z
//
// CONTRACT: respecify (plan.json). The unit OPENs and CLOSEs
// `UnControllerParameters` and `UnEc` itself, so its contract is
// (a DISCON.IN on disk, LocalVar%DT, RootName) -> (CntrPar, ErrVar). A Fortran
// unit number has no C representation, so the I/O is reimplemented; everything
// that is not I/O -- the parameter names, the AllowDefault predicates, the
// array lengths, the arithmetic, the open-loop channel assembly -- is
// transcribed literally, because those are what a value comparison can see.
//
// ------------------------------------------------------------------------
// WHAT VERIFIED THIS, AND THE ANSWER TODAY IS NOTHING. Read this before
// trusting a line of it.
//
// The differential harness REFUSED (evidence/ReadControlParameterFileSub/
// harness.plan-dump.the-file-is-neither-supplied-nor-compared.txt): the
// generator reports `accINFILE` and `RootName` as UNOBSERVABLE character
// arguments -- neither supplied nor compared -- and no R8_file_contents rule
// fires, because `file_params_from` matches a BARE dummy and the reference
// writes `file=accINFILE(1)`. Its 291 varied parameters are CntrPar fields
// this unit OVERWRITES from the file before reading.
//
// Integration is REFUSED too (evidence/.../integrate.no-mode-copies-an-
// ALLOCATABLE-back.txt): no `vit integrate` mode copies an ALLOCATABLE view
// field back into the Fortran type, and ~50 of this unit's outputs are exactly
// that. So the gate cannot run either.
//
// This file is therefore a TRANSCRIPTION AWAITING AN INSTRUMENT. 192 of its
// 193 parse calls are generated by
// `evidence/ReadControlParameterFileSub/transcribe_parse_block.py` from the
// Fortran and from `vit_types.h`, so the transcription is re-runnable and
// diffable rather than trusted; re-run it and diff before believing it.
// ------------------------------------------------------------------------
//
// WHAT IS NOT REPRODUCED, each named rather than left to be found:
//
//   the phantom last record   `NumLines` counts the READ that FAILS, so
//                             `FileLines` has one more record than the file
//                             has lines and the reference never assigns the
//                             last one -- it is whatever ALLOCATE returned.
//                             Undefined is not reproducible; blanks is what
//                             this writes, and an all-blank record matches no
//                             parameter name in FindLine.
//   the echo file's BODY      the ~193 per-parameter records are written by
//                             the Parse*_Opt callees through `UnEc`, and those
//                             five units emit nothing because a Fortran unit
//                             number cannot cross the boundary (their family
//                             decision, DECISIONS.md). This unit owns the
//                             file, so its five HEADER records ARE written
//                             here -- with the byte layout measured off
//                             gfortran rather than recalled. An echo file this
//                             side is a header without a body. The arm is dead
//                             in all 27 scenarios (CntrPar%Echo == 0 in every
//                             `Examples/DISCON*.IN`).
//   GetNewUnit                its only failure is "no free unit below 1024",
//                             which is a statement about the Fortran runtime's
//                             unit table. There is no such table here.
//   the C++ side's ALLOCATEs  CFI_allocate mallocs and nothing frees it; the
//                             Fortran copy-back allocates its own and copies.
//                             ~50 small blocks per call, ~28 calls per
//                             simulation. Stated, not repaired: freeing them
//                             would free storage the view still points at.

#include "vit_types.h"

#include <ISO_Fortran_binding.h>

#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <string>
#include <string_view>
#include <vector>

// `CurDate` and `CurTime` are declared PERMANENT BRIDGES in plan.json -- they
// read the wall clock through `DATE_AND_TIME`, so they are not functions of
// this unit's arguments. Same shim and same declaration block as `Debug`
// (rosco/controller/src/debug.cpp:80-83), which is the unit that raised them;
// neither result is NUL-terminated.
extern "C" {
void vit_curdate_c(char* CurDate_result);   // CHARACTER(11)
void vit_curtime_c(char* CurTime_result);   // CHARACTER(8)
}

namespace {

// CHARACTER(*), PARAMETER :: RoutineName = 'ReadControlParameterFileSub'
constexpr std::string_view RoutineName = "ReadControlParameterFileSub";

// ROSCO_Helpers.f90:44
constexpr int MaxLineLength = 2048;
// Constants.f90:22, :37, :53, :73 -- read out of the source, not recalled.
constexpr double R2D = 57.2957795130;
constexpr char Tab = '\t';                       // CHAR(9)
constexpr int VS_FBP_Variable_Pitch = 0;
constexpr int PRC_Comm_Constant = 0;
// ROSCO_Types.f90:10
constexpr std::string_view rosco_version = "2.10.1";

// The reference's own local widths. A CHARACTER local narrower than what is
// assigned into it TRUNCATES silently, and three of these are load-bearing.
constexpr int PriPath_LEN = 1024;                // CHARACTER(1024)
constexpr int EchoFilename_LEN = 128;            // CHARACTER(128)
constexpr int OL_String_LEN = 1024;              // CHARACTER(1024)

// TRIM: trailing blanks only.
std::string_view ftrim(const char* s, int len) {
    int n = len;
    while (n > 0 && s[n - 1] == ' ') --n;
    return std::string_view(s, static_cast<size_t>(n));
}

// A Fortran CHARACTER assignment blank-fills the ENTIRE declared width and
// truncates what does not fit. Both halves matter here.
void fassign(char* dst, int width, std::string_view src) {
    const int n = static_cast<int>(src.size()) < width
                      ? static_cast<int>(src.size()) : width;
    if (n > 0) std::memcpy(dst, src.data(), static_cast<size_t>(n));
    if (n < width) std::memset(dst + n, ' ', static_cast<size_t>(width - n));
}

// `ErrVar%ErrMsg` is CHARACTER(:), ALLOCATABLE: assignment REALLOCATES to the
// right-hand side's length. Same helper as CheckInputs, Read_OL_Input and the
// five Parse*_Opt units, including the clear-the-tail argument measured there.
void assign_errmsg(errorvariables_view_t* ErrVar, std::string_view s) {
    if (ErrVar->ErrMsg == nullptr) {
        std::fprintf(stderr,
                     "VIT: ReadControlParameterFileSub: ErrVar%%ErrMsg has no "
                     "staging buffer; the assignment of %d bytes is refused\n",
                     static_cast<int>(s.size()));
        return;
    }
    if (static_cast<int32_t>(s.size()) > ErrVar->n_ErrMsg_cap) {
        std::fprintf(stderr,
                     "VIT: ReadControlParameterFileSub: ErrVar%%ErrMsg needs %d "
                     "bytes, the staging buffer holds %d; the assignment is "
                     "refused\n",
                     static_cast<int>(s.size()),
                     static_cast<int>(ErrVar->n_ErrMsg_cap));
        return;
    }
    std::memcpy(ErrVar->ErrMsg, s.data(), s.size());
    if (ErrVar->n_ErrMsg_cap > static_cast<int32_t>(s.size())) {
        std::memset(ErrVar->ErrMsg + s.size(), 0,
                    static_cast<size_t>(ErrVar->n_ErrMsg_cap) - s.size());
    }
    ErrVar->n_ErrMsg = static_cast<int32_t>(s.size());
}

// TRIM(ErrVar%ErrMsg)
std::string errmsg_trim(const errorvariables_view_t* ErrVar) {
    const int n = ErrVar->n_ErrMsg;
    if (ErrVar->ErrMsg == nullptr || n <= 0) return std::string();
    const std::string_view v(ErrVar->ErrMsg, static_cast<size_t>(n));
    return std::string(v.substr(0, v.find_last_not_of(' ') + 1));
}

// ANY(a > v) over a view's pointer+size pair. ANY of an empty set is .FALSE.,
// and the pointer is null exactly when the Fortran component is unallocated --
// which is the case this unit reaches whenever the group count is 0.
bool any_gt(const int* a, int32_t n, int v) {
    if (a == nullptr) return false;
    for (int32_t i = 0; i < n; ++i)
        if (a[i] > v) return true;
    return false;
}

// --- The ALLOCATABLE array dummies of ParseDbAry_Opt / ParseInAry_Opt -------
//
// Both callees take `REAL(8)/INTEGER, INTENT(INOUT), ALLOCATABLE :: Ary(:)`,
// which crosses BIND(C) as a CFI descriptor, and both ALLOCATE INTO IT
// (`CFI_allocate`, parsedbary_opt.cpp:587). The view carries the same field as
// a bare pointer + size, so the descriptor has to be built here and read back
// afterwards.
//
// CFI_establish is REQUIRED to be given a null base_addr for an allocatable,
// so an already-allocated field is expressed by filling the descriptor's own
// fields afterwards. That case is not hypothetical: it is the branch whose
// message the callee writes as "array was already allocated", and dropping it
// would delete a reachable error path.
struct AryRef {
    CFI_CDESC_T(1) d;
};

void establish(AryRef* a, CFI_type_t type, size_t elem, void* base, int32_t n) {
    CFI_establish(reinterpret_cast<CFI_cdesc_t*>(&a->d), nullptr,
                  CFI_attribute_allocatable, type, elem, 1, nullptr);
    if (base != nullptr) {
        CFI_cdesc_t* d = reinterpret_cast<CFI_cdesc_t*>(&a->d);
        d->base_addr = base;
        d->dim[0].lower_bound = 1;
        d->dim[0].extent = n;
        d->dim[0].sm = static_cast<CFI_index_t>(elem);
    }
}

void readback(AryRef* a, void** base, int32_t* n) {
    CFI_cdesc_t* d = reinterpret_cast<CFI_cdesc_t*>(&a->d);
    *base = d->base_addr;
    *n = d->base_addr != nullptr ? static_cast<int32_t>(d->dim[0].extent) : 0;
}

// --- gfortran list-directed output, for the echo header --------------------
//
// MEASURED, not recalled (`od -c` on a five-record probe, 2026-08-20): each
// record opens with ONE blank, adjacent CHARACTER items are concatenated with
// NO separator between them, and the record ends with '\n'. `NEW_LINE('A')` is
// an ordinary one-character item, so `WRITE(u,*) NEW_LINE('A')` is " \n\n".
void ld_write(std::FILE* f, std::string_view s) {
    std::fputc(' ', f);
    std::fwrite(s.data(), 1, s.size(), f);
    std::fputc('\n', f);
}

}  // namespace

void ReadControlParameterFileSub(controlparameters_view_t* CntrPar,
                                 localvariables_view_t* LocalVar,
                                 char* accINFILE, int accINFILE_size,
                                 char* RootName,
                                 errorvariables_view_t* ErrVar) {
    // `accINFILE` is CHARACTER(accINFILE_size), DIMENSION(accINFILE_size), and
    // the wrapper flattens element j to offset (j-1)*accINFILE_size. Every use
    // in the reference is `accINFILE(1)`.
    char* const accINFILE_1 = accINFILE;
    const int len_accINFILE_1 = accINFILE_size;

    // CHARACTER(1024) :: PriPath
    std::vector<char> PriPath(static_cast<size_t>(PriPath_LEN));

    // CALL GetPath( accINFILE(1), PriPath )
    getpath_c(accINFILE_1, len_accINFILE_1, PriPath.data(), PriPath_LEN);

    // CALL GetNewUnit(UnControllerParameters, ErrVar)
    // OPEN(unit=UnControllerParameters, file=accINFILE(1), status='old',
    //      action='read')
    //
    // The OPEN carries no IOSTAT=, so on an absent file the REFERENCE
    // terminates the process rather than reporting (measured: EXIT=2,
    // evidence/.../reference.OPEN-status-old-aborts-on-an-absent-file.txt).
    // A C++ `fopen` returning null is that same program state, and there is no
    // error path to transcribe: abort with the runtime's own wording so a
    // divergence here cannot be mistaken for a parse result.
    const std::string infile(ftrim(accINFILE_1, len_accINFILE_1));
    std::FILE* f = std::fopen(infile.c_str(), "rb");
    if (f == nullptr) {
        std::fprintf(stderr,
                     "Fortran runtime error: Cannot open file '%s': "
                     "No such file or directory\n", infile.c_str());
        std::fflush(stderr);
        std::_Exit(2);
    }

    // ! Read all lines, first get the number of lines
    // NumLines = 0 ; IOS = 0
    // DO WHILE (IOS == 0) ; NumLines = NumLines + 1
    //     READ(u,'(A)',IOSTAT=IOS) TmpLine ; END DO
    //
    // The counter is incremented BEFORE the read, so the read that hits
    // end-of-file has already been counted: NumLines is (records in the file)
    // + 1. The rewind-and-fill loop below runs to that same NumLines, so its
    // last READ fails and leaves FileLines(NumLines) as ALLOCATE left it. See
    // the header: blanks here, and that is a stated divergence.
    std::vector<std::string> records;
    {
        std::string cur;
        int c;
        bool any = false;
        while ((c = std::fgetc(f)) != EOF) {
            any = true;
            if (c == '\n') {
                // A CR immediately before the record terminator is part of the
                // line separator for a text-mode Fortran READ.
                if (!cur.empty() && cur.back() == '\r') cur.pop_back();
                records.push_back(cur);
                cur.clear();
                any = false;
            } else {
                cur += static_cast<char>(c);
            }
        }
        // A final partial record with no terminator is still a record.
        if (any) {
            if (!cur.empty() && cur.back() == '\r') cur.pop_back();
            records.push_back(cur);
        }
    }
    std::fclose(f);                                  // CLOSE(UnControllerParameters)

    const int NumLines = static_cast<int>(records.size()) + 1;

    // ALLOCATE(FileLines(NumLines)) -- CHARACTER(MaxLineLength).
    // The '(A)' edit descriptor blank-fills the rest of each record and
    // truncates anything past MaxLineLength.
    std::vector<char> FileLines(static_cast<size_t>(NumLines) * MaxLineLength, ' ');
    for (int i = 0; i < static_cast<int>(records.size()); ++i) {
        fassign(FileLines.data() + static_cast<size_t>(i) * MaxLineLength,
                MaxLineLength, records[static_cast<size_t>(i)]);
    }

    // The five callee shims. Each fills in the four arguments that are the
    // same at all 193 call sites (FileLines, its two extents, and the file
    // name) so that the transcribed block below reads like the Fortran.
    auto parse_int = [&](const char* name, int* v,
                         int has_ad, int ad, int has_unec, int unec) {
        parseinput_int_opt_c(FileLines.data(), NumLines, MaxLineLength,
                             const_cast<char*>(name),
                             static_cast<int>(std::strlen(name)), v,
                             accINFILE_1, len_accINFILE_1, ErrVar,
                             has_ad, static_cast<int32_t>(ad), has_unec, unec);
    };
    auto parse_dbl = [&](const char* name, double* v,
                         int has_ad, int ad, int has_unec, int unec) {
        parseinput_dbl_opt_c(FileLines.data(), NumLines, MaxLineLength,
                             const_cast<char*>(name),
                             static_cast<int>(std::strlen(name)), v,
                             accINFILE_1, len_accINFILE_1, ErrVar,
                             has_ad, static_cast<int32_t>(ad), has_unec, unec);
    };
    auto parse_str = [&](const char* name, char* v, int len_v,
                         int has_ad, int ad, int has_unec, int unec) {
        parseinput_str_opt_c(FileLines.data(), NumLines, MaxLineLength,
                             const_cast<char*>(name),
                             static_cast<int>(std::strlen(name)), v, len_v,
                             accINFILE_1, len_accINFILE_1, ErrVar,
                             has_ad, static_cast<int32_t>(ad), has_unec, unec);
    };
    auto parse_dbary = [&](const char* name, double** v, int32_t* n, int AryLen,
                           int has_ad, int ad, int has_unec, int unec) {
        AryRef a;
        establish(&a, CFI_type_double, sizeof(double), *v, *n);
        parsedbary_opt_c(FileLines.data(), NumLines, MaxLineLength,
                         const_cast<char*>(name),
                         static_cast<int>(std::strlen(name)),
                         reinterpret_cast<CFI_cdesc_t*>(&a.d), AryLen,
                         accINFILE_1, len_accINFILE_1, ErrVar,
                         has_ad, static_cast<int32_t>(ad), has_unec, unec);
        readback(&a, reinterpret_cast<void**>(v), n);
    };
    auto parse_inary = [&](const char* name, int** v, int32_t* n, int AryLen,
                           int has_ad, int ad, int has_unec, int unec) {
        AryRef a;
        establish(&a, CFI_type_int, sizeof(int), *v, *n);
        parseinary_opt_c(FileLines.data(), NumLines, MaxLineLength,
                         const_cast<char*>(name),
                         static_cast<int>(std::strlen(name)),
                         reinterpret_cast<CFI_cdesc_t*>(&a.d), AryLen,
                         accINFILE_1, len_accINFILE_1, ErrVar,
                         has_ad, static_cast<int32_t>(ad), has_unec, unec);
        readback(&a, reinterpret_cast<void**>(v), n);
    };

    // ! Read Echo first, so file can be set up, if desired
    // CALL ParseInput(FileLines,'Echo', CntrPar%Echo, accINFILE(1), ErrVar)
    parse_int("Echo", &CntrPar->Echo, 0, 0, 0, 0);
    if (ErrVar->aviFAIL < 0) return;

    // ! Set up echo file
    // UnEc = 0
    //
    // `UnEc` is a Fortran unit number, and the only thing the reference ever
    // ASKS of it is `UnEc > 0`. So it is modelled as a flag here, and the
    // sentinel is the reference's own first free unit. What matters is WHEN it
    // becomes non-zero: GetNewUnit runs BEFORE the OPEN, so a failed OPEN
    // leaves UnEc > 0 -- it is still passed to all 192 parse calls and still
    // CLOSEd at the end. Setting it after the OPEN would delete that.
    int UnEc = 0;
    std::FILE* ec = nullptr;
    std::vector<char> EchoFilename(static_cast<size_t>(EchoFilename_LEN));
    if (CntrPar->Echo > 0) {
        // EchoFilename = TRIM(RootName)//'.RO.echo'   -- CHARACTER(128), so a
        // RootName past 120 characters truncates, silently, in the reference.
        std::string nm(ftrim(RootName, accINFILE_size));
        nm += ".RO.echo";
        fassign(EchoFilename.data(), EchoFilename_LEN, nm);

        // CALL GetNewUnit(UnEc, ErrVar)
        UnEc = 10;   // GetNewUnit's StartUnit; see above for why this is here
        const std::string echo_path(ftrim(EchoFilename.data(), EchoFilename_LEN));
        ec = std::fopen(echo_path.c_str(), "w");      // ACTION='WRITE'
        if (ec == nullptr) {
            // ErrVar%ErrMsg = 'Cannot open file '//TRIM(EchoFilename)//
            //                 '. Another program may have locked it for writing.'
            std::string msg = "Cannot open file ";
            msg += echo_path;
            msg += ". Another program may have locked it for writing.";
            assign_errmsg(ErrVar, msg);
            ErrVar->aviFAIL = 1;
        } else {
            char date[11], time[8];
            vit_curdate_c(date);
            vit_curtime_c(time);
            ld_write(ec, "ROSCO ECHO file");
            {
                std::string s = "Generated on ";
                s.append(date, 11);
                s += " at ";
                s.append(time, 8);
                s += " using ROSCO-";
                s += std::string(rosco_version);
                ld_write(ec, s);
            }
            ld_write(ec, "\n");                       // NEW_LINE('A')
            {
                std::string s = "Line Number";
                s += Tab;
                s += "Parameter";
                s += Tab;
                s += "Value";
                ld_write(ec, s);
            }
            ld_write(ec, "-----------------------------------------");
        }
    }

    parse_int("LoggingLevel", &CntrPar->LoggingLevel, 1, 1, 1, UnEc);
    parse_dbl("DT_Out", &CntrPar->DT_Out, 1, 1, 1, UnEc);
    parse_int("Ext_Interface", &CntrPar->Ext_Interface, 1, 1, 1, UnEc);
    if (ErrVar->aviFAIL < 0) return;

    //----------------- CONTROLLER FLAGS ---------------------
    parse_int("F_LPFType", &CntrPar->F_LPFType, 0, 0, 1, UnEc);
    parse_int("IPC_ControlMode", &CntrPar->IPC_ControlMode, 0, 0, 1, UnEc);
    parse_int("VS_ControlMode", &CntrPar->VS_ControlMode, 0, 0, 1, UnEc);
    parse_int("VS_ConstPower", &CntrPar->VS_ConstPower, 1, 1, 1, UnEc);
    parse_int("VS_FBP", &CntrPar->VS_FBP, 1, 1, 1, UnEc);
    parse_int("PC_ControlMode", &CntrPar->PC_ControlMode, 0, 0, 1, UnEc);
    parse_int("Y_ControlMode", &CntrPar->Y_ControlMode, 0, 0, 1, UnEc);
    parse_int("SS_Mode", &CntrPar->SS_Mode, 0, 0, 1, UnEc);
    parse_int("PRC_Mode", &CntrPar->PRC_Mode, 0, 0, 1, UnEc);
    parse_int("WE_Mode", &CntrPar->WE_Mode, 0, 0, 1, UnEc);
    parse_int("PS_Mode", &CntrPar->PS_Mode, 0, 0, 1, UnEc);
    parse_int("SU_Mode", &CntrPar->SU_Mode, 0, 0, 1, UnEc);
    parse_int("SD_Mode", &CntrPar->SD_Mode, 0, 0, 1, UnEc);
    parse_int("FL_Mode", &CntrPar->Fl_Mode, 0, 0, 1, UnEc);
    parse_int("TD_Mode", &CntrPar->TD_Mode, 0, 0, 1, UnEc);
    parse_int("TRA_Mode", &CntrPar->TRA_Mode, 0, 0, 1, UnEc);
    parse_int("Flp_Mode", &CntrPar->Flp_Mode, 0, 0, 1, UnEc);
    parse_int("OL_Mode", &CntrPar->OL_Mode, 0, 0, 1, UnEc);
    parse_int("PA_Mode", &CntrPar->PA_Mode, 0, 0, 1, UnEc);
    parse_int("PF_Mode", &CntrPar->PF_Mode, 0, 0, 1, UnEc);
    parse_int("AWC_Mode", &CntrPar->AWC_Mode, 0, 0, 1, UnEc);
    parse_int("Ext_Mode", &CntrPar->Ext_Mode, 0, 0, 1, UnEc);
    parse_int("ZMQ_Mode", &CntrPar->ZMQ_Mode, 0, 0, 1, UnEc);
    parse_int("CC_Mode", &CntrPar->CC_Mode, 0, 0, 1, UnEc);
    parse_int("StC_Mode", &CntrPar->StC_Mode, 0, 0, 1, UnEc);
    if (ErrVar->aviFAIL < 0) return;

    //----------------- FILTER CONSTANTS ---------------------
    parse_dbl("F_LPFCornerFreq", &CntrPar->F_LPFCornerFreq, 1, 0, 1, UnEc);
    parse_dbl("F_LPFDamping", &CntrPar->F_LPFDamping, 1, (CntrPar->F_LPFType == 1) ? 1 : 0, 1, UnEc);
    parse_int("F_NumNotchFilts", &CntrPar->F_NumNotchFilts, 1, 1, 1, UnEc);
    parse_dbary("F_NotchFreqs", &CntrPar->F_NotchFreqs, &CntrPar->n_F_NotchFreqs, CntrPar->F_NumNotchFilts, 1, (CntrPar->F_NumNotchFilts == 0) ? 1 : 0, 1, UnEc);
    parse_dbary("F_NotchBetaNum", &CntrPar->F_NotchBetaNum, &CntrPar->n_F_NotchBetaNum, CntrPar->F_NumNotchFilts, 1, (CntrPar->F_NumNotchFilts == 0) ? 1 : 0, 1, UnEc);
    parse_dbary("F_NotchBetaDen", &CntrPar->F_NotchBetaDen, &CntrPar->n_F_NotchBetaDen, CntrPar->F_NumNotchFilts, 1, (CntrPar->F_NumNotchFilts == 0) ? 1 : 0, 1, UnEc);
    parse_int("F_GenSpdNotch_N", &CntrPar->F_GenSpdNotch_N, 1, (CntrPar->F_NumNotchFilts == 0) ? 1 : 0, 1, UnEc);
    parse_int("F_TwrTopNotch_N", &CntrPar->F_TwrTopNotch_N, 1, (CntrPar->F_NumNotchFilts == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("F_SSCornerFreq", &CntrPar->F_SSCornerFreq, 1, (CntrPar->SS_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("F_WECornerFreq", &CntrPar->F_WECornerFreq, 1, 0, 1, UnEc);
    parse_dbl("F_YawErr", &CntrPar->F_YawErr, 1, (CntrPar->Y_ControlMode == 0) ? 1 : 0, 1, UnEc);
    parse_dbary("F_FlCornerFreq", &CntrPar->F_FlCornerFreq, &CntrPar->n_F_FlCornerFreq, 2, 1, (CntrPar->Fl_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("F_FlHighPassFreq", &CntrPar->F_FlHighPassFreq, 1, (CntrPar->Fl_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbary("F_FlpCornerFreq", &CntrPar->F_FlpCornerFreq, &CntrPar->n_F_FlpCornerFreq, 2, 1, (CntrPar->Flp_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("F_VSRefSpdCornerFreq", &CntrPar->F_VSRefSpdCornerFreq, 1, (CntrPar->VS_ControlMode < 2) ? 1 : 0, 1, UnEc);

    // Optional filter inds
    if (CntrPar->F_GenSpdNotch_N > 0) {
        parse_inary("F_GenSpdNotch_Ind", &CntrPar->F_GenSpdNotch_Ind, &CntrPar->n_F_GenSpdNotch_Ind, CntrPar->F_GenSpdNotch_N, 1, (CntrPar->F_GenSpdNotch_N == 0) ? 1 : 0, 1, UnEc);
    }
    if (CntrPar->F_TwrTopNotch_N > 0) {
        parse_inary("F_TwrTopNotch_Ind", &CntrPar->F_TwrTopNotch_Ind, &CntrPar->n_F_TwrTopNotch_Ind, CntrPar->F_TwrTopNotch_N, 1, (CntrPar->F_TwrTopNotch_N == 0) ? 1 : 0, 1, UnEc);
    }

    if (ErrVar->aviFAIL < 0) return;

    //----------- BLADE PITCH CONTROLLER CONSTANTS -----------
    parse_int("PC_GS_n", &CntrPar->PC_GS_n, 1, (CntrPar->PC_ControlMode == 0) ? 1 : 0, 1, UnEc);
    parse_dbary("PC_GS_angles", &CntrPar->PC_GS_angles, &CntrPar->n_PC_GS_angles, CntrPar->PC_GS_n, 1, (CntrPar->PC_ControlMode == 0) ? 1 : 0, 1, UnEc);
    parse_dbary("PC_GS_KP", &CntrPar->PC_GS_KP, &CntrPar->n_PC_GS_KP, CntrPar->PC_GS_n, 1, (CntrPar->PC_ControlMode == 0) ? 1 : 0, 1, UnEc);
    parse_dbary("PC_GS_KI", &CntrPar->PC_GS_KI, &CntrPar->n_PC_GS_KI, CntrPar->PC_GS_n, 1, (CntrPar->PC_ControlMode == 0) ? 1 : 0, 1, UnEc);
    parse_dbary("PC_GS_KD", &CntrPar->PC_GS_KD, &CntrPar->n_PC_GS_KD, CntrPar->PC_GS_n, 1, (CntrPar->PC_ControlMode == 0) ? 1 : 0, 1, UnEc);
    parse_dbary("PC_GS_TF", &CntrPar->PC_GS_TF, &CntrPar->n_PC_GS_TF, CntrPar->PC_GS_n, 1, (CntrPar->PC_ControlMode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("PC_MaxPit", &CntrPar->PC_MaxPit, 1, (CntrPar->PC_ControlMode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("PC_MinPit", &CntrPar->PC_MinPit, 1, (CntrPar->PC_ControlMode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("PC_MaxRat", &CntrPar->PC_MaxRat, 1, (CntrPar->PC_ControlMode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("PC_MinRat", &CntrPar->PC_MinRat, 1, (CntrPar->PC_ControlMode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("PC_RefSpd", &CntrPar->PC_RefSpd, 1, (CntrPar->PC_ControlMode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("PC_FinePit", &CntrPar->PC_FinePit, 1, (CntrPar->PC_ControlMode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("PC_Switch", &CntrPar->PC_Switch, 1, (CntrPar->PC_ControlMode == 0) ? 1 : 0, 1, UnEc);
    if (ErrVar->aviFAIL < 0) return;

    //------------------- IPC CONSTANTS -----------------------
    parse_dbary("IPC_Vramp", &CntrPar->IPC_Vramp, &CntrPar->n_IPC_Vramp, 2, 1, (CntrPar->IPC_ControlMode == 0) ? 1 : 0, 1, UnEc);
    parse_int("IPC_SatMode", &CntrPar->IPC_SatMode, 1, (CntrPar->IPC_ControlMode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("IPC_IntSat", &CntrPar->IPC_IntSat, 1, (CntrPar->IPC_ControlMode == 0) ? 1 : 0, 1, UnEc);
    parse_dbary("IPC_KP", &CntrPar->IPC_KP, &CntrPar->n_IPC_KP, 2, 1, (CntrPar->IPC_ControlMode == 0) ? 1 : 0, 1, UnEc);
    parse_dbary("IPC_KI", &CntrPar->IPC_KI, &CntrPar->n_IPC_KI, 2, 1, (CntrPar->IPC_ControlMode == 0) ? 1 : 0, 1, UnEc);
    parse_dbary("IPC_aziOffset", &CntrPar->IPC_aziOffset, &CntrPar->n_IPC_aziOffset, 2, 1, (CntrPar->IPC_ControlMode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("IPC_CornerFreqAct", &CntrPar->IPC_CornerFreqAct, 1, (CntrPar->IPC_ControlMode == 0) ? 1 : 0, 1, UnEc);
    if (ErrVar->aviFAIL < 0) return;

    //------------ VS TORQUE CONTROL CONSTANTS ----------------
    parse_dbl("VS_GenEff", &CntrPar->VS_GenEff, 1, 0, 1, UnEc);
    parse_dbl("VS_ArSatTq", &CntrPar->VS_ArSatTq, 1, (CntrPar->VS_ControlMode != 1) ? 1 : 0, 1, UnEc);
    parse_dbl("VS_MaxRat", &CntrPar->VS_MaxRat, 1, (CntrPar->VS_ControlMode != 1) ? 1 : 0, 1, UnEc);
    parse_dbl("VS_MaxTq", &CntrPar->VS_MaxTq, 1, 0, 1, UnEc);
    parse_dbl("VS_MinTq", &CntrPar->VS_MinTq, 1, 0, 1, UnEc);
    parse_dbl("VS_MinOMSpd", &CntrPar->VS_MinOMSpd, 0, 0, 0, 0);
    parse_dbl("VS_Rgn2K", &CntrPar->VS_Rgn2K, 1, (CntrPar->VS_ControlMode == 2) ? 1 : 0, 1, UnEc);
    parse_dbl("VS_RtPwr", &CntrPar->VS_RtPwr, 1, 0, 1, UnEc);
    parse_dbl("VS_RtTq", &CntrPar->VS_RtTq, 1, 0, 1, UnEc);
    parse_dbl("VS_RefSpd", &CntrPar->VS_RefSpd, 1, 0, 1, UnEc);
    parse_int("VS_n", &CntrPar->VS_n, 1, 0, 1, UnEc);
    parse_dbary("VS_KP", &CntrPar->VS_KP, &CntrPar->n_VS_KP, CntrPar->VS_n, 1, 0, 1, UnEc);
    parse_dbary("VS_KI", &CntrPar->VS_KI, &CntrPar->n_VS_KI, CntrPar->VS_n, 1, 0, 1, UnEc);
    parse_dbl("VS_TSRopt", &CntrPar->VS_TSRopt, 1, (CntrPar->VS_ControlMode < 2) ? 1 : 0, 1, UnEc);
    if (ErrVar->aviFAIL < 0) return;

    //------------ Fixed-Pitch Region 3 Control ------------
    parse_int("VS_FBP_n", &CntrPar->VS_FBP_n, 1, (CntrPar->VS_FBP == VS_FBP_Variable_Pitch) ? 1 : 0, 1, UnEc);
    parse_dbary("VS_FBP_U", &CntrPar->VS_FBP_U, &CntrPar->n_VS_FBP_U, CntrPar->VS_FBP_n, 1, (CntrPar->VS_FBP == VS_FBP_Variable_Pitch) ? 1 : 0, 1, UnEc);
    parse_dbary("VS_FBP_Omega", &CntrPar->VS_FBP_Omega, &CntrPar->n_VS_FBP_Omega, CntrPar->VS_FBP_n, 1, (CntrPar->VS_FBP == VS_FBP_Variable_Pitch) ? 1 : 0, 1, UnEc);
    parse_dbary("VS_FBP_Tau", &CntrPar->VS_FBP_Tau, &CntrPar->n_VS_FBP_Tau, CntrPar->VS_FBP_n, 1, (CntrPar->VS_FBP == VS_FBP_Variable_Pitch) ? 1 : 0, 1, UnEc);
    if (ErrVar->aviFAIL < 0) return;

    //------- Setpoint Smoother --------------------------------
    parse_dbl("SS_VSGain", &CntrPar->SS_VSGain, 1, (CntrPar->SS_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("SS_PCGain", &CntrPar->SS_PCGain, 1, (CntrPar->SS_Mode == 0) ? 1 : 0, 1, UnEc);
    if (ErrVar->aviFAIL < 0) return;

    //------------ POWER REFERENCE TRACKING SETPOINTS --------------
    parse_int("PRC_Comm", &CntrPar->PRC_Comm, 1, (CntrPar->PRC_Mode != 1) ? 1 : 0, 1, UnEc);
    parse_dbl("PRC_R_Torque", &CntrPar->PRC_R_Torque, 1, ((CntrPar->PRC_Mode != 2) || (CntrPar->PRC_Comm != PRC_Comm_Constant)) ? 1 : 0, 1, UnEc);
    parse_dbl("PRC_R_Speed", &CntrPar->PRC_R_Speed, 1, ((CntrPar->PRC_Mode != 2) || (CntrPar->PRC_Comm != PRC_Comm_Constant)) ? 1 : 0, 1, UnEc);
    parse_dbl("PRC_R_Pitch", &CntrPar->PRC_R_Pitch, 1, ((CntrPar->PRC_Mode != 2) || (CntrPar->PRC_Comm != PRC_Comm_Constant)) ? 1 : 0, 1, UnEc);
    parse_int("PRC_Table_n", &CntrPar->PRC_Table_n, 1, ((CntrPar->PRC_Mode != 2) || (CntrPar->PRC_R_Pitch == 1.0)) ? 1 : 0, 1, UnEc);
    parse_dbary("PRC_R_Table", &CntrPar->PRC_R_Table, &CntrPar->n_PRC_R_Table, CntrPar->PRC_Table_n, 1, ((CntrPar->PRC_Mode != 2) || (CntrPar->PRC_R_Pitch == 1.0)) ? 1 : 0, 1, UnEc);
    parse_dbary("PRC_Pitch_Table", &CntrPar->PRC_Pitch_Table, &CntrPar->n_PRC_Pitch_Table, CntrPar->PRC_Table_n, 1, ((CntrPar->PRC_Mode != 2) || (CntrPar->PRC_R_Pitch == 1.0)) ? 1 : 0, 1, UnEc);
    parse_int("PRC_n", &CntrPar->PRC_n, 1, (CntrPar->PRC_Mode == 0) ? 1 : 0, 0, 0);
    parse_dbl("PRC_LPF_Freq", &CntrPar->PRC_LPF_Freq, 1, (CntrPar->PRC_Mode == 0) ? 1 : 0, 0, 0);
    parse_dbary("PRC_WindSpeeds", &CntrPar->PRC_WindSpeeds, &CntrPar->n_PRC_WindSpeeds, CntrPar->PRC_n, 1, (CntrPar->PRC_Mode == 0) ? 1 : 0, 0, 0);
    parse_dbary("PRC_GenSpeeds", &CntrPar->PRC_GenSpeeds, &CntrPar->n_PRC_GenSpeeds, CntrPar->PRC_n, 1, (CntrPar->PRC_Mode == 0) ? 1 : 0, 0, 0);

    //------------ WIND SPEED ESTIMATOR CONTANTS --------------
    parse_dbl("WE_BladeRadius", &CntrPar->WE_BladeRadius, 1, 0, 1, UnEc);
    parse_dbl("WE_Gamma", &CntrPar->WE_Gamma, 1, (CntrPar->WE_Mode != 1) ? 1 : 0, 1, UnEc);
    parse_dbl("WE_GearboxRatio", &CntrPar->WE_GearboxRatio, 1, 0, 1, UnEc);
    parse_dbl("WE_Jtot", &CntrPar->WE_Jtot, 1, (CntrPar->WE_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("WE_RhoAir", &CntrPar->WE_RhoAir, 1, (CntrPar->WE_Mode != 2) ? 1 : 0, 1, UnEc);
    parse_str("PerfFileName", CntrPar->PerfFileName, 1024, 1, (CntrPar->WE_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_inary("PerfTableSize", &CntrPar->PerfTableSize, &CntrPar->n_PerfTableSize, 2, 1, (CntrPar->WE_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_int("WE_FOPoles_N", &CntrPar->WE_FOPoles_N, 1, (CntrPar->WE_Mode != 2) ? 1 : 0, 1, UnEc);
    parse_dbary("WE_FOPoles_v", &CntrPar->WE_FOPoles_v, &CntrPar->n_WE_FOPoles_v, CntrPar->WE_FOPoles_N, 1, (CntrPar->WE_Mode != 2) ? 1 : 0, 1, UnEc);
    parse_dbary("WE_FOPoles", &CntrPar->WE_FOPoles, &CntrPar->n_WE_FOPoles, CntrPar->WE_FOPoles_N, 1, (CntrPar->WE_Mode != 2) ? 1 : 0, 1, UnEc);
    if (ErrVar->aviFAIL < 0) return;

    // Retired WSE inputs:  not used anywhere in code
    // CALL ParseInput(FileLines,  'WE_CP_n',accINFILE(1),CntrPar%WE_CP_n,ErrVar, UnEc)
    // CALL ParseAry(  FileLines,  'WE_CP', CntrPar%WE_CP, CntrPar%WE_CP_n, accINFILE(1), ErrVar, .FALSE. , UnEc)

    //-------------- YAW CONTROLLER CONSTANTS -----------------
    parse_dbl("Y_uSwitch", &CntrPar->Y_uSwitch, 1, (CntrPar->Y_ControlMode == 0) ? 1 : 0, 1, UnEc);
    parse_dbary("Y_ErrThresh", &CntrPar->Y_ErrThresh, &CntrPar->n_Y_ErrThresh, 2, 1, (CntrPar->Y_ControlMode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("Y_Rate", &CntrPar->Y_Rate, 1, (CntrPar->Y_ControlMode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("Y_MErrSet", &CntrPar->Y_MErrSet, 1, (CntrPar->Y_ControlMode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("Y_IPC_IntSat", &CntrPar->Y_IPC_IntSat, 1, (CntrPar->Y_ControlMode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("Y_IPC_KP", &CntrPar->Y_IPC_KP, 1, (CntrPar->Y_ControlMode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("Y_IPC_KI", &CntrPar->Y_IPC_KI, 1, (CntrPar->Y_ControlMode == 0) ? 1 : 0, 1, UnEc);
    if (ErrVar->aviFAIL < 0) return;

    //------------ FORE-AFT TOWER DAMPER CONSTANTS ------------
    parse_dbl("TRA_ExclSpeed", &CntrPar->TRA_ExclSpeed, 1, (CntrPar->TRA_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("TRA_ExclBand", &CntrPar->TRA_ExclBand, 1, (CntrPar->TRA_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("TRA_RateLimit", &CntrPar->TRA_RateLimit, 1, (CntrPar->TRA_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("FA_KI", &CntrPar->FA_KI, 1, (CntrPar->TD_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("FA_HPFCornerFreq", &CntrPar->FA_HPFCornerFreq, 1, (CntrPar->TD_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("FA_IntSat", &CntrPar->FA_IntSat, 1, (CntrPar->TD_Mode == 0) ? 1 : 0, 1, UnEc);
    if (ErrVar->aviFAIL < 0) return;

    //------------ PEAK SHAVING ------------
    parse_int("PS_BldPitchMin_N", &CntrPar->PS_BldPitchMin_N, 1, (CntrPar->PS_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbary("PS_WindSpeeds", &CntrPar->PS_WindSpeeds, &CntrPar->n_PS_WindSpeeds, CntrPar->PS_BldPitchMin_N, 1, (CntrPar->PS_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbary("PS_BldPitchMin", &CntrPar->PS_BldPitchMin, &CntrPar->n_PS_BldPitchMin, CntrPar->PS_BldPitchMin_N, 1, (CntrPar->PS_Mode == 0) ? 1 : 0, 1, UnEc);
    if (ErrVar->aviFAIL < 0) return;

    //------------ STARTUP ------------
    parse_dbl("SU_StartTime", &CntrPar->SU_StartTime, 1, (CntrPar->SU_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("SU_FW_MinDuration", &CntrPar->SU_FW_MinDuration, 1, (CntrPar->SU_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("SU_RotorSpeedThresh", &CntrPar->SU_RotorSpeedThresh, 1, (CntrPar->SU_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("SU_RotorSpeedCornerFreq", &CntrPar->SU_RotorSpeedCornerFreq, 1, (CntrPar->SU_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_int("SU_LoadStages_N", &CntrPar->SU_LoadStages_N, 1, (CntrPar->SU_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbary("SU_LoadStages", &CntrPar->SU_LoadStages, &CntrPar->n_SU_LoadStages, CntrPar->SU_LoadStages_N, 1, (CntrPar->SU_LoadStages_N == 0) ? 1 : 0, 1, UnEc);
    parse_dbary("SU_LoadRampDuration", &CntrPar->SU_LoadRampDuration, &CntrPar->n_SU_LoadRampDuration, CntrPar->SU_LoadStages_N, 1, (CntrPar->SU_LoadStages_N == 0) ? 1 : 0, 1, UnEc);
    parse_dbary("SU_LoadHoldDuration", &CntrPar->SU_LoadHoldDuration, &CntrPar->n_SU_LoadHoldDuration, CntrPar->SU_LoadStages_N, 1, (CntrPar->SU_LoadStages_N == 0) ? 1 : 0, 1, UnEc);

    //------------ SHUTDOWN ------------
    parse_dbl("SD_TimeActivate", &CntrPar->SD_TimeActivate, 1, (CntrPar->SD_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_int("SD_EnablePitch", &CntrPar->SD_EnablePitch, 1, (CntrPar->SD_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_int("SD_EnableYawError", &CntrPar->SD_EnableYawError, 1, (CntrPar->SD_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_int("SD_EnableGenSpeed", &CntrPar->SD_EnableGenSpeed, 1, (CntrPar->SD_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_int("SD_EnableTime", &CntrPar->SD_EnableTime, 1, (CntrPar->SD_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("SD_MaxPit", &CntrPar->SD_MaxPit, 1, (CntrPar->SD_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("SD_PitchCornerFreq", &CntrPar->SD_PitchCornerFreq, 1, (CntrPar->SD_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("SD_MaxYawError", &CntrPar->SD_MaxYawError, 1, (CntrPar->SD_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("SD_YawErrorCornerFreq", &CntrPar->SD_YawErrorCornerFreq, 1, (CntrPar->SD_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("SD_MaxGenSpd", &CntrPar->SD_MaxGenSpd, 1, (CntrPar->SD_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("SD_GenSpdCornerFreq", &CntrPar->SD_GenSpdCornerFreq, 1, (CntrPar->SD_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("SD_Time", &CntrPar->SD_Time, 1, (CntrPar->SD_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_int("SD_Method", &CntrPar->SD_Method, 1, (CntrPar->SD_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_int("SD_Stage_N", &CntrPar->SD_Stage_N, 1, (CntrPar->SD_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbary("SD_StageTime", &CntrPar->SD_StageTime, &CntrPar->n_SD_StageTime, CntrPar->SD_Stage_N, 1, (CntrPar->SD_Method != 1) ? 1 : 0, 1, UnEc);
    parse_dbary("SD_StagePitch", &CntrPar->SD_StagePitch, &CntrPar->n_SD_StagePitch, CntrPar->SD_Stage_N, 1, (CntrPar->SD_Method != 2) ? 1 : 0, 1, UnEc);
    parse_dbary("SD_MaxTorqueRate", &CntrPar->SD_MaxTorqueRate, &CntrPar->n_SD_MaxTorqueRate, CntrPar->SD_Stage_N, 1, (CntrPar->SD_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbary("SD_MaxPitchRate", &CntrPar->SD_MaxPitchRate, &CntrPar->n_SD_MaxPitchRate, CntrPar->SD_Stage_N, 1, (CntrPar->SD_Mode == 0) ? 1 : 0, 1, UnEc);
    if (ErrVar->aviFAIL < 0) return;

    //------------ FLOATING ------------
    parse_int("Fl_n", &CntrPar->Fl_n, 1, 1, 1, UnEc);
    if (CntrPar->Fl_n == 0) CntrPar->Fl_n = 1;
    parse_dbary("Fl_Kp", &CntrPar->Fl_Kp, &CntrPar->n_Fl_Kp, CntrPar->Fl_n, 1, (CntrPar->Fl_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbary("Fl_U", &CntrPar->Fl_U, &CntrPar->n_Fl_U, CntrPar->Fl_n, 1, (CntrPar->Fl_n == 1) ? 1 : 0, 1, UnEc);
    if (ErrVar->aviFAIL < 0) return;

    //------------ Flaps ------------
    parse_dbl("Flp_Angle", &CntrPar->Flp_Angle, 1, (CntrPar->Flp_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("Flp_Kp", &CntrPar->Flp_Kp, 1, (CntrPar->Flp_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("Flp_Ki", &CntrPar->Flp_Ki, 1, (CntrPar->Flp_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("Flp_MaxPit", &CntrPar->Flp_MaxPit, 1, (CntrPar->Flp_Mode == 0) ? 1 : 0, 1, UnEc);
    if (ErrVar->aviFAIL < 0) return;

    //------------ Open loop input ------------
    // Indices can be left 0 by default, checked later
    parse_str("OL_Filename", CntrPar->OL_Filename, 1024, 1, (CntrPar->OL_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_int("OL_BP_Mode", &CntrPar->OL_BP_Mode, 1, (CntrPar->OL_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("OL_BP_FiltFreq", &CntrPar->OL_BP_FiltFreq, 1, (CntrPar->OL_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_int("Ind_Breakpoint", &CntrPar->Ind_Breakpoint, 0, 0, 1, UnEc);
    parse_inary("Ind_BldPitch", &CntrPar->Ind_BldPitch, &CntrPar->n_Ind_BldPitch, 3, 0, 0, 1, UnEc);
    parse_int("Ind_GenTq", &CntrPar->Ind_GenTq, 0, 0, 1, UnEc);
    parse_int("Ind_YawRate", &CntrPar->Ind_YawRate, 0, 0, 1, UnEc);
    parse_int("Ind_Azimuth", &CntrPar->Ind_Azimuth, 1, (CntrPar->OL_Mode != 2) ? 1 : 0, 1, UnEc);
    parse_int("Ind_R_Speed", &CntrPar->Ind_R_Speed, 1, (CntrPar->OL_Mode != 2) ? 1 : 0, 1, UnEc);
    parse_int("Ind_R_Torque", &CntrPar->Ind_R_Torque, 1, (CntrPar->OL_Mode != 2) ? 1 : 0, 1, UnEc);
    parse_int("Ind_R_Pitch", &CntrPar->Ind_R_Pitch, 1, (CntrPar->OL_Mode != 2) ? 1 : 0, 1, UnEc);
    parse_dbary("RP_Gains", &CntrPar->RP_Gains, &CntrPar->n_RP_Gains, 4, 1, (CntrPar->OL_Mode != 2) ? 1 : 0, 1, UnEc);
    if (ErrVar->aviFAIL < 0) return;

    //------------ Pitch Actuator Inputs ------------
    parse_dbl("PA_CornerFreq", &CntrPar->PA_CornerFreq, 1, (CntrPar->PA_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("PA_Damping", &CntrPar->PA_Damping, 1, (CntrPar->PA_Mode == 0) ? 1 : 0, 1, UnEc);
    if (ErrVar->aviFAIL < 0) return;

    //------------ Pitch Actuator Faults ------------
    parse_dbary("PF_Offsets", &CntrPar->PF_Offsets, &CntrPar->n_PF_Offsets, 3, 1, (CntrPar->PF_Mode != 1) ? 1 : 0, 1, UnEc);
    parse_dbary("PF_TimeStuck", &CntrPar->PF_TimeStuck, &CntrPar->n_PF_TimeStuck, 3, 1, (CntrPar->PF_Mode != 2) ? 1 : 0, 1, UnEc);
    if (ErrVar->aviFAIL < 0) return;

    //------------ AWC input ------------
    parse_int("AWC_NumModes", &CntrPar->AWC_NumModes, 1, (CntrPar->AWC_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_inary("AWC_n", &CntrPar->AWC_n, &CntrPar->n_AWC_n, CntrPar->AWC_NumModes, 1, (CntrPar->AWC_Mode != 1) ? 1 : 0, 1, UnEc);
    parse_inary("AWC_harmonic", &CntrPar->AWC_harmonic, &CntrPar->n_AWC_harmonic, CntrPar->AWC_NumModes, 1, (CntrPar->AWC_Mode < 2) ? 1 : 0, 1, UnEc);
    parse_dbary("AWC_freq", &CntrPar->AWC_freq, &CntrPar->n_AWC_freq, CntrPar->AWC_NumModes, 1, (CntrPar->AWC_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbary("AWC_amp", &CntrPar->AWC_amp, &CntrPar->n_AWC_amp, CntrPar->AWC_NumModes, 1, (CntrPar->AWC_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbary("AWC_clockangle", &CntrPar->AWC_clockangle, &CntrPar->n_AWC_clockangle, CntrPar->AWC_NumModes, 1, (CntrPar->AWC_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("AWC_phaseoffset", &CntrPar->AWC_phaseoffset, 1, (CntrPar->AWC_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbary("AWC_CntrGains", &CntrPar->AWC_CntrGains, &CntrPar->n_AWC_CntrGains, 2, 1, (CntrPar->AWC_Mode < 3) ? 1 : 0, 1, UnEc);
    if (ErrVar->aviFAIL < 0) return;

    //------------ External control interface ------------
    parse_str("DLL_FileName", CntrPar->DLL_FileName, 1024, 1, (CntrPar->Ext_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_str("DLL_InFile", CntrPar->DLL_InFile, 1024, 1, (CntrPar->Ext_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_str("DLL_ProcName", CntrPar->DLL_ProcName, 1024, 1, (CntrPar->Ext_Mode == 0) ? 1 : 0, 1, UnEc);
    if (ErrVar->aviFAIL < 0) return;

    //------------ ZeroMQ ------------
    parse_int("ZMQ_ID", &CntrPar->ZMQ_ID, 1, 1, 1, UnEc);
    parse_str("ZMQ_CommAddress", CntrPar->ZMQ_CommAddress, 256, 1, (CntrPar->ZMQ_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("ZMQ_UpdatePeriod", &CntrPar->ZMQ_UpdatePeriod, 1, (CntrPar->ZMQ_Mode == 0) ? 1 : 0, 1, UnEc);
    if (ErrVar->aviFAIL < 0) return;

    //------------- Cable Control -----
    parse_int("CC_Group_N", &CntrPar->CC_Group_N, 1, (CntrPar->CC_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_inary("CC_GroupIndex", &CntrPar->CC_GroupIndex, &CntrPar->n_CC_GroupIndex, CntrPar->CC_Group_N, 1, (CntrPar->CC_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_dbl("CC_ActTau", &CntrPar->CC_ActTau, 1, (CntrPar->CC_Mode == 0) ? 1 : 0, 1, UnEc);
    if (ErrVar->aviFAIL < 0) return;

    //------------- StC Control -----
    parse_int("StC_Group_N", &CntrPar->StC_Group_N, 1, (CntrPar->StC_Mode == 0) ? 1 : 0, 1, UnEc);
    parse_inary("StC_GroupIndex", &CntrPar->StC_GroupIndex, &CntrPar->n_StC_GroupIndex, CntrPar->StC_Group_N, 1, (CntrPar->StC_Mode == 0) ? 1 : 0, 1, UnEc);
    if (ErrVar->aviFAIL < 0) return;

    // Open loop cable, structural control, needs number of groups
    parse_inary("Ind_CableControl", &CntrPar->Ind_CableControl, &CntrPar->n_Ind_CableControl, CntrPar->CC_Group_N, 1, (CntrPar->CC_Mode != 2) ? 1 : 0, 1, UnEc);
    parse_inary("Ind_StructControl", &CntrPar->Ind_StructControl, &CntrPar->n_Ind_StructControl, CntrPar->StC_Group_N, 1, (CntrPar->StC_Mode != 2) ? 1 : 0, 1, UnEc);
    if (ErrVar->aviFAIL < 0) return;

    // IF (UnEc > 0) CLOSE(UnEc)     ! Close echo file
    //
    // `UnEc > 0` is TRUE even when the OPEN above failed -- GetNewUnit ran
    // first. A CLOSE of an unconnected unit is a legal no-op in Fortran, so
    // the guard here is on the stream and not on the flag.
    if (UnEc > 0 && ec != nullptr) std::fclose(ec);
    ec = nullptr;

    //-------------------
    //------------------- CALCULATED CONSTANTS -----------------------
    //----------------------------------------------------------------

    // ! Fix defaults manually for now
    if (CntrPar->DT_Out == 0) {
        CntrPar->DT_Out = LocalVar->DT;
    }

    // ! DT_Out -- NINT is round-half-AWAY-FROM-ZERO; a cast truncates and
    // std::rint is half-to-even. std::lround is the one that agrees.
    CntrPar->n_DT_Out = static_cast<int>(std::lround(CntrPar->DT_Out / LocalVar->DT));
    CntrPar->n_DT_ZMQ =
        static_cast<int>(std::lround(CntrPar->ZMQ_UpdatePeriod / LocalVar->DT));

    // ! Fix Paths (add relative paths if called from another dir, UnEc)
    // IF (PathIsRelative(CntrPar%PerfFileName))
    //     CntrPar%PerfFileName = TRIM(PriPath)//TRIM(CntrPar%PerfFileName)
    //
    // The right-hand side READS the field it is assigned to. Fortran evaluates
    // it whole before assigning, so the concatenation is built first and the
    // blank-fill to 1024 happens after -- which is why the source string is
    // materialised here rather than written in place.
    if (pathisrelative_c(CntrPar->PerfFileName, 1024) != 0) {
        std::string s(ftrim(PriPath.data(), PriPath_LEN));
        s.append(ftrim(CntrPar->PerfFileName, 1024));
        fassign(CntrPar->PerfFileName, 1024, s);
    }
    if (pathisrelative_c(CntrPar->OL_Filename, 1024) != 0) {
        std::string s(ftrim(PriPath.data(), PriPath_LEN));
        s.append(ftrim(CntrPar->OL_Filename, 1024));
        fassign(CntrPar->OL_Filename, 1024, s);
    }

    // ! Convert yaw rate to deg/s
    CntrPar->Y_Rate = CntrPar->Y_Rate * R2D;

    CntrPar->PC_RtTq99 = CntrPar->VS_RtTq * 0.99;
    // `A*B**2` is `A * (B*B)` in Fortran -- `**` binds tighter than `*`. The
    // C++ `A * B * B` is `(A*B) * B` and rounds differently.
    CntrPar->VS_MinOMTq =
        CntrPar->VS_Rgn2K * (CntrPar->VS_MinOMSpd * CntrPar->VS_MinOMSpd);
    CntrPar->VS_MaxOMTq =
        CntrPar->VS_Rgn2K * (CntrPar->VS_RefSpd * CntrPar->VS_RefSpd);

    // ! Read open loop input, if desired
    if (CntrPar->OL_Mode > 0) {
        // CHARACTER(1024) :: OL_String ; OL_String = ''
        std::string OL_String;                 // held trimmed; see ol_cat
        int OL_Count = 1;

        // Every append in this block is `OL_String = TRIM(OL_String)//'...'`,
        // so the value that carries forward is the TRIMMED one -- a plain
        // std::string append is that exactly, provided the 1024-byte width is
        // still enforced, because the reference's assignment TRUNCATES.
        auto ol_cat = [&](std::string_view piece) {
            OL_String += piece;
            if (static_cast<int>(OL_String.size()) > OL_String_LEN)
                OL_String.resize(static_cast<size_t>(OL_String_LEN));
            // TRIM of the truncated, blank-filled result: trailing blanks go.
            while (!OL_String.empty() && OL_String.back() == ' ')
                OL_String.pop_back();
        };

        const int* Ind_BldPitch = CntrPar->Ind_BldPitch;
        if (Ind_BldPitch != nullptr && CntrPar->n_Ind_BldPitch >= 1 &&
            Ind_BldPitch[0] > 0) {
            ol_cat(" BldPitch1 ");
            OL_Count = OL_Count + 1;
        }

        if (Ind_BldPitch != nullptr && CntrPar->n_Ind_BldPitch >= 2 &&
            Ind_BldPitch[1] > 0) {
            ol_cat(" BldPitch2 ");
            // ! If there are duplicate indices, don't increment OL_Count
            if (!((Ind_BldPitch[1] == Ind_BldPitch[0]) ||
                  (Ind_BldPitch[1] == Ind_BldPitch[2]))) {
                OL_Count = OL_Count + 1;
            }
        }

        if (Ind_BldPitch != nullptr && CntrPar->n_Ind_BldPitch >= 3 &&
            Ind_BldPitch[2] > 0) {
            ol_cat(" BldPitch3 ");
            if (!((Ind_BldPitch[2] == Ind_BldPitch[0]) ||
                  (Ind_BldPitch[2] == Ind_BldPitch[1]))) {
                OL_Count = OL_Count + 1;
            }
        }

        if (CntrPar->Ind_GenTq > 0) {
            ol_cat(" GenTq ");
            OL_Count = OL_Count + 1;   // ! Read channel still, so we don't have issues
        }

        if (CntrPar->Ind_YawRate > 0) {
            ol_cat(" YawRate ");
            OL_Count = OL_Count + 1;
        }

        if (CntrPar->Ind_Azimuth > 0) {
            if (CntrPar->OL_Mode == 2) {
                ol_cat(" Azimuth ");
                OL_Count = OL_Count + 1;
            }
        }

        if (CntrPar->Ind_R_Speed > 0) {
            if (CntrPar->OL_Mode == 1) {
                ol_cat(" R_Speed ");
                OL_Count = OL_Count + 1;
            }
        }

        if (CntrPar->Ind_R_Torque > 0) {
            if (CntrPar->OL_Mode == 1) {
                ol_cat(" R_Torque ");
                OL_Count = OL_Count + 1;
            }
        }

        if (CntrPar->Ind_R_Pitch > 0) {
            if (CntrPar->OL_Mode == 1) {
                ol_cat(" R_Pitch ");
                OL_Count = OL_Count + 1;
            }
        }

        int N_OL_Cables = 0;
        if (any_gt(CntrPar->Ind_CableControl, CntrPar->n_Ind_CableControl, 0)) {
            for (int32_t I = 1; I <= CntrPar->n_Ind_CableControl; ++I) {
                if (CntrPar->Ind_CableControl[I - 1] > 0) {
                    char n11[11];
                    int2lstr_c(static_cast<int>(I), n11);
                    std::string s = " Cable";
                    s.append(ftrim(n11, 11));
                    s += " ";
                    ol_cat(s);
                    OL_Count = OL_Count + 1;
                    N_OL_Cables = N_OL_Cables + 1;
                }
            }
        }

        int N_OL_StCs = 0;
        if (any_gt(CntrPar->Ind_StructControl, CntrPar->n_Ind_StructControl, 0)) {
            for (int32_t I = 1; I <= CntrPar->n_Ind_StructControl; ++I) {
                if (CntrPar->Ind_StructControl[I - 1] > 0) {
                    char n11[11];
                    int2lstr_c(static_cast<int>(I), n11);
                    std::string s = " StC";
                    s.append(ftrim(n11, 11));
                    s += " ";
                    ol_cat(s);
                    OL_Count = OL_Count + 1;
                    N_OL_StCs = N_OL_StCs + 1;
                }
            }
        }

        // PRINT *, '...'//TRIM(OL_String) -- list-directed to stdout: one
        // leading blank, the text, a newline. Same layout measured for the
        // echo records.
        ld_write(stdout,
                 std::string("ROSCO: Implementing open loop control for") + OL_String);
        if (CntrPar->OL_Mode == 2) {
            ld_write(stdout,
                     "ROSCO: OL_Mode = 2 will change generator torque control "
                     "for Azimuth tracking");
        }

        // CALL GetNewUnit(UnOpenLoop, ErrVar) -- see the header: a unit number
        // has no C representation, and the callee ignores the argument for the
        // same reason (read_ol_input.cpp:282).
        const int UnOpenLoop = 0;

        // CALL Read_OL_Input(CntrPar%OL_Filename, UnOpenLoop, OL_Count,
        //                    CntrPar%OL_Channels, ErrVar)
        {
            double* ch = nullptr;
            int rows = 0, cols = 0;
            read_ol_input_c(CntrPar->OL_Filename, UnOpenLoop, OL_Count,
                            &ch, &rows, &cols, ErrVar);
            CntrPar->OL_Channels = ch;
            CntrPar->n_OL_Channels_rows = static_cast<int32_t>(rows);
            CntrPar->n_OL_Channels_cols = static_cast<int32_t>(cols);
        }
        if (ErrVar->aviFAIL < 0) {
            return;
        }

        // OL_Channels is (rows, cols) COLUMN-MAJOR, so `OL_Channels(:, j)` is
        // the CONTIGUOUS run at (j-1)*rows and its length is `rows`.
        const int32_t ol_rows = CntrPar->n_OL_Channels_rows;
        const double* const OL_Channels = CntrPar->OL_Channels;
        auto column = [&](int j) -> const double* {
            return OL_Channels + static_cast<size_t>(j - 1) * ol_rows;
        };
        // An intrinsic assignment to an unallocated ALLOCATABLE allocates it
        // to the right-hand side's shape (F2003 allocate-on-assignment).
        auto assign_column = [&](double** dst, int32_t* n, int j) {
            double* p = static_cast<double*>(
                std::malloc(static_cast<size_t>(ol_rows) * sizeof(double)));
            if (p != nullptr && ol_rows > 0)
                std::memcpy(p, column(j), static_cast<size_t>(ol_rows) * sizeof(double));
            *dst = p;
            *n = ol_rows;
        };

        // CntrPar%OL_Breakpoints = CntrPar%OL_Channels(:,CntrPar%Ind_Breakpoint)
        assign_column(&CntrPar->OL_Breakpoints, &CntrPar->n_OL_Breakpoints,
                      CntrPar->Ind_Breakpoint);

        // ! Set OL Inputs based on indices
        if (Ind_BldPitch != nullptr && CntrPar->n_Ind_BldPitch >= 1 &&
            Ind_BldPitch[0] > 0) {
            assign_column(&CntrPar->OL_BldPitch1, &CntrPar->n_OL_BldPitch1,
                          Ind_BldPitch[0]);
        }
        if (Ind_BldPitch != nullptr && CntrPar->n_Ind_BldPitch >= 2 &&
            Ind_BldPitch[1] > 0) {
            assign_column(&CntrPar->OL_BldPitch2, &CntrPar->n_OL_BldPitch2,
                          Ind_BldPitch[1]);
        }
        if (Ind_BldPitch != nullptr && CntrPar->n_Ind_BldPitch >= 3 &&
            Ind_BldPitch[2] > 0) {
            assign_column(&CntrPar->OL_BldPitch3, &CntrPar->n_OL_BldPitch3,
                          Ind_BldPitch[2]);
        }
        if (CntrPar->Ind_GenTq > 0) {
            assign_column(&CntrPar->OL_GenTq, &CntrPar->n_OL_GenTq,
                          CntrPar->Ind_GenTq);
        }
        if (CntrPar->Ind_YawRate > 0) {
            assign_column(&CntrPar->OL_YawRate, &CntrPar->n_OL_YawRate,
                          CntrPar->Ind_YawRate);
        }
        if (CntrPar->Ind_Azimuth > 0) {
            // CntrPar%OL_Azimuth = Unwrap(OL_Channels(:,Ind_Azimuth), ErrVar)
            double* p = static_cast<double*>(
                std::malloc(static_cast<size_t>(ol_rows) * sizeof(double)));
            unwrap_c(const_cast<double*>(column(CntrPar->Ind_Azimuth)),
                     static_cast<int>(ol_rows), ErrVar, p);
            CntrPar->OL_Azimuth = p;
            CntrPar->n_OL_Azimuth = ol_rows;
        }
        if (CntrPar->Ind_R_Speed > 0) {
            assign_column(&CntrPar->OL_R_Speed, &CntrPar->n_OL_R_Speed,
                          CntrPar->Ind_R_Speed);
        }
        if (CntrPar->Ind_R_Torque > 0) {
            assign_column(&CntrPar->OL_R_Torque, &CntrPar->n_OL_R_Torque,
                          CntrPar->Ind_R_Torque);
        }
        if (CntrPar->Ind_R_Pitch > 0) {
            assign_column(&CntrPar->OL_R_Pitch, &CntrPar->n_OL_R_Pitch,
                          CntrPar->Ind_R_Pitch);
        }

        // ALLOCATE(CntrPar%OL_CableControl(N_OL_Cables, SIZE(OL_Channels,DIM=1)))
        // CntrPar%OL_CableControl(I_OL,:) = OL_Channels(:,Ind_CableControl(I))
        //
        // The destination is (N_OL_Cables x rows) COLUMN-MAJOR, and `(I_OL,:)`
        // is a STRIDED ROW of it: element (I_OL,k) sits at
        // (k-1)*N_OL_Cables + (I_OL-1). It is not a pointer and cannot be
        // memcpy'd.
        if (any_gt(CntrPar->Ind_CableControl, CntrPar->n_Ind_CableControl, 0)) {
            double* p = static_cast<double*>(std::malloc(
                static_cast<size_t>(N_OL_Cables) * ol_rows * sizeof(double)));
            CntrPar->OL_CableControl = p;
            CntrPar->n_OL_CableControl_rows = static_cast<int32_t>(N_OL_Cables);
            CntrPar->n_OL_CableControl_cols = ol_rows;
            int I_OL = 1;
            for (int32_t I = 1; I <= CntrPar->n_Ind_CableControl; ++I) {
                if (CntrPar->Ind_CableControl[I - 1] > 0) {
                    const double* src = column(CntrPar->Ind_CableControl[I - 1]);
                    for (int32_t k = 1; k <= ol_rows; ++k)
                        p[static_cast<size_t>(k - 1) * N_OL_Cables + (I_OL - 1)] =
                            src[k - 1];
                    I_OL = I_OL + 1;
                }
            }
        }

        if (any_gt(CntrPar->Ind_StructControl, CntrPar->n_Ind_StructControl, 0)) {
            double* p = static_cast<double*>(std::malloc(
                static_cast<size_t>(N_OL_StCs) * ol_rows * sizeof(double)));
            CntrPar->OL_StructControl = p;
            CntrPar->n_OL_StructControl_rows = static_cast<int32_t>(N_OL_StCs);
            CntrPar->n_OL_StructControl_cols = ol_rows;
            int I_OL = 1;
            for (int32_t I = 1; I <= CntrPar->n_Ind_StructControl; ++I) {
                if (CntrPar->Ind_StructControl[I - 1] > 0) {
                    const double* src = column(CntrPar->Ind_StructControl[I - 1]);
                    for (int32_t k = 1; k <= ol_rows; ++k)
                        p[static_cast<size_t>(k - 1) * N_OL_StCs + (I_OL - 1)] =
                            src[k - 1];
                    I_OL = I_OL + 1;
                }
            }
        }
    }

    //------------------- HOUSEKEEPING -----------------------
    // CntrPar%PerfFileName = TRIM(CntrPar%PerfFileName)
    //
    // A NO-OP, and transcribed as one rather than deleted. The target is
    // CHARACTER(1024): dropping the trailing blanks and then blank-filling the
    // full width back reproduces the value byte for byte. It is not removed
    // because P7's oracle is the source, and a reader comparing the two files
    // should find the statement accounted for rather than missing.

    // ! Add RoutineName to error message
    if (ErrVar->aviFAIL < 0) {
        // ErrVar%ErrMsg = RoutineName//':'//TRIM(ErrVar%ErrMsg)
        std::string msg(RoutineName);
        msg += ':';
        msg += errmsg_trim(ErrVar);
        assign_errmsg(ErrVar, msg);
    }
}
