// Auto-generated C struct for Fortran TYPE(resParams)
// Generated by VIT (Verified Incremental Translator)

#ifndef RESPARAMS_T_H
#define RESPARAMS_T_H

typedef struct {
    double res_OutputSignalLast1[1024];
    double res_OutputSignalLast2[1024];
    double res_InputSignalLast1[1024];
    double res_InputSignalLast2[1024];
} resparams_t;

#endif // RESPARAMS_T_H
