// C++ implementation of Fortran function: ColemanTransformInverse
// Generated by VIT (Verified Incremental Translator)
// After verification: ColemanTransformInverse kernel PASSED

// --- User-provided C++ implementation ---
// VIT Translation Scaffold
// Function: ColemanTransformInverse
// Source: Functions.f90
// Module: Functions
// Fortran: SUBROUTINE ColemanTransformInverse(axTIn, axYIn, aziAngle, nHarmonic, aziOffset, PitComIPC)
// Source MD5: ec4d363951a9
// VIT: 0.1.0
// Status: unverified
// Generated: 2026-03-18T13:43:50Z

#include <cmath>
#include "rosco_constants.h"

void ColemanTransformInverse(double axTIn, double axYIn, double aziAngle, int nHarmonic, double aziOffset, double* PitComIPC) {
    const double phi2 = 2.0 / 3.0 * PI;
    const double phi3 = 4.0 / 3.0 * PI;

    PitComIPC[0] = cos(nHarmonic * (aziAngle + aziOffset)) * axTIn
                 + sin(nHarmonic * (aziAngle + aziOffset)) * axYIn;
    PitComIPC[1] = cos(nHarmonic * (aziAngle + aziOffset + phi2)) * axTIn
                 + sin(nHarmonic * (aziAngle + aziOffset + phi2)) * axYIn;
    PitComIPC[2] = cos(nHarmonic * (aziAngle + aziOffset + phi3)) * axTIn
                 + sin(nHarmonic * (aziAngle + aziOffset + phi3)) * axYIn;
}

// --- Fortran-callable C wrapper ---
extern "C" {
    void colemantransforminverse_c(double axTIn, double axYIn, double aziAngle, int nHarmonic, double aziOffset, double* PitComIPC) {
        ColemanTransformInverse(axTIn, axYIn, aziAngle, nHarmonic, aziOffset, PitComIPC);
    }
}
