// C++ implementation of Fortran function: ColemanTransform
// Generated by VIT (Verified Incremental Translator)
// After verification: ColemanTransform kernel PASSED

// --- User-provided C++ implementation ---
// VIT Translation Scaffold
// Function: ColemanTransform
// Source: Functions.f90
// Module: Functions
// Fortran: SUBROUTINE ColemanTransform(rootMOOP, aziAngle, nHarmonic, axTOut, axYOut)
// Source MD5: 2c870c3258ec
// VIT: 0.1.0
// Status: unverified
// Generated: 2026-03-18T13:43:44Z

#include <cmath>
#include "rosco_constants.h"

void ColemanTransform(double* rootMOOP, double aziAngle, int nHarmonic, double* axTOut, double* axYOut) {
    const double phi2 = 2.0 / 3.0 * PI;
    const double phi3 = 4.0 / 3.0 * PI;

    *axTOut = 2.0 / 3.0 * (cos(nHarmonic * aziAngle) * rootMOOP[0]
            + cos(nHarmonic * (aziAngle + phi2)) * rootMOOP[1]
            + cos(nHarmonic * (aziAngle + phi3)) * rootMOOP[2]);
    *axYOut = 2.0 / 3.0 * (sin(nHarmonic * aziAngle) * rootMOOP[0]
            + sin(nHarmonic * (aziAngle + phi2)) * rootMOOP[1]
            + sin(nHarmonic * (aziAngle + phi3)) * rootMOOP[2]);
}

// --- Fortran-callable C wrapper ---
extern "C" {
    void colemantransform_c(double* rootMOOP, double aziAngle, int nHarmonic, double* axTOut, double* axYOut) {
        ColemanTransform(rootMOOP, aziAngle, nHarmonic, axTOut, axYOut);
    }
}
