// C++ implementation of Fortran function: Debug
// Generated by VIT (Verified Incremental Translator)
// Integrated by `vit integrate`. What verified this function,
// and how strongly, is recorded in the campaign's evidence for
// Debug -- not here: integration does not verify anything.

#include "vit_types.h"
#include "vit_translated.h"

// --- User-provided C++ implementation ---
// VIT Translation Scaffold
// Function: Debug
// Source: ROSCO_IO.f90
// Module: ROSCO_IO
// Fortran: SUBROUTINE Debug(LocalVar, CntrPar, DebugVar, ErrVar, avrSWAP, RootName, size_avcOUTNAME)
// Reference built with: -fdefault-real-8 -fdefault-double-8 -ffp-contract=off
// Source MD5: 356dc75dd79c
// VIT: 0.1.0
// Status: unverified
// Generated: 2026-08-14T06:00:57Z
//
// ---------------------------------------------------------------------------
// CONTRACT. `plan.json` classifies this unit `respecify`: it performs external
// I/O on three files it opens and closes itself, so what it must reproduce is
// the BYTES of those files, not a set of returned values. Its C signature
// carries no output at all -- `ErrVar` is written only on `GetNewUnit`'s
// overflow arm (below), `avrSWAP` is INTENT(INOUT) and never assigned -- so a
// harness comparing the mapped signature would compare nothing. What compares
// this unit is the `.RO.dbg` file it writes; see evidence/Debug/.
//
// FORTRAN OUTPUT FORMATTING IS THE WHOLE UNIT. Every observable this unit has
// is a formatted record, so the edit descriptors below are transcribed rather
// than approximated:
//
//   Aw          right-justified, blank-filled on the LEFT; if the value is
//               WIDER than w, the LEFTMOST w characters (not the rightmost).
//   Fw.d        fixed point.
//   ESw.dEe     scientific, exactly one non-zero digit before the point,
//               exponent in exactly `e` digits.
//   TRn         tab RIGHT n columns. Positional only: it moves the write
//               position and emits nothing, so blanks appear only where a
//               later edit descriptor writes past them. A trailing TR5
//               therefore produces NO trailing blanks -- which is why the
//               reference's records are 670 bytes and not 675.
//   :           terminate format processing if no data item remains. It sits
//               AFTER the TR5 in `(99(a20,TR5:))`, so the last item's TR5 is
//               processed and then discarded by the rule above.
//
// GETNEWUNIT IS ABSORBED, AND THAT IS A RESPECIFICATION WITH A CONSEQUENCE.
// `plan.json` records `absorbs: [GetNewUnit]`. GetNewUnit exists to find a free
// Fortran I/O unit number between 10 and 1024 and to report failure when there
// is none. A C++ implementation opens a `FILE*`; the unit number does not
// exist, so neither does its exhaustion arm, and this unit's only write to
// `ErrVar` goes with it. That arm is unreachable in the reference here as well
// -- it needs 1014 simultaneously open units -- but the difference is real and
// is recorded rather than hidden. See evidence/Debug/README.md.
// ---------------------------------------------------------------------------

#include "vit_types.h"

#include <ISO_Fortran_binding.h>

#include <cmath>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

// THE PRODUCTION BRIDGE. `rosco/controller/src/vit_debug_bridges.f90`.
//
// `CurDate` and `CurTime` are declared PERMANENT BRIDGES for this unit in
// plan.json. They read the wall clock through `DATE_AND_TIME`, so they are not
// functions of this unit's arguments and cannot be verified against it; and
// X1 forbids reproducing a callee's body in its caller. They stay Fortran and
// are called through a BIND(C) shim, which is the same shape ExtController's
// `LoadDynamicLib` bridge already has.
//
// Each writes a fixed-width, blank-padded Fortran CHARACTER value: 11 bytes
// for 'dd-mmm-yyyy' and 8 for 'hh:mm:ss'. Neither is NUL-terminated.
extern "C" {
void vit_curdate_c(char* CurDate_result);   // CHARACTER(11)
void vit_curtime_c(char* CurTime_result);   // CHARACTER(8)
}

namespace {

// ---------------------------------------------------------------------------
// One output record under construction.
//
// `pos` is the Fortran write position; `buf` holds only what has actually been
// written. `tr()` advances the position without writing, and the gap is filled
// with blanks by the next `put()` -- never at end of record. That single rule
// is what makes a trailing `TRn` invisible, which the reference's own record
// length (670, not 675) confirms.
// ---------------------------------------------------------------------------
struct Rec {
    std::string buf;
    size_t pos = 0;

    void tr(size_t n) { pos += n; }

    void put(const char* s, size_t n) {
        if (pos > buf.size()) buf.append(pos - buf.size(), ' ');
        buf.append(s, n);
        pos = buf.size();
    }
    void put(const std::string& s) { put(s.data(), s.size()); }

    void write_to(std::FILE* f) const {
        std::fwrite(buf.data(), 1, buf.size(), f);
        std::fputc('\n', f);
    }
};

// ---------------------------------------------------------------------------
// A Fortran CHARACTER(W) value.
//
// The reference builds its column headings by assigning literals into
// `CHARACTER(15)` array elements, and five of the 185 literals are LONGER than
// 15 -- 'NacHeadingTarget' becomes 'NacHeadingTarge' in the shipped header.
// The truncation is therefore load-bearing, and it is written ONCE, here, so
// that the width has exactly one site. Restating it 185 times would leave 184
// of them unable to change any output.
// ---------------------------------------------------------------------------
template <int W>
struct FChar {
    char c[W];
    explicit FChar(const char* s) {
        size_t n = std::strlen(s);
        if (n > static_cast<size_t>(W)) n = W;          // silent truncation
        std::memcpy(c, s, n);
        std::memset(c + n, ' ', W - n);                 // blank fill
    }
};

// Fortran `Aw` applied to a CHARACTER(len) value.
void put_a(Rec& r, const char* s, int len, int w) {
    if (len >= w) {
        r.put(s, static_cast<size_t>(w));               // leftmost w characters
    } else {
        std::string pad(static_cast<size_t>(w - len), ' ');
        r.put(pad);
        r.put(s, static_cast<size_t>(len));
    }
}

template <int W>
void put_a(Rec& r, const FChar<W>& v, int w) { put_a(r, v.c, W, w); }

// Right-justify `text` in a field of `w`, or fill the field with '*' when it
// does not fit -- Fortran's overflow behaviour for every numeric descriptor.
std::string field(const std::string& text, int w) {
    if (static_cast<int>(text.size()) > w) {
        return std::string(static_cast<size_t>(w), '*');
    }
    return std::string(static_cast<size_t>(w) - text.size(), ' ') + text;
}

void put_field(Rec& r, const std::string& text, int w) { r.put(field(text, w)); }

// Fortran `Iw`.
void put_i(Rec& r, int v, int w) { put_field(r, std::to_string(v), w); }

// gfortran renders a non-finite value as a WORD, not as digits: "NaN" with no
// sign, and "Infinity" (or "Inf" in a field too narrow for it) carrying the
// sign. Returns false when the value is finite and the caller should format it.
bool nonfinite_text(double v, int w, std::string& out) {
    if (std::isnan(v)) { out = "NaN"; return true; }
    if (std::isinf(v)) {
        const char* sign = std::signbit(v) ? "-" : "";
        const int need = static_cast<int>(std::strlen(sign)) + 8;
        out = std::string(sign) + (w >= need ? "Infinity" : "Inf");
        return true;
    }
    return false;
}

// Fortran `Fw.d`.
//
// The optional-leading-zero rule -- gfortran drops the '0' in "0.5" when the
// value would not otherwise fit -- is NOT written. Every F descriptor in this
// unit is F20.5, and no double's fixed-point rendering at 5 decimals reaches
// 20 characters without already overflowing the field, so the branch has no
// reachable input. The proof lives here rather than in an unreachable arm.
void put_f(Rec& r, double v, int w, int d) {
    std::string text;
    if (!nonfinite_text(v, w, text)) {
        char tmp[512];
        std::snprintf(tmp, sizeof tmp, "%.*f", d, v);
        text = tmp;
    }
    put_field(r, text, w);
}

// Fortran `ESw.dEe`.
//
// C's `%.*E` is scientific with one non-zero digit before the point -- the same
// normalisation `ES` specifies -- and libgfortran's own float writer is built
// on the same snprintf conversion, so the rounding agrees by construction
// rather than by luck. What C does NOT guarantee is the exponent WIDTH: it
// emits at least two digits and as many more as the value needs, while `Ee`
// demands exactly `e` and fills the field with '*' when the exponent needs
// more.
void put_es(Rec& r, double v, int w, int d, int e) {
    std::string text;
    if (!nonfinite_text(v, w, text)) {
        char tmp[512];
        std::snprintf(tmp, sizeof tmp, "%.*E", d, v);
        std::string s(tmp);

        const size_t epos = s.find('E');
        std::string mant = s.substr(0, epos);
        const char esign = s[epos + 1];
        std::string edig = s.substr(epos + 2);
        while (edig.size() > 1 && edig[0] == '0') edig.erase(0, 1);

        if (static_cast<int>(edig.size()) > e) {
            put_field(r, std::string(static_cast<size_t>(w) + 1, '*'), w);
            return;
        }
        edig.insert(0, static_cast<size_t>(e) - edig.size(), '0');
        text = mant + "E" + esign + edig;
    }
    put_field(r, text, w);
}

// ---------------------------------------------------------------------------
// The SAVE locals.
//
//     INTEGER(IntKi), SAVE :: UnDb, UnDb2, UnDb3
//     INTEGER(IntKi), SAVE, DIMENSION(:), ALLOCATABLE :: avrIndices
//
// A Fortran SAVE local is a function-local static, and these are load-bearing:
// the unit opens on one call, writes on tens of thousands, and closes on the
// last. The unit NUMBERS become `FILE*` because GetNewUnit is absorbed.
//
// `avrIndices` stays a Fortran ALLOCATABLE, in a descriptor this file owns,
// because `AddToList` -- an already-translated callee -- reallocates it
// through `CFI_allocate`. Mirroring it as a `std::vector` would mean passing
// AddToList something other than the allocatable it takes, which is the
// inlining X1 forbids one step removed.
// ---------------------------------------------------------------------------
std::FILE* UnDb = nullptr;
std::FILE* UnDb2 = nullptr;
std::FILE* UnDb3 = nullptr;

CFI_CDESC_T(1) avrIndices_desc;
bool avrIndices_established = false;

CFI_cdesc_t* avrIndices() {
    if (!avrIndices_established) {
        CFI_establish(reinterpret_cast<CFI_cdesc_t*>(&avrIndices_desc), nullptr,
                      CFI_attribute_allocatable, CFI_type_int, sizeof(int), 1,
                      nullptr);
        avrIndices_established = true;
    }
    return reinterpret_cast<CFI_cdesc_t*>(&avrIndices_desc);
}

int avrIndices_size() {
    CFI_cdesc_t* d = avrIndices();
    return d->base_addr == nullptr ? 0 : static_cast<int>(d->dim[0].extent);
}

int avrIndices_at(int i) {   // 1-based, as the Fortran indexes it
    CFI_cdesc_t* d = avrIndices();
    CFI_index_t sub = d->dim[0].lower_bound + (i - 1);
    return *static_cast<int*>(CFI_address(d, &sub));
}

// TRIM(RootName)//suffix. RootName is a CHARACTER(size_avcOUTNAME) dummy: a
// fixed-width, blank-padded buffer, NOT NUL-terminated. TRIM removes TRAILING
// BLANKS and nothing else.
std::string trimmed_name(const char* RootName, int len, const char* suffix) {
    int n = len;
    while (n > 0 && RootName[n - 1] == ' ') --n;
    return std::string(RootName, static_cast<size_t>(n)) + suffix;
}

// 'Generated on '//CurDate()//' at '//CurTime()//' using ROSCO-'//TRIM(rosco_version)
//
// WRITE(u, *) of a single character expression: gfortran's list-directed output
// prefixes the record with one blank and writes the value with no quoting. The
// reference's own header line is 56 bytes -- 1 + 13 + 11 + 4 + 8 + 13 + 6.
void write_generated_on(std::FILE* f) {
    char date[11];
    char time[8];
    vit_curdate_c(date);
    vit_curtime_c(time);

    Rec r;
    r.put(" Generated on ", 14);
    r.put(date, 11);
    r.put(" at ", 4);
    r.put(time, 8);
    r.put(" using ROSCO-", 13);
    r.put("2.10.1", 6);          // TRIM(rosco_version), ROSCO_Types.f90:10
    r.write_to(f);
}

// Constants.f90:21-22, copied as the truncated decimal literals the reference
// declares rather than recomputed from mathematics.
const double RPS2RPM = 9.5492966;
const double R2D     = 57.2957795130;

}  // namespace

void Debug(localvariables_view_t* LocalVar, controlparameters_view_t* CntrPar,
           debugvariables_t* DebugVar, errorvariables_view_t* ErrVar,
           float* avrSWAP, char* RootName, int size_avcOUTNAME) {
    (void)ErrVar;   // see the GetNewUnit note in the file header

    // nDebugOuts = 26 ; Allocate(DebugOutData(nDebugOuts)) ...
    const int nDebugOuts = 26;
    std::vector<double> DebugOutData(static_cast<size_t>(nDebugOuts));
    DebugOutData[0]  = DebugVar->WE_Cp;
    DebugOutData[1]  = DebugVar->WE_b;
    DebugOutData[2]  = DebugVar->WE_w;
    DebugOutData[3]  = DebugVar->WE_t;
    DebugOutData[4]  = DebugVar->WE_Vm;
    DebugOutData[5]  = DebugVar->WE_Vt;
    DebugOutData[6]  = DebugVar->WE_Vw;
    DebugOutData[7]  = DebugVar->WE_lambda;
    DebugOutData[8]  = DebugVar->PC_PICommand;
    DebugOutData[9]  = DebugVar->GenSpeedF;
    DebugOutData[10] = DebugVar->RotSpeedF;
    DebugOutData[11] = DebugVar->NacIMU_FA_AccF;
    DebugOutData[12] = DebugVar->FA_AccF;
    DebugOutData[13] = DebugVar->Fl_PitCom;
    DebugOutData[14] = DebugVar->PC_MinPit;
    DebugOutData[15] = DebugVar->axisTilt_1P;
    DebugOutData[16] = DebugVar->axisYaw_1P;
    DebugOutData[17] = DebugVar->axisTilt_2P;
    DebugOutData[18] = DebugVar->axisYaw_2P;
    DebugOutData[19] = DebugVar->YawRateCom;
    DebugOutData[20] = DebugVar->NacHeadingTarget;
    DebugOutData[21] = DebugVar->NacVaneOffset;
    DebugOutData[22] = DebugVar->Yaw_Err;
    DebugOutData[23] = DebugVar->YawState;
    DebugOutData[24] = DebugVar->VS_RefSpd;
    DebugOutData[25] = DebugVar->PC_RefSpd;

    // DebugOutStrings = [CHARACTER(15) :: ...]
    static const char* const DebugOutStrings_src[26] = {
        "WE_Cp", "WE_b", "WE_w", "WE_t", "WE_Vm",
        "WE_Vt", "WE_Vw", "WE_lambda", "PC_PICommand", "GenSpeedF",
        "RotSpeedF", "NacIMU_FA_AccF", "FA_AccF", "Fl_PitCom", "PC_MinPit",
        "axisTilt_1P", "axisYaw_1P", "axisTilt_2P", "axisYaw_2P", "YawRateCom",
        "NacHeadingTarget", "NacVaneOffset", "Yaw_Err", "YawState", "VS_RefSpd",
        "PC_RefSpd"};
    static const char* const DebugOutUnits_src[26] = {
        "[-]", "[-]", "[-]", "[-]", "[m/s]",
        "[m/s]", "[m/s]", "[rad]", "[rad]", "[rad/s]",
        "[rad/s]", "[rad/s]", "[m/s]", "[rad]", "[rad]",
        "[N/A]", "[N/A]", "[N/A]", "[N/A]", "[rad/s]",
        "[deg]", "[deg]", "[deg]", "[N/A]", "[rad/s]",
        "[rad/s]"};

    // nLocalVars = 159 ; Allocate(LocalVarOutData(nLocalVars))
    const int nLocalVars = 159;
    std::vector<double> LocalVarOutData(static_cast<size_t>(nLocalVars));
    LocalVarOutData[0]   = LocalVar->iStatus;
    LocalVarOutData[1]   = LocalVar->AlreadyInitialized;
    LocalVarOutData[2]   = LocalVar->RestartWSE;
    LocalVarOutData[3]   = LocalVar->Time;
    LocalVarOutData[4]   = LocalVar->DT;
    LocalVarOutData[5]   = LocalVar->n_DT;
    LocalVarOutData[6]   = LocalVar->Time_Last;
    LocalVarOutData[7]   = LocalVar->VS_GenPwr;
    LocalVarOutData[8]   = LocalVar->GenSpeed;
    LocalVarOutData[9]   = LocalVar->RotSpeed;
    LocalVarOutData[10]  = LocalVar->NacHeading;
    LocalVarOutData[11]  = LocalVar->NacVane;
    LocalVarOutData[12]  = LocalVar->NacVaneF;
    LocalVarOutData[13]  = LocalVar->WindDir;
    LocalVarOutData[14]  = LocalVar->HorWindV;
    LocalVarOutData[15]  = LocalVar->HorWindV_F;
    LocalVarOutData[16]  = LocalVar->rootMOOP[0];
    LocalVarOutData[17]  = LocalVar->rootMOOPF[0];
    LocalVarOutData[18]  = LocalVar->BlPitch[0];
    LocalVarOutData[19]  = LocalVar->BlPitchCMeas;
    LocalVarOutData[20]  = LocalVar->Azimuth;
    LocalVarOutData[21]  = LocalVar->OL_Azimuth;
    LocalVarOutData[22]  = LocalVar->AzUnwrapped;
    LocalVarOutData[23]  = LocalVar->AzError;
    LocalVarOutData[24]  = LocalVar->GenTqAz;
    LocalVarOutData[25]  = LocalVar->AzBuffer[0];
    LocalVarOutData[26]  = LocalVar->NumBl;
    LocalVarOutData[27]  = LocalVar->FA_Acc_TT;
    LocalVarOutData[28]  = LocalVar->SS_Acc_TT;
    LocalVarOutData[29]  = LocalVar->FA_Acc_Nac;
    LocalVarOutData[30]  = LocalVar->NacIMU_FA_RAcc;
    LocalVarOutData[31]  = LocalVar->FA_AccHPF;
    LocalVarOutData[32]  = LocalVar->FA_AccHPFI;
    LocalVarOutData[33]  = LocalVar->FA_PitCom[0];
    LocalVarOutData[34]  = LocalVar->VS_RefSpd;
    LocalVarOutData[35]  = LocalVar->VS_RefSpd_TSR;
    LocalVarOutData[36]  = LocalVar->VS_RefSpd_TRA;
    LocalVarOutData[37]  = LocalVar->VS_RefSpd_RL;
    LocalVarOutData[38]  = LocalVar->PC_RefSpd;
    LocalVarOutData[39]  = LocalVar->PC_RefSpd_SS;
    LocalVarOutData[40]  = LocalVar->PC_RefSpd_PRC;
    LocalVarOutData[41]  = LocalVar->RotSpeedF;
    LocalVarOutData[42]  = LocalVar->GenSpeedF;
    LocalVarOutData[43]  = LocalVar->GenTq;
    LocalVarOutData[44]  = LocalVar->GenTqMeas;
    LocalVarOutData[45]  = LocalVar->GenArTq;
    LocalVarOutData[46]  = LocalVar->GenBrTq;
    LocalVarOutData[47]  = LocalVar->VS_KOmega2_GenTq;
    LocalVarOutData[48]  = LocalVar->VS_ConstPwr_GenTq;
    LocalVarOutData[49]  = LocalVar->IPC_PitComF[0];
    LocalVarOutData[50]  = LocalVar->PC_KP;
    LocalVarOutData[51]  = LocalVar->PC_KI;
    LocalVarOutData[52]  = LocalVar->PC_KD;
    LocalVarOutData[53]  = LocalVar->PC_TF;
    LocalVarOutData[54]  = LocalVar->PC_MaxPit;
    LocalVarOutData[55]  = LocalVar->PC_MinPit;
    LocalVarOutData[56]  = LocalVar->PC_PitComT;
    LocalVarOutData[57]  = LocalVar->PC_PitComT_Last;
    LocalVarOutData[58]  = LocalVar->BlPitchCMeasF;
    LocalVarOutData[59]  = LocalVar->PC_PitComT_IPC[0];
    LocalVarOutData[60]  = LocalVar->PC_PwrErr;
    LocalVarOutData[61]  = LocalVar->PC_SpdErr;
    LocalVarOutData[62]  = LocalVar->IPC_AxisTilt_1P;
    LocalVarOutData[63]  = LocalVar->IPC_AxisYaw_1P;
    LocalVarOutData[64]  = LocalVar->IPC_AxisTilt_2P;
    LocalVarOutData[65]  = LocalVar->IPC_AxisYaw_2P;
    LocalVarOutData[66]  = LocalVar->axisTilt_1P;
    LocalVarOutData[67]  = LocalVar->axisYaw_1P;
    LocalVarOutData[68]  = LocalVar->axisYawF_1P;
    LocalVarOutData[69]  = LocalVar->axisTilt_2P;
    LocalVarOutData[70]  = LocalVar->axisYaw_2P;
    LocalVarOutData[71]  = LocalVar->axisYawF_2P;
    LocalVarOutData[72]  = LocalVar->IPC_KI[0];
    LocalVarOutData[73]  = LocalVar->IPC_KP[0];
    LocalVarOutData[74]  = LocalVar->IPC_IntSat;
    LocalVarOutData[75]  = LocalVar->PC_State;
    LocalVarOutData[76]  = LocalVar->PitCom[0];
    LocalVarOutData[77]  = LocalVar->PitCom_SD[0];
    LocalVarOutData[78]  = LocalVar->PitComAct[0];
    LocalVarOutData[79]  = LocalVar->SS_DelOmegaF;
    LocalVarOutData[80]  = LocalVar->TestType;
    LocalVarOutData[81]  = LocalVar->Kp_Float;
    LocalVarOutData[82]  = LocalVar->VS_MaxTq;
    LocalVarOutData[83]  = LocalVar->VS_LastGenTrq;
    LocalVarOutData[84]  = LocalVar->VS_LastGenPwr;
    LocalVarOutData[85]  = LocalVar->VS_MechGenPwr;
    LocalVarOutData[86]  = LocalVar->VS_SpdErrAr;
    LocalVarOutData[87]  = LocalVar->VS_SpdErrBr;
    LocalVarOutData[88]  = LocalVar->VS_SpdErr;
    LocalVarOutData[89]  = LocalVar->VS_State;
    LocalVarOutData[90]  = LocalVar->VS_Rgn3Pitch;
    LocalVarOutData[91]  = LocalVar->WE_Vw;
    LocalVarOutData[92]  = LocalVar->WE_Vw_F;
    LocalVarOutData[93]  = LocalVar->WE_VwI;
    LocalVarOutData[94]  = LocalVar->WE_VwIdot;
    LocalVarOutData[95]  = LocalVar->WE_Op;
    LocalVarOutData[96]  = LocalVar->WE_Op_Last;
    LocalVarOutData[97]  = LocalVar->VS_LastGenTrqF;
    LocalVarOutData[98]  = LocalVar->PRC_WSE_F;
    LocalVarOutData[99]  = LocalVar->PRC_R_Speed;
    LocalVarOutData[100] = LocalVar->PRC_R_Torque;
    LocalVarOutData[101] = LocalVar->PRC_R_Pitch;
    LocalVarOutData[102] = LocalVar->PRC_R_Total;
    LocalVarOutData[103] = LocalVar->PRC_Min_Pitch;
    LocalVarOutData[104] = LocalVar->PS_Min_Pitch;
    LocalVarOutData[105] = LocalVar->OL_Index;
    LocalVarOutData[106] = LocalVar->SU_Stage;
    LocalVarOutData[107] = LocalVar->SU_LoadStageStartTime;
    LocalVarOutData[108] = LocalVar->SU_RotSpeedF;
    LocalVarOutData[109] = LocalVar->SD_Trigger;
    LocalVarOutData[110] = LocalVar->SD_BlPitchF;
    LocalVarOutData[111] = LocalVar->SD_NacVaneF;
    LocalVarOutData[112] = LocalVar->SD_GenSpeedF;
    LocalVarOutData[113] = LocalVar->SD_Stage;
    LocalVarOutData[114] = LocalVar->SD_StageStartTime;
    LocalVarOutData[115] = LocalVar->SD_MaxPitchRate;
    LocalVarOutData[116] = LocalVar->SD_MaxTorqueRate;
    LocalVarOutData[117] = LocalVar->GenTq_SD;
    LocalVarOutData[118] = LocalVar->Fl_PitCom;
    LocalVarOutData[119] = LocalVar->NACIMU_FA_AccF;
    LocalVarOutData[120] = LocalVar->FA_AccF;
    LocalVarOutData[121] = LocalVar->FA_Hist;
    LocalVarOutData[122] = LocalVar->TRA_LastRefSpd;
    LocalVarOutData[123] = LocalVar->VS_RefSpeed;
    LocalVarOutData[124] = LocalVar->PtfmTDX;
    LocalVarOutData[125] = LocalVar->PtfmTDY;
    LocalVarOutData[126] = LocalVar->PtfmTDZ;
    LocalVarOutData[127] = LocalVar->PtfmRDX;
    LocalVarOutData[128] = LocalVar->PtfmRDY;
    LocalVarOutData[129] = LocalVar->PtfmRDZ;
    LocalVarOutData[130] = LocalVar->PtfmTVX;
    LocalVarOutData[131] = LocalVar->PtfmTVY;
    LocalVarOutData[132] = LocalVar->PtfmTVZ;
    LocalVarOutData[133] = LocalVar->PtfmRVX;
    LocalVarOutData[134] = LocalVar->PtfmRVY;
    LocalVarOutData[135] = LocalVar->PtfmRVZ;
    LocalVarOutData[136] = LocalVar->PtfmTAX;
    LocalVarOutData[137] = LocalVar->PtfmTAY;
    LocalVarOutData[138] = LocalVar->PtfmTAZ;
    LocalVarOutData[139] = LocalVar->PtfmRAX;
    LocalVarOutData[140] = LocalVar->PtfmRAY;
    LocalVarOutData[141] = LocalVar->PtfmRAZ;
    LocalVarOutData[142] = LocalVar->CC_DesiredL[0];
    LocalVarOutData[143] = LocalVar->CC_ActuatedL[0];
    LocalVarOutData[144] = LocalVar->CC_ActuatedDL[0];
    LocalVarOutData[145] = LocalVar->StC_Input[0];
    LocalVarOutData[146] = LocalVar->Flp_Angle[0];
    LocalVarOutData[147] = LocalVar->RootMyb_Last[0];
    LocalVarOutData[148] = LocalVar->ACC_INFILE_SIZE;
    // LocalVarOutData(150) = LocalVar%AWC_complexangle(1)
    //
    // A COMPLEX value assigned to a REAL takes the REAL PART and discards the
    // imaginary one. The declaration is two screens from the assignment and
    // nothing in the statement says it is complex.
    LocalVarOutData[149] = LocalVar->AWC_complexangle[0].re;
    LocalVarOutData[150] = LocalVar->TiltMean;
    LocalVarOutData[151] = LocalVar->YawMean;
    LocalVarOutData[152] = LocalVar->ZMQ_ID;
    LocalVarOutData[153] = LocalVar->ZMQ_YawOffset;
    LocalVarOutData[154] = LocalVar->ZMQ_TorqueOffset;
    LocalVarOutData[155] = LocalVar->ZMQ_PitOffset[0];
    LocalVarOutData[156] = LocalVar->ZMQ_R_Speed;
    LocalVarOutData[157] = LocalVar->ZMQ_R_Torque;
    LocalVarOutData[158] = LocalVar->ZMQ_R_Pitch;

    static const char* const LocalVarOutStrings_src[159] = {
        "iStatus", "AlreadyInitialized", "RestartWSE", "Time", "DT",
        "n_DT", "Time_Last", "VS_GenPwr", "GenSpeed", "RotSpeed",
        "NacHeading", "NacVane", "NacVaneF", "WindDir", "HorWindV",
        "HorWindV_F", "rootMOOP", "rootMOOPF", "BlPitch", "BlPitchCMeas",
        "Azimuth", "OL_Azimuth", "AzUnwrapped", "AzError", "GenTqAz",
        "AzBuffer", "NumBl", "FA_Acc_TT", "SS_Acc_TT", "FA_Acc_Nac",
        "NacIMU_FA_RAcc", "FA_AccHPF", "FA_AccHPFI", "FA_PitCom", "VS_RefSpd",
        "VS_RefSpd_TSR", "VS_RefSpd_TRA", "VS_RefSpd_RL", "PC_RefSpd", "PC_RefSpd_SS",
        "PC_RefSpd_PRC", "RotSpeedF", "GenSpeedF", "GenTq", "GenTqMeas",
        "GenArTq", "GenBrTq", "VS_KOmega2_GenTq", "VS_ConstPwr_GenTq", "IPC_PitComF",
        "PC_KP", "PC_KI", "PC_KD", "PC_TF", "PC_MaxPit",
        "PC_MinPit", "PC_PitComT", "PC_PitComT_Last", "BlPitchCMeasF", "PC_PitComT_IPC",
        "PC_PwrErr", "PC_SpdErr", "IPC_AxisTilt_1P", "IPC_AxisYaw_1P", "IPC_AxisTilt_2P",
        "IPC_AxisYaw_2P", "axisTilt_1P", "axisYaw_1P", "axisYawF_1P", "axisTilt_2P",
        "axisYaw_2P", "axisYawF_2P", "IPC_KI", "IPC_KP", "IPC_IntSat",
        "PC_State", "PitCom", "PitCom_SD", "PitComAct", "SS_DelOmegaF",
        "TestType", "Kp_Float", "VS_MaxTq", "VS_LastGenTrq", "VS_LastGenPwr",
        "VS_MechGenPwr", "VS_SpdErrAr", "VS_SpdErrBr", "VS_SpdErr", "VS_State",
        "VS_Rgn3Pitch", "WE_Vw", "WE_Vw_F", "WE_VwI", "WE_VwIdot",
        "WE_Op", "WE_Op_Last", "VS_LastGenTrqF", "PRC_WSE_F", "PRC_R_Speed",
        "PRC_R_Torque", "PRC_R_Pitch", "PRC_R_Total", "PRC_Min_Pitch", "PS_Min_Pitch",
        "OL_Index", "SU_Stage", "SU_LoadStageStartTime", "SU_RotSpeedF", "SD_Trigger",
        "SD_BlPitchF", "SD_NacVaneF", "SD_GenSpeedF", "SD_Stage", "SD_StageStartTime",
        "SD_MaxPitchRate", "SD_MaxTorqueRate", "GenTq_SD", "Fl_PitCom", "NACIMU_FA_AccF",
        "FA_AccF", "FA_Hist", "TRA_LastRefSpd", "VS_RefSpeed", "PtfmTDX",
        "PtfmTDY", "PtfmTDZ", "PtfmRDX", "PtfmRDY", "PtfmRDZ",
        "PtfmTVX", "PtfmTVY", "PtfmTVZ", "PtfmRVX", "PtfmRVY",
        "PtfmRVZ", "PtfmTAX", "PtfmTAY", "PtfmTAZ", "PtfmRAX",
        "PtfmRAY", "PtfmRAZ", "CC_DesiredL", "CC_ActuatedL", "CC_ActuatedDL",
        "StC_Input", "Flp_Angle", "RootMyb_Last", "ACC_INFILE_SIZE", "AWC_complexangle",
        "TiltMean", "YawMean", "ZMQ_ID", "ZMQ_YawOffset", "ZMQ_TorqueOffset",
        "ZMQ_PitOffset", "ZMQ_R_Speed", "ZMQ_R_Torque", "ZMQ_R_Pitch"};

    // ! Initialize debug file
    // IF ((LocalVar%iStatus == 0) .OR. (LocalVar%iStatus == -9)) THEN
    if ((LocalVar->iStatus == 0) || (LocalVar->iStatus == -9)) {
        if (CntrPar->LoggingLevel > 0) {
            // CALL GetNewUnit(UnDb, ErrVar)
            // OPEN(unit=UnDb, FILE=TRIM(RootName)//'.RO.dbg')
            //
            // A previously opened UnDb is deliberately NOT closed here: the
            // reference calls GetNewUnit again, which hands back a DIFFERENT
            // unit number and leaves the first connected. Scenario 1 does this
            // -- two initialisations, one close -- and the first file is
            // flushed at process exit by libgfortran there and by stdio here.
            UnDb = std::fopen(trimmed_name(RootName, size_avcOUTNAME, ".RO.dbg").c_str(), "w");
            if (UnDb) {
                write_generated_on(UnDb);

                // WRITE(UnDb, '(99(a20,TR5:))') 'Time', DebugOutStrings
                Rec r1;
                put_a(r1, "Time", 4, 20);
                r1.tr(5);
                for (int i = 0; i < nDebugOuts; ++i) {
                    put_a(r1, FChar<15>(DebugOutStrings_src[i]), 20);
                    r1.tr(5);
                }
                r1.write_to(UnDb);

                // WRITE(UnDb, '(99(a20,TR5:))') '(sec)', DebugOutUnits
                Rec r2;
                put_a(r2, "(sec)", 5, 20);
                r2.tr(5);
                for (int i = 0; i < nDebugOuts; ++i) {
                    put_a(r2, FChar<15>(DebugOutUnits_src[i]), 20);
                    r2.tr(5);
                }
                r2.write_to(UnDb);
            }
        }

        if (CntrPar->LoggingLevel > 1) {
            UnDb2 = std::fopen(trimmed_name(RootName, size_avcOUTNAME, ".RO.dbg2").c_str(), "w");
            if (UnDb2) {
                write_generated_on(UnDb2);

                // WRITE(UnDb2, '(160(a20,TR5:))') 'Time', LocalVarOutStrings
                Rec r1;
                put_a(r1, "Time", 4, 20);
                r1.tr(5);
                for (int i = 0; i < nLocalVars; ++i) {
                    put_a(r1, FChar<15>(LocalVarOutStrings_src[i]), 20);
                    r1.tr(5);
                }
                r1.write_to(UnDb2);

                // WRITE(UnDb2, '(160(a20,TR5:))')
                //
                // No output items at all: format processing stops at the first
                // descriptor that needs one, and an EMPTY RECORD is written.
                Rec r2;
                r2.write_to(UnDb2);
            }
        }

        if (CntrPar->LoggingLevel > 2) {
            // Allocate(avrIndices(avrBaseLength)) ; DO Ind = 1, avrBaseLength
            //
            // `INTEGER(IntKi) :: avrBaseLength = 85` -- a declaration with an
            // initialiser, which makes it implicitly SAVE in Fortran. It is
            // never assigned, so the save has no observable effect and it is
            // written as a constant.
            const int avrBaseLength = 85;
            CFI_cdesc_t* idx = avrIndices();
            if (idx->base_addr != nullptr) CFI_deallocate(idx);
            {
                CFI_index_t lower = 1, upper = avrBaseLength;
                CFI_allocate(idx, &lower, &upper, 0);
            }
            for (int Ind = 1; Ind <= avrBaseLength; ++Ind) {
                CFI_index_t sub = Ind;
                *static_cast<int*>(CFI_address(idx, &sub)) = Ind;
            }

            // ! Cable control indices
            if (CntrPar->CC_Mode > 0) {
                for (int Ind = 1; Ind <= CntrPar->n_CC_GroupIndex; ++Ind) {
                    addtolist_c(avrIndices(), CntrPar->CC_GroupIndex[Ind - 1]);
                    addtolist_c(avrIndices(), CntrPar->CC_GroupIndex[Ind - 1] + 1);
                }
            }

            // ! Structural control indices
            if (CntrPar->StC_Mode > 0) {
                for (int Ind = 1; Ind <= CntrPar->n_StC_GroupIndex; ++Ind) {
                    addtolist_c(avrIndices(), CntrPar->StC_GroupIndex[Ind - 1]);
                }
            }

            // avrFmt = '(A21,'//TRIM(Int2LStr(SIZE(avrIndices)))//'(TR12,"AvrSWAP(",I4,")"))'
            //
            // INT2LSTR IS NOT CALLED HERE, AND THAT IS NOT AN INLINING.
            //
            // The reference builds a FORMAT STRING at run time, and Int2LStr's
            // only job in it is to render the group's repeat count as decimal
            // text so the Fortran format parser can read it back as an integer.
            // A C++ implementation writes the records with a loop, so the
            // repeat count never leaves the integer domain and the
            // integer -> text -> integer round trip has nothing to do. X1
            // forbids reproducing a callee's BODY in its caller; no part of
            // Int2LStr's body appears anywhere in this file. What is dropped is
            // the round trip, not the callee's work.
            //
            // It is unobservable by construction: TRIM(Int2LStr(n)) is the
            // decimal representation of n for every n a 4-byte int can hold
            // (Int2LStr's own I11 field is exactly wide enough for INT_MIN), so
            // the parsed repeat count is n whatever this call returns.
            //
            // Recorded against plan.json's `depends_on: [AddToList, Int2LStr]`:
            // after respecification this unit depends on AddToList only.

            UnDb3 = std::fopen(trimmed_name(RootName, size_avcOUTNAME, ".RO.dbg3").c_str(), "w");
            if (UnDb3) {
                // WRITE(UnDb3,'(/////)')
                //
                // Five record terminators, then the record the write statement
                // itself ends: six empty records.
                for (int i = 0; i < 6; ++i) std::fputc('\n', UnDb3);

                // WRITE(UnDb3,avrFmt) 'LocalVar%Time ', (avrIndices)
                Rec r1;
                put_a(r1, "LocalVar%Time ", 14, 21);
                for (int i = 1; i <= avrIndices_size(); ++i) {
                    r1.tr(12);
                    r1.put("AvrSWAP(", 8);
                    put_i(r1, avrIndices_at(i), 4);
                    r1.put(")", 1);
                }
                r1.write_to(UnDb3);

                // WRITE(UnDb3,'(A21,'//TRIM(Int2LStr(SIZE(avrIndices)))//'(TR22,"(-)"))') '(s)'
                //
                // The group holds NO data edit descriptor -- only a TR and a
                // character-string descriptor -- so format control does not
                // stop when the one data item ('(s)') is consumed by the A21.
                // Positional and character-string descriptors are processed
                // unconditionally, so the group runs its full repeat count and
                // '(-)' is written SIZE(avrIndices) times.
                Rec r2;
                put_a(r2, "(s)", 3, 21);
                for (int i = 1; i <= avrIndices_size(); ++i) {
                    r2.tr(22);
                    r2.put("(-)", 3);
                }
                r2.write_to(UnDb3);
            }
        }
    }

    // ! Print simulation status, every 10 seconds
    // IF (MODULO(LocalVar%Time, 10.0_DbKi) == 0) THEN
    //
    // MODULO(a,p) for REALs is fmod(a,p) adjusted by p when the signs of a and
    // p differ. `LocalVar%Time` is a simulation clock and p is the positive
    // literal 10, so the adjustment arm is unreachable; the fmod is what
    // decides the branch and it is written as such.
    if (std::fmod(LocalVar->Time, 10.0) == 0.0) {
        // 100 FORMAT('Generator speed: ', f6.1, ' RPM, Pitch angle: ', f5.1,
        //            ' deg, Power: ', f7.1, ' kW, Est. wind Speed: ', f5.1, ' m/s')
        //
        // Built through the same record machinery as the files rather than
        // through printf: the widths are narrow (F5.1 holds -99.9 and no more),
        // so the asterisk-fill arm is reachable here in a way it is not for the
        // F20.5 columns, and printf would print MORE characters instead.
        Rec r;
        r.put("Generator speed: ", 17);
        put_f(r, LocalVar->GenSpeedF * RPS2RPM, 6, 1);
        r.put(" RPM, Pitch angle: ", 19);
        put_f(r, LocalVar->BlPitch[0] * R2D, 5, 1);
        r.put(" deg, Power: ", 13);
        put_f(r, static_cast<double>(avrSWAP[14]) / 1000.0, 7, 1);
        r.put(" kW, Est. wind Speed: ", 22);
        put_f(r, LocalVar->WE_Vw, 5, 1);
        r.put(" m/s", 4);
        r.write_to(stdout);
    }

    // ! Process DebugOutData, LocalVarOutData
    // ! Remove very small numbers that cause ******** outputs
    for (int I = 0; I < nDebugOuts; ++I) {
        if (std::fabs(DebugOutData[I]) < 1E-99) DebugOutData[I] = 0;
        if (std::fabs(DebugOutData[I]) > 1E+99) DebugOutData[I] = 1E+99;
    }
    for (int I = 0; I < nLocalVars; ++I) {
        if (std::fabs(LocalVarOutData[I]) < 1E-99) LocalVarOutData[I] = 0;
        if (std::fabs(LocalVarOutData[I]) > 1E+99) LocalVarOutData[I] = 1E+99;
    }

    // ! Write debug files
    // FmtDat = "(F20.5,TR5,159(ES20.5E2,TR5:))"
    if (LocalVar->n_DT % CntrPar->n_DT_Out == 0) {
        if ((CntrPar->LoggingLevel > 0) && (LocalVar->iStatus >= 0) && UnDb) {
            Rec r;
            put_f(r, LocalVar->Time, 20, 5);
            r.tr(5);
            for (int i = 0; i < nDebugOuts; ++i) {
                put_es(r, DebugOutData[i], 20, 5, 2);
                r.tr(5);
            }
            r.write_to(UnDb);
        }

        if ((CntrPar->LoggingLevel > 1) && (LocalVar->iStatus >= 0) && UnDb2) {
            Rec r;
            put_f(r, LocalVar->Time, 20, 5);
            r.tr(5);
            for (int i = 0; i < nLocalVars; ++i) {
                put_es(r, LocalVarOutData[i], 20, 5, 2);
                r.tr(5);
            }
            r.write_to(UnDb2);
        }

        if ((CntrPar->LoggingLevel > 2) && (LocalVar->iStatus >= 0) && UnDb3) {
            // WRITE (UnDb3, TRIM(FmtDat)) LocalVar%Time, avrSWAP(avrIndices)
            //
            // A VECTOR SUBSCRIPT: the io-list is the avrSWAP elements named by
            // avrIndices, in that order, not a contiguous slice. Each is a
            // REAL(ReKi) -- a 4-byte float -- widened to the DOUBLE the ES
            // descriptor formats.
            Rec r;
            put_f(r, LocalVar->Time, 20, 5);
            r.tr(5);
            for (int i = 1; i <= avrIndices_size(); ++i) {
                put_es(r, static_cast<double>(avrSWAP[avrIndices_at(i) - 1]), 20, 5, 2);
                r.tr(5);
            }
            r.write_to(UnDb3);
        }
    }

    // ! Close all files when simulation finished
    if (LocalVar->iStatus < 0) {
        // CLOSE on a unit that was never connected is a no-op in Fortran;
        // fclose(nullptr) is not, so the guard is the transcription.
        if (UnDb)  { std::fclose(UnDb);  UnDb  = nullptr; }
        if (UnDb2) { std::fclose(UnDb2); UnDb2 = nullptr; }
        if (UnDb3) { std::fclose(UnDb3); UnDb3 = nullptr; }
    }
}

// --- Fortran-callable C wrapper ---
extern "C" {
    void debug_c(localvariables_view_t* LocalVar, controlparameters_view_t* CntrPar, debugvariables_t* DebugVar, errorvariables_view_t* ErrVar, float* avrSWAP, char* RootName, int size_avcOUTNAME) {
        Debug(LocalVar, CntrPar, DebugVar, ErrVar, avrSWAP, RootName, size_avcOUTNAME);
    }
}
