// C++ implementation of Fortran function: FloatingFeedback
// Generated by VIT (Verified Incremental Translator)
// After verification: FloatingFeedback kernel PASSED

#include "vit_types.h"

// --- User-provided C++ implementation ---
// VIT Translation
// Function: FloatingFeedback
// Source: Controllers.f90
// Module: Controllers
// Fortran: FUNCTION FloatingFeedback(LocalVar, CntrPar, objInst, ErrVar) RESULT(FloatingFeedback)
// Source MD5: 6fc87aa286bd
// VIT: 0.1.0
// Status: unverified

// interp1d and PIController entry points — provided by vit_translated.h (integration)
// or vit_kernel_callees.h (kernel verification).
#include "vit_types.h"
extern "C" {
    double interp1d_c(double* xData, int n_xData, double* yData, int n_yData,
                      double xq, errorvariables_t* ErrVar);
    double picontroller_c(double error, double kp, double ki,
                          double minValue, double maxValue, double DT,
                          double I0, piparams_t* piP, int reset, int* inst);
}

double FloatingFeedback(localvariables_t* LocalVar, controlparameters_view_t* CntrPar, objectinstances_t* objInst, errorvariables_t* ErrVar) {
    // FloatingFeedback: pitch contribution from nacelle velocity feedback
    //   Fl_Mode = 1: proportional feedback of translational nacelle velocity
    //   Fl_Mode = 2: proportional feedback of rotational nacelle velocity

    // Gain scheduling — interpolate Kp_Float from wind speed
    LocalVar->Kp_Float = interp1d_c(CntrPar->Fl_U, CntrPar->n_Fl_U,
                                     CntrPar->Fl_Kp, CntrPar->n_Fl_Kp,
                                     LocalVar->WE_Vw_F, ErrVar);

    // Integrate fore-aft acceleration to get velocity (KP=0, KI=1 → pure integrator)
    double FA_vel = picontroller_c(
        LocalVar->FA_AccF,          // error: fore-aft acceleration
        0.0,                         // kp
        1.0,                         // ki
        -100.0,                      // minValue
        100.0,                       // maxValue
        LocalVar->DT,                // time step
        0.0,                         // I0
        &LocalVar->piP,              // PI parameters struct
        (LocalVar->restart != 0),    // reset flag
        &objInst->instPI             // instance counter
    );

    double NacIMU_FA_vel = picontroller_c(
        LocalVar->NACIMU_FA_AccF,   // error: nacelle IMU fore-aft acceleration
        0.0,                         // kp
        1.0,                         // ki
        -100.0,                      // minValue
        100.0,                       // maxValue
        LocalVar->DT,                // time step
        0.0,                         // I0
        &LocalVar->piP,              // PI parameters struct
        (LocalVar->restart != 0),    // reset flag
        &objInst->instPI             // instance counter
    );

    // Select velocity signal based on mode and apply gain
    double result = 0.0;
    if (CntrPar->Fl_Mode == 1) {
        result = (0.0 - FA_vel) * LocalVar->Kp_Float;
    } else if (CntrPar->Fl_Mode == 2) {
        result = (0.0 - NacIMU_FA_vel) * LocalVar->Kp_Float;
    }

    return result;
}

// --- Fortran-callable C wrapper ---
extern "C" {
    double floatingfeedback_c(localvariables_t* LocalVar, controlparameters_view_t* CntrPar, objectinstances_t* objInst, errorvariables_t* ErrVar) {
        return FloatingFeedback(LocalVar, CntrPar, objInst, ErrVar);
    }
}
