// C++ implementation of Fortran function: ForeAftDamping
// Generated by VIT (Verified Incremental Translator)
// Integrated by `vit integrate`. What verified this function,
// and how strongly, is recorded in the campaign's evidence for
// ForeAftDamping -- not here: integration does not verify anything.

#include "vit_types.h"
#include "vit_translated.h"

// --- User-provided C++ implementation ---
// VIT Translation Scaffold
// Function: ForeAftDamping
// Source: Controllers.f90
// Module: Controllers
// Fortran: SUBROUTINE ForeAftDamping(CntrPar, LocalVar, objInst)
// Reference built with: -fdefault-real-8 -fdefault-double-8 -ffp-contract=off
// Source MD5: a8c867d5d238
// VIT: 0.1.0
// Status: unverified
// Generated: 2026-08-18T00:46:22Z
//
// CONTRACT: mirror (plan.json). Every input and every output crosses the
// signature, and the body is transcribed statement for statement.
//
// TWO STATEMENTS, ONE OF WHICH IS A CALL, AND NOT ONE BRANCH IN THE UNIT.
// Clean `Controllers.f90:586-606` at `54dd134`:
//
//     LocalVar%FA_AccHPFI = PIController(LocalVar%FA_AccHPF, 0.0_DbKi, ...)
//     DO K = 1,LocalVar%NumBl
//         LocalVar%FA_PitCom(K) = LocalVar%FA_AccHPFI
//     END DO
//
// There is no IF anywhere in it. The only control flow is the loop, and its
// trip count is `LocalVar%NumBl` -- which makes NumBl the whole of this unit's
// arm structure and the only pin that narrows anything (harness/ranges.toml).
//
// WHAT THE 27 SCENARIOS SEE, read from coverage/line_coverage.json against the
// clean source. THREE scenarios reach this unit and the other 24 never call it,
// because DISCON's call site at :80 is itself behind `IF (CntrPar%TD_Mode > 0)`:
//
//   :586  the procedure entry        3: 15,999   7: 23,999   27: 23,999
//   :599  the PIController call      the same three counts
//   :602  DO K = 1,NumBl             3: 63,996   7: 95,996   27: 95,996
//   :603  the loop body              the same three counts
//
// 63,996 = 4 x 15,999 and 95,996 = 4 x 23,999, which is gcov's count for a
// three-trip loop (three bodies plus the exit test). So NumBl is 3 in every one
// of the three scenarios and the gate never sees any other trip count. The
// differential harness is the only instrument that varies it, and it varies it
// over {0, 1, 2, 3} -- see the pin's cost note.

#include "vit_types.h"

void ForeAftDamping(controlparameters_view_t* CntrPar, localvariables_view_t* LocalVar, objectinstances_t* objInst) {
    // INTEGER(IntKi) :: K    ! Integer used to loop through turbine blades
    //
    // Declared at the loop below rather than here, because the reference's `K`
    // has no life outside it: nothing before the DO reads it and nothing after
    // it does either. Fortran's implicit-SAVE rule does not apply -- `K` has no
    // initialiser -- so a function-local `static` would be wrong here (contrast
    // the check registry's SAVE rule, which is about declarations WITH one).

    // ! Body
    // LocalVar%FA_AccHPFI = PIController(LocalVar%FA_AccHPF, 0.0_DbKi,
    //     CntrPar%FA_KI, -CntrPar%FA_IntSat, CntrPar%FA_IntSat, LocalVar%DT,
    //     0.0_DbKi, LocalVar%piP, LocalVar%restart, objInst%instPI)
    //
    // `kp = 0.0` AND `ki = FA_KI` MAKE THIS A PURE INTEGRATOR, which is what
    // turns the high-pass-filtered fore-aft ACCELERATION into a velocity --
    // `ROSCO_Types.f90:339-340` names both signals and says so:
    //
    //     FA_AccHPF    ! High-pass filtered fore-aft acceleration [m/s^2]
    //     FA_AccHPFI   ! Tower velocity, high-pass filtered and integrated
    //                    fore-aft acceleration [m/s]
    //
    // The zero `kp` is not a degenerate call to be simplified away: PIController
    // still saturates, still resets, still writes two `piP` slots and still
    // consumes an instance of `objInst%instPI`. Unit #51 makes the same note for
    // the same callee, and unit #48's rule (X1) is the general one -- a callee
    // that exists in Fortran is CALLED, never inlined.
    //
    // *** `-CntrPar%FA_IntSat` IS A UNARY NEGATION AND IS TRANSCRIBED AS ONE,
    // WHICH IS THE OPPOSITE OF WHAT UNIT #51 DID ONE PROCEDURE OVER. ***
    // `floatingfeedback.cpp` writes `(0.0 - FA_vel)` because the REFERENCE
    // writes `(0.0_DbKi - FA_vel)`, and the two spellings differ at a zero:
    // `0.0 - (+0.0)` is `+0.0` while `-(+0.0)` is `-0.0`, and this campaign's
    // harness compares bit patterns. Here the reference writes `-X`, so the
    // translation writes `-X`. Both units transcribe the shape; they look
    // opposite because the two references are.
    //
    // The distinction is live rather than theoretical: `FA_IntSat` is a
    // configured real, `0.0` is inside the harness's draw for it, and
    // `minValue` reaches `saturate` inside PIController on every call.
    //
    // AND THE ORDER OF THE TWO SATURATION ARGUMENTS IS `-FA_IntSat` THEN
    // `+FA_IntSat` -- minValue then maxValue. Swapping them is a program that
    // clamps to an empty interval whenever FA_IntSat > 0.
    //
    // `LocalVar%piP` IS PASSED BY REFERENCE AND IS INTENT(INOUT) IN THE CALLEE,
    // which writes `piP%ITerm(inst)` and `piP%ITermLast(inst)` and then
    // post-increments `inst`. So this unit advances `objInst%instPI` by exactly
    // ONE per invocation -- one call, unconditionally, no arms -- and that is
    // the arithmetic behind the `objInst_instPI` bound in harness/ranges.toml.
    //
    // `LocalVar%restart` is LOGICAL and crosses as `int8_t`; `? 1 : 0` matches
    // the `MERGE(1_C_INT, 0_C_INT, reset)` the generated wrapper writes. The
    // callee bridge converts back with `(reset /= 0)` and the integrated
    // `picontroller.cpp:30` with `(reset != 0)`, so the particular non-zero
    // value is not observable on either tree -- units #50 and #51 both declared
    // the `const_tweak` mutant of this token equivalent, with the probe that
    // says the site is live.
    //
    // THE ASSIGNMENT TARGET IS `LocalVar%FA_AccHPFI`, A FIELD AND NOT A LOCAL.
    // It is therefore one of this unit's outputs, AND the loop below reads it
    // back out of the view struct rather than out of a register -- the
    // reference does the same, reading `LocalVar%FA_AccHPFI` at :603 rather
    // than a saved copy. It is a scalar of `LocalVariables`, so it comes back
    // out of the view only through `vit_copy_scalars_to_localvariables`, which
    // is what `vit integrate --reverse-copy` emits.
    LocalVar->FA_AccHPFI = picontroller_c(LocalVar->FA_AccHPF, 0.0,
                                          CntrPar->FA_KI,
                                          -CntrPar->FA_IntSat,
                                          CntrPar->FA_IntSat,
                                          LocalVar->DT, 0.0, &LocalVar->piP,
                                          LocalVar->restart ? 1 : 0,
                                          &objInst->instPI);

    // ! Store the fore-aft pitch contribution to LocalVar data type
    // DO K = 1,LocalVar%NumBl
    //     LocalVar%FA_PitCom(K) = LocalVar%FA_AccHPFI
    // END DO
    //
    // WRITTEN 1-BASED, WITH `<=`, BECAUSE THAT IS THE OBSERVABLE SHAPE. The
    // runbook's rule from unit #44: an off-by-one in a literally transcribed
    // Fortran loop shows up as a missing element, while the same loop rewritten
    // 0-based can hide it. `K - 1` is the only index arithmetic, applied at the
    // subscript, where `index_offset` can grade it.
    //
    // `LocalVar%FA_PitCom` IS `REAL(DbKi) :: FA_PitCom(3)` -- a FIXED-SIZE
    // field of the type (`ROSCO_Types.f90:341`), not an ALLOCATABLE -- so it
    // crosses as `double FA_PitCom[3]` inside the view struct and there is no
    // synthesised extent to pass. `NumBl` is an ordinary integer field and
    // nothing in the reference checks it against 3: a NumBl above 3 writes past
    // the field in the REFERENCE too. harness/ranges.toml bounds it to [0, 3]
    // for that reason and says so; a guard here would be a test the reference
    // does not have (P7).
    //
    // NumBl == 0 RUNS THE LOOP ZERO TIMES AND IS KEPT IN THE CORPUS. It is the
    // one configuration in which this unit calls PIController, advances the
    // instance counter and writes `FA_AccHPFI`, and yet leaves all three
    // `FA_PitCom` slots at the values they arrived with -- the only way the two
    // statements can be told apart by an input.
    for (int K = 1; K <= LocalVar->NumBl; ++K) {
        LocalVar->FA_PitCom[K - 1] = LocalVar->FA_AccHPFI;
    }
}

// --- Fortran-callable C wrapper ---
extern "C" {
    void foreaftdamping_c(controlparameters_view_t* CntrPar, localvariables_view_t* LocalVar, objectinstances_t* objInst) {
        ForeAftDamping(CntrPar, LocalVar, objInst);
    }
}
