// C++ implementation of Fortran function: LPFilter
// Generated by VIT (Verified Incremental Translator)
// Integrated by `vit integrate`. What verified this function,
// and how strongly, is recorded in the campaign's evidence for
// LPFilter -- not here: integration does not verify anything.

#include "vit_types.h"
#include "vit_translated.h"

// --- User-provided C++ implementation ---
// VIT Translation Scaffold
// Function: LPFilter
// Source: Filters.f90
// Module: Filters
// Fortran: FUNCTION LPFilter(InputSignal, DT, CornerFreq, FP, iStatus, reset, inst, InitialValue)
// Reference built with: -fdefault-real-8 -fdefault-double-8 -ffp-contract=off
// Source MD5: 8055ec1ca707
// VIT: 0.1.0
// Status: unverified
// Generated: 2026-08-11T22:02:50Z

#include "vit_types.h"

double LPFilter(double InputSignal, double DT, double CornerFreq, filterparameters_t* FP, int iStatus, int32_t reset, int* inst, int has_InitialValue, double InitialValue) {
    // `inst` is a 1-based Fortran index into every FP array. Named ONCE, here,
    // so the 0-based conversion has a single site -- units #1 and #4 both paid
    // for restating an index and getting unobservable mutants for it. The
    // increment at the end is written against `*inst` directly, because the
    // Fortran increments the dummy and the caller sees it.
    const int i = *inst - 1;

    // REAL(DbKi) :: InitialValue_
    //   InitialValue_ = InputSignal
    //   IF (PRESENT(InitialValue)) InitialValue_ = InitialValue
    // Transcribed as the Fortran writes it -- a default that is then overwritten
    // -- rather than folded into a conditional expression. `has_InitialValue` is
    // VIT's PRESENT() flag. Unlike HPFilter's, it is NOT dead here: of this
    // unit's 18 live call sites (21 total, 3,527,912 calls across 23 scenarios)
    // exactly one passes the argument -- ControllerBlocks.f90:377,
    // `LPFilter(..., objInst%instLPF, LocalVar%WE_Vw)`, 407,976 calls in 23
    // scenarios -- so the PRESENT branch IS exercised by the simulation. It is
    // still outside the KERNEL, whose window sits at Filters.f90:347, a site
    // that passes no InitialValue.
    double InitialValue_ = InputSignal;
    if (has_InitialValue) InitialValue_ = InitialValue;

    // IF ((iStatus == 0) .OR. reset) THEN
    // `reset` is LOGICAL(4); the generated wrapper hands it over as
    // MERGE(1_C_INT, 0_C_INT, reset), so any non-zero value is .TRUE.
    if ((iStatus == 0) || (reset != 0)) {
        // Source order, and here the order of the first two is NOT free of
        // consequence in the way HPFilter's was: the filter expression below
        // reads lpf1_OutputSignalLast, so this write has to precede it. The two
        // are set to the same value, so their relative order is unobservable;
        // transcribed in source order anyway, because nothing justifies moving.
        FP->lpf1_OutputSignalLast[i] = InitialValue_;
        FP->lpf1_InputSignalLast[i] = InitialValue_;

        // FP%lpf1_a1(inst) = 2 + CornerFreq*DT
        // FP%lpf1_a0(inst) = CornerFreq*DT - 2
        // FP%lpf1_b1(inst) = CornerFreq*DT
        // FP%lpf1_b0(inst) = CornerFreq*DT
        //
        // The Fortran literal `2` is an INTEGER converted to REAL(8) exactly, so
        // `2.0` here is the same value; written as a double to keep the
        // expression in one type rather than relying on C++'s own promotion.
        //
        // `CornerFreq*DT` is written FOUR times because the Fortran writes it
        // four times. It is not the unobservable kind of restatement units #1
        // and #4 deleted: each occurrence lands in a DIFFERENT coefficient, and
        // every one of the four coefficients appears in the filter expression
        // below, so a mutation at any one of them changes the result.
        FP->lpf1_a1[i] = 2.0 + CornerFreq * DT;
        FP->lpf1_a0[i] = CornerFreq * DT - 2.0;
        FP->lpf1_b1[i] = CornerFreq * DT;
        FP->lpf1_b0[i] = CornerFreq * DT;
    }

    // LPFilter = 1.0/FP%lpf1_a1(inst) * (-FP%lpf1_a0(inst)*FP%lpf1_OutputSignalLast(inst)
    //                                    + FP%lpf1_b1(inst)*InputSignal
    //                                    + FP%lpf1_b0(inst)*FP%lpf1_InputSignalLast(inst))
    //
    // Transcribed shape-for-shape, NOT algebraically. `/` and `*` are equal
    // precedence and left-associative in both languages, so `1.0/a1 * (...)` is
    // a RECIPROCAL then a multiply on both sides -- which rounds differently
    // from `(...)/a1`. The two additions inside the parentheses are
    // left-associative in both, so the three terms accumulate in source order.
    //
    // The leading `-` is written as `-(a0*OutLast)` because that is how Fortran
    // parses `-FP%lpf1_a0(inst)*FP%lpf1_OutputSignalLast(inst)`: unary minus
    // binds LOOSER than `*` there and TIGHTER than `*` in C++. The two agree
    // bit-for-bit -- an IEEE sign flip is exact -- so this is about transcribing
    // the parse, not about a rounding difference.
    const double LPFilter_result =
        1.0 / FP->lpf1_a1[i] * (-(FP->lpf1_a0[i] * FP->lpf1_OutputSignalLast[i])
                                + FP->lpf1_b1[i] * InputSignal
                                + FP->lpf1_b0[i] * FP->lpf1_InputSignalLast[i]);

    // Save signals for next time step. The Fortran stores the RESULT, and it
    // stores it AFTER reading the previous values above -- so both reads in the
    // filter expression must happen before these two writes.
    FP->lpf1_InputSignalLast[i] = InputSignal;
    FP->lpf1_OutputSignalLast[i] = LPFilter_result;

    *inst = *inst + 1;

    return LPFilter_result;
}

// --- Fortran-callable C wrapper ---
extern "C" {
    double lpfilter_c(double InputSignal, double DT, double CornerFreq, filterparameters_t* FP, int iStatus, int32_t reset, int* inst, int has_InitialValue, double InitialValue) {
        return LPFilter(InputSignal, DT, CornerFreq, FP, iStatus, reset, inst, has_InitialValue, InitialValue);
    }
}
