// C++ implementation of Fortran function: NotchFilter
// Generated by VIT (Verified Incremental Translator)
// After verification: NotchFilter kernel PASSED

#include "vit_types.h"

// --- User-provided C++ implementation ---
// VIT Translation Scaffold
// Function: NotchFilter
// Source: Filters.f90
// Module: Filters
// Fortran: FUNCTION NotchFilter(InputSignal, DT, omega, betaNum, betaDen, FP, iStatus, reset, inst, InitialValue)
// Source MD5: 4d7afd533dd7
// VIT: 0.1.0
// Status: unverified
// Generated: 2026-03-19T03:19:26Z

#include "vit_types.h"
double NotchFilter(double InputSignal, double DT, double omega, double betaNum, double betaDen, filterparameters_t* FP, int iStatus, int reset, int* inst, int has_InitialValue, double InitialValue) {
    int idx = *inst - 1;  // Fortran 1-based → C 0-based

    // OPTIONAL handling
    double InitialValue_ = InputSignal;
    if (has_InitialValue) InitialValue_ = InitialValue;

    // Initialization
    double K = 2.0 / DT;
    if (iStatus == 0 || reset) {
        FP->nf_OutputSignalLast1[idx] = InitialValue_;
        FP->nf_OutputSignalLast2[idx] = InitialValue_;
        FP->nf_InputSignalLast1[idx] = InitialValue_;
        FP->nf_InputSignalLast2[idx] = InitialValue_;
        FP->nf_b2[idx] = (K * K + 2.0 * omega * betaNum * K + omega * omega) / (K * K + 2.0 * omega * betaDen * K + omega * omega);
        FP->nf_b1[idx] = (2.0 * omega * omega - 2.0 * K * K) / (K * K + 2.0 * omega * betaDen * K + omega * omega);
        FP->nf_b0[idx] = (K * K - 2.0 * omega * betaNum * K + omega * omega) / (K * K + 2.0 * omega * betaDen * K + omega * omega);
        FP->nf_a1[idx] = (2.0 * omega * omega - 2.0 * K * K) / (K * K + 2.0 * omega * betaDen * K + omega * omega);
        FP->nf_a0[idx] = (K * K - 2.0 * omega * betaDen * K + omega * omega) / (K * K + 2.0 * omega * betaDen * K + omega * omega);
    }

    // Filter
    double result = FP->nf_b2[idx] * InputSignal
                  + FP->nf_b1[idx] * FP->nf_InputSignalLast1[idx]
                  + FP->nf_b0[idx] * FP->nf_InputSignalLast2[idx]
                  - FP->nf_a1[idx] * FP->nf_OutputSignalLast1[idx]
                  - FP->nf_a0[idx] * FP->nf_OutputSignalLast2[idx];

    // Save signals for next time step
    FP->nf_InputSignalLast2[idx] = FP->nf_InputSignalLast1[idx];
    FP->nf_InputSignalLast1[idx] = InputSignal;
    FP->nf_OutputSignalLast2[idx] = FP->nf_OutputSignalLast1[idx];
    FP->nf_OutputSignalLast1[idx] = result;
    *inst = *inst + 1;

    return result;
}

// --- Fortran-callable C wrapper ---
extern "C" {
    double notchfilter_c(double InputSignal, double DT, double omega, double betaNum, double betaDen, filterparameters_t* FP, int iStatus, int reset, int* inst, int has_InitialValue, double InitialValue) {
        return NotchFilter(InputSignal, DT, omega, betaNum, betaDen, FP, iStatus, reset, inst, has_InitialValue, InitialValue);
    }
}
