// C++ implementation of Fortran function: PIDController
// Generated by VIT (Verified Incremental Translator)
// After verification: PIDController kernel PASSED

#include "vit_types.h"

// --- User-provided C++ implementation ---
// VIT Translation Scaffold
// Function: PIDController
// Source: Controllers.f90
// Module: Controllers
// Fortran: FUNCTION PIDController(error, kp, ki, kd, tf, minValue, maxValue, DT, I0, piP, reset, objInst, LocalVar)
// Source MD5: 9e2a63a1564a
// VIT: 0.1.0
// Status: unverified
// Generated: 2026-04-01T22:04:01Z

#include "vit_types.h"

// Callee entry points — provided by vit_translated.h (integration)
// or vit_kernel_callees.h (kernel verification).
extern "C" {
    double saturate_c(double inputValue, double minValue, double maxValue);
    double lpfilter_c(double InputSignal, double DT, double CornerFreq,
                      filterparameters_t* FP, int iStatus, int reset, int* inst,
                      int has_InitialValue, double InitialValue);
}

double PIDController(double error, double kp, double ki, double kd, double tf, double minValue, double maxValue, double DT, double I0, piparams_t* piP, int reset, objectinstances_t* objInst, localvariables_t* LocalVar) {
    int piIdx = objInst->instPI - 1;  // Fortran 1-based -> C 0-based
    double result;

    // Always filter error for derivative calculation
    double EFilt = lpfilter_c(error, DT, tf, &LocalVar->FP, LocalVar->iStatus, reset, &objInst->instLPF, 0, 0.0);

    if (reset) {
        piP->ITerm[piIdx] = I0;
        piP->ITermLast[piIdx] = I0;
        piP->ELast[piIdx] = 0.0;
        result = I0;
    } else {
        // Proportional
        double PTerm = kp * error;

        // Integrate and saturate
        piP->ITerm[piIdx] = piP->ITerm[piIdx] + DT * ki * error;
        piP->ITerm[piIdx] = saturate_c(piP->ITerm[piIdx], minValue, maxValue);

        // Derivative (filtered)
        double DTerm = kd * (EFilt - piP->ELast[piIdx]) / DT;

        // Saturate all
        result = saturate_c(PTerm + piP->ITerm[piIdx] + DTerm, minValue, maxValue);

        // Save lasts
        piP->ITermLast[piIdx] = piP->ITerm[piIdx];
        piP->ELast[piIdx] = EFilt;
    }

    objInst->instPI = objInst->instPI + 1;

    return result;
}

// --- Fortran-callable C wrapper ---
extern "C" {
    double pidcontroller_c(double error, double kp, double ki, double kd, double tf, double minValue, double maxValue, double DT, double I0, piparams_t* piP, int reset, objectinstances_t* objInst, localvariables_t* LocalVar) {
        return PIDController(error, kp, ki, kd, tf, minValue, maxValue, DT, I0, piP, reset, objInst, LocalVar);
    }
}
