// C++ implementation of Fortran function: PitchSaturation
// Generated by VIT (Verified Incremental Translator)
// After verification: PitchSaturation kernel PASSED

#include "vit_types.h"

// --- User-provided C++ implementation ---
// VIT Translation Scaffold
// Function: PitchSaturation
// Source: ControllerBlocks.f90
// Module: ControllerBlocks
// Fortran: FUNCTION PitchSaturation(LocalVar, CntrPar, objInst, DebugVar, ErrVar)
// Source MD5: c9cf442e202f
// VIT: 0.1.0
// Status: unverified
// Generated: 2026-03-28T00:37:27Z

#include "vit_types.h"
#include <cstring>

extern "C" {

double interp1d_c(double* xData, int n_xData, double* yData, int n_yData,
                  double xq, errorvariables_t* ErrVar);

double PitchSaturation(localvariables_t* LocalVar, controlparameters_view_t* CntrPar, objectinstances_t* objInst, debugvariables_t* DebugVar, errorvariables_t* ErrVar) {

    // Define minimum blade pitch angle for peak shaving as a function of estimated wind speed
    LocalVar->PS_Min_Pitch = interp1d_c(CntrPar->PS_WindSpeeds, CntrPar->n_PS_WindSpeeds,
                                        CntrPar->PS_BldPitchMin, CntrPar->n_PS_BldPitchMin,
                                        LocalVar->WE_Vw_F, ErrVar);

    // Total min pitch limit is greater of peak shaving and power control pitch
    double result = (LocalVar->PS_Min_Pitch > LocalVar->PRC_Min_Pitch)
                    ? LocalVar->PS_Min_Pitch : LocalVar->PRC_Min_Pitch;

    // Add RoutineName to error message
    if (ErrVar->aviFAIL < 0) {
        // Fortran: ErrVar%ErrMsg = RoutineName//':'//TRIM(ErrVar%ErrMsg)
        int trimmed_len = 1024;
        while (trimmed_len > 0 && ErrVar->ErrMsg[trimmed_len - 1] == ' ') {
            trimmed_len--;
        }
        char buf[1024];
        const char prefix[] = "PitchSaturation:";
        int prefix_len = 16;
        memcpy(buf, prefix, prefix_len);
        int copy_len = trimmed_len;
        if (prefix_len + copy_len > 1024) copy_len = 1024 - prefix_len;
        memcpy(buf + prefix_len, ErrVar->ErrMsg, copy_len);
        int total = prefix_len + copy_len;
        if (total < 1024) memset(buf + total, ' ', 1024 - total);
        memcpy(ErrVar->ErrMsg, buf, 1024);
    }

    return result;
}

} // extern "C"

// --- Fortran-callable C wrapper ---
extern "C" {
    double pitchsaturation_c(localvariables_t* LocalVar, controlparameters_view_t* CntrPar, objectinstances_t* objInst, debugvariables_t* DebugVar, errorvariables_t* ErrVar) {
        return PitchSaturation(LocalVar, CntrPar, objInst, DebugVar, ErrVar);
    }
}
