// C++ implementation of Fortran function: PowerControlSetpoints
// Generated by VIT (Verified Incremental Translator)
// After verification: PowerControlSetpoints kernel PASSED

#include "vit_types.h"

// --- User-provided C++ implementation ---
// VIT Translation Scaffold
// Function: PowerControlSetpoints
// Source: ControllerBlocks.f90
// Module: ControllerBlocks
// Fortran: SUBROUTINE PowerControlSetpoints(CntrPar, LocalVar, objInst, DebugVar, ErrVar)
// Source MD5: 698e5372ba1f
// VIT: 0.1.0
// Status: unverified
// Generated: 2026-03-28T12:00:16Z

#include "vit_types.h"
#include "rosco_constants.h"

extern "C" {

double interp1d_c(double* xData, int n_xData, double* yData, int n_yData,
                  double xq, errorvariables_t* ErrVar);

void PowerControlSetpoints(controlparameters_view_t* CntrPar, localvariables_t* LocalVar, objectinstances_t* objInst, debugvariables_t* DebugVar, errorvariables_t* ErrVar) {

    // Set up power control
    if (CntrPar->PRC_Mode == 2) { // Using power reference control
        if (CntrPar->PRC_Comm == PRC_Comm_Constant) { // Constant, from DISCON
            LocalVar->PRC_R_Speed = CntrPar->PRC_R_Speed;
            LocalVar->PRC_R_Torque = CntrPar->PRC_R_Torque;
            LocalVar->PRC_R_Pitch = CntrPar->PRC_R_Pitch;

        } else if (CntrPar->PRC_Comm == PRC_Comm_OpenLoop) { // Open loop

            if (CntrPar->Ind_R_Speed > 0) {
                LocalVar->PRC_R_Speed = interp1d_c(CntrPar->OL_Breakpoints, CntrPar->n_OL_Breakpoints,
                                                   CntrPar->OL_R_Speed, CntrPar->n_OL_R_Speed,
                                                   LocalVar->OL_Index, ErrVar);
            } else {
                LocalVar->PRC_R_Speed = 1.0;
            }

            if (CntrPar->Ind_R_Torque > 0) {
                LocalVar->PRC_R_Torque = interp1d_c(CntrPar->OL_Breakpoints, CntrPar->n_OL_Breakpoints,
                                                    CntrPar->OL_R_Torque, CntrPar->n_OL_R_Torque,
                                                    LocalVar->OL_Index, ErrVar);
            } else {
                LocalVar->PRC_R_Torque = 1.0;
            }

            if (CntrPar->Ind_R_Pitch > 0) {
                LocalVar->PRC_R_Pitch = interp1d_c(CntrPar->OL_Breakpoints, CntrPar->n_OL_Breakpoints,
                                                   CntrPar->OL_R_Pitch, CntrPar->n_OL_R_Pitch,
                                                   LocalVar->OL_Index, ErrVar);
            } else {
                LocalVar->PRC_R_Pitch = 1.0;
            }

        } else if (CntrPar->PRC_Comm == PRC_Comm_ZMQ) { // ZeroMQ
            LocalVar->PRC_R_Speed = LocalVar->ZMQ_R_Speed;
            LocalVar->PRC_R_Torque = LocalVar->ZMQ_R_Torque;
            LocalVar->PRC_R_Pitch = LocalVar->ZMQ_R_Pitch;
        }

        // Set min pitch for power control
        LocalVar->PRC_Min_Pitch = interp1d_c(CntrPar->PRC_R_Table, CntrPar->n_PRC_R_Table,
                                             CntrPar->PRC_Pitch_Table, CntrPar->n_PRC_Pitch_Table,
                                             LocalVar->PRC_R_Pitch, ErrVar);

    } else {
        LocalVar->PRC_R_Speed = 1.0;
        LocalVar->PRC_R_Torque = 1.0;
        LocalVar->PRC_R_Pitch = 1.0;
        LocalVar->PRC_Min_Pitch = CntrPar->PC_FinePit;
    }
}

} // extern "C"

// --- Fortran-callable C wrapper ---
extern "C" {
    void powercontrolsetpoints_c(controlparameters_view_t* CntrPar, localvariables_t* LocalVar, objectinstances_t* objInst, debugvariables_t* DebugVar, errorvariables_t* ErrVar) {
        PowerControlSetpoints(CntrPar, LocalVar, objInst, DebugVar, ErrVar);
    }
}
