// C++ implementation of Fortran function: Read_OL_Input
// Generated by VIT (Verified Incremental Translator)
// Integrated by `vit integrate`. What verified this function,
// and how strongly, is recorded in the campaign's evidence for
// Read_OL_Input -- not here: integration does not verify anything.

#include "vit_types.h"
#include "vit_translated.h"

// --- User-provided C++ implementation ---
// VIT Translation Scaffold
// Function: Read_OL_Input
// Source: ROSCO_Helpers.f90
// Module: ROSCO_Helpers
// Fortran: SUBROUTINE Read_OL_Input(OL_InputFileName, Unit_OL_Input, NumChannels, Channels, ErrVar)
// Reference built with: -fdefault-real-8 -fdefault-double-8 -ffp-contract=off
// Source MD5: c82cd261fbf3
// VIT: 0.1.0
// Status: unverified
// Generated: 2026-08-12T04:09:11Z
//
// CONTRACT: respecify (plan.json). This unit performs external formatted I/O on
// a Fortran unit number it opens and closes itself, so a literal transcription
// is impossible: a Fortran unit number has no representation on the C side. The
// contract it is held to is (file on disk, NumChannels) -> (Channels, ErrVar),
// and the parts that are NOT I/O -- the comment/data line accounting, the error
// messages, the allocation shape, the column-major fill -- are transcribed
// literally, because those are what a value comparison can see.
//
// WHAT THE FORTRAN'S LIST-DIRECTED READ MEANS, and what is reimplemented here.
// `READ(u,*,IOSTAT=IOS) (TmpData(I), I=1,NumChannels)` is Fortran list-directed
// input. The forms implemented are the ones gfortran accepts for a REAL list:
//
//   separators   blank, comma, tab; leading/trailing blanks ignored
//   null value   two adjacent separators leave that item UNCHANGED, IOS = 0
//   terminator   `/` ends the list; remaining items unchanged, IOS = 0
//   repeat       `r*value` and the null form `r*`
//   real forms   [s]ddd[.ddd][EeDdQq[s]dd] and the exponent-letter-less
//                `1.5-3` == 1.5e-3 that gfortran also accepts
//   continuation a list that is not satisfied by one record CONTINUES into the
//                next record. An INTERNAL read has one record, so running out
//                is end-of-file: IOS < 0.
//
// NOT implemented, and therefore outside this translation's stated domain:
// NAMELIST, complex `(re,im)`, `r*` with a repeat count that overflows, and the
// BLANK=/DECIMAL= mode changes -- the reference opens with neither.
// See evidence/Read_OL_Input/ for what the campaign's instruments could reach.

#include "vit_types.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>
#include <sys/stat.h>

namespace {

// Fortran TRIM: trailing blanks only. The dummy is CHARACTER(1024), so the name
// arrives blank-padded to a fixed width that is compiled into both sides -- it
// is NOT a parameter, which is why nothing in the C signature states it.
constexpr int OL_INPUT_FILENAME_LEN = 1024;

std::string fortran_trim(const char* buf, int width) {
    int n = width;
    while (n > 0 && buf[n - 1] == ' ') --n;
    return std::string(buf, static_cast<size_t>(n));
}

// `ErrVar%ErrMsg = <expr>` on a CHARACTER(:), ALLOCATABLE field is a
// REALLOCATING assignment: the new length is the right-hand side's. The view's
// staging buffer is finite, so an assignment that does not fit is REFUSED and
// reported rather than truncated -- a shortened message is the one wrong answer
// a byte comparison cannot tell from a right one. Same shape as ReadAvrSWAP.
//
// `n_ErrMsg < 0` on ENTRY means the field arrived UNALLOCATED, which is exactly
// what happens at this unit's only reachable call site. A reallocating
// assignment allocates it, so writing here is correct and the reverse copy
// performs the allocation; that the view supplies a buffer either way is a
// change made for this unit (vit/view_populator.py, 2026-08-12) after the
// kernel reported 200 of 200 IDENTICAL on a run that wrote no message at all.
void assign_errmsg(errorvariables_view_t* ErrVar, const std::string& s) {
    if (ErrVar->ErrMsg == nullptr) {
        std::fprintf(stderr,
                     "VIT: Read_OL_Input: ErrVar%%ErrMsg has no staging buffer; "
                     "the assignment of %d bytes is refused\n",
                     static_cast<int>(s.size()));
        return;
    }
    if (static_cast<int32_t>(s.size()) > ErrVar->n_ErrMsg_cap) {
        std::fprintf(stderr,
                     "VIT: Read_OL_Input: ErrVar%%ErrMsg needs %d bytes, "
                     "staging buffer holds %d; field left unchanged\n",
                     static_cast<int>(s.size()), static_cast<int>(ErrVar->n_ErrMsg_cap));
        return;
    }
    std::memcpy(ErrVar->ErrMsg, s.data(), s.size());
    ErrVar->n_ErrMsg = static_cast<int32_t>(s.size());
}

// TRIM(ErrVar%ErrMsg): trailing blanks only, off the CURRENT length.
std::string trimmed_errmsg(const errorvariables_view_t* ErrVar) {
    if (ErrVar->ErrMsg == nullptr || ErrVar->n_ErrMsg <= 0) return std::string();
    return fortran_trim(ErrVar->ErrMsg, static_cast<int>(ErrVar->n_ErrMsg));
}

// ---------------------------------------------------------------------------
// List-directed input
// ---------------------------------------------------------------------------

bool is_sep(char c) { return c == ' ' || c == ',' || c == '\t'; }

// One list-directed REAL datum out of `rec` starting at `pos`.
// Returns false on a malformed datum (the reference's IOS > 0).
bool scan_real(const std::string& rec, size_t& pos, double& value) {
    const size_t n = rec.size();
    size_t i = pos;
    const size_t start = i;
    if (i < n && (rec[i] == '+' || rec[i] == '-')) ++i;
    size_t digits = 0;
    while (i < n && rec[i] >= '0' && rec[i] <= '9') { ++i; ++digits; }
    if (i < n && rec[i] == '.') {
        ++i;
        while (i < n && rec[i] >= '0' && rec[i] <= '9') { ++i; ++digits; }
    }
    if (digits == 0) return false;
    // Exponent: an explicit letter, or gfortran's letter-less signed form.
    if (i < n && (rec[i] == 'e' || rec[i] == 'E' || rec[i] == 'd' || rec[i] == 'D' ||
                  rec[i] == 'q' || rec[i] == 'Q')) {
        size_t save = i;
        ++i;
        if (i < n && (rec[i] == '+' || rec[i] == '-')) ++i;
        size_t ed = 0;
        while (i < n && rec[i] >= '0' && rec[i] <= '9') { ++i; ++ed; }
        if (ed == 0) { i = save; }
    } else if (i < n && (rec[i] == '+' || rec[i] == '-')) {
        size_t save = i;
        ++i;
        size_t ed = 0;
        while (i < n && rec[i] >= '0' && rec[i] <= '9') { ++i; ++ed; }
        if (ed == 0) { i = save; }
    }
    // The datum must end at a separator or at the end of the record.
    if (i < n && !is_sep(rec[i]) && rec[i] != '/') return false;

    // strtod does not know 'D'/'Q'; normalise the exponent letter, and supply
    // an 'e' for the letter-less form so the same converter handles both.
    std::string tok = rec.substr(start, i - start);
    for (size_t k = 1; k < tok.size(); ++k) {
        if (tok[k] == 'd' || tok[k] == 'D' || tok[k] == 'q' || tok[k] == 'Q') tok[k] = 'e';
        else if ((tok[k] == '+' || tok[k] == '-') && tok[k - 1] != 'e' && tok[k - 1] != 'E')
            { tok.insert(k, 1, 'e'); ++k; }
    }
    const char* c = tok.c_str();
    char* end = nullptr;
    value = std::strtod(c, &end);
    if (end == c) return false;
    pos = i;
    return true;
}

// An unsigned integer repeat count followed by '*'. Returns 0 when there is none.
long scan_repeat(const std::string& rec, size_t& pos) {
    size_t i = pos;
    const size_t n = rec.size();
    size_t d = 0;
    long r = 0;
    while (i < n && rec[i] >= '0' && rec[i] <= '9') { r = r * 10 + (rec[i] - '0'); ++i; ++d; }
    if (d == 0 || i >= n || rec[i] != '*' || r <= 0) return 0;
    pos = i + 1;
    return r;
}

// The IOSTAT contract of the reference's reads, reproduced:
//   0   the whole list was satisfied (or `/` ended it)
//  <0   the input ran out first (end of file / end of an internal record)
//  >0   a datum was malformed
enum class ListIO { Ok = 0, Eof = -1, Bad = 1 };

// `records` is a cursor over a source of records: an external file reads on,
// an internal file has exactly one.
struct RecordSource {
    virtual ~RecordSource() = default;
    virtual bool next(std::string& rec) = 0;
};

struct FileRecords : RecordSource {
    std::FILE* fp;
    explicit FileRecords(std::FILE* f) : fp(f) {}
    bool next(std::string& rec) override {
        if (fp == nullptr) return false;
        rec.clear();
        int c;
        bool any = false;
        while ((c = std::fgetc(fp)) != EOF) {
            any = true;
            if (c == '\n') return true;
            if (c != '\r') rec.push_back(static_cast<char>(c));
        }
        return any;   // a final record with no newline is still a record
    }
};

struct OneRecord : RecordSource {
    std::string rec;
    bool done = false;
    explicit OneRecord(std::string r) : rec(std::move(r)) {}
    bool next(std::string& out) override {
        if (done) return false;
        done = true;
        out = rec;
        return true;
    }
};

ListIO read_list_reals(RecordSource& src, double* data, int count) {
    if (count <= 0) {
        // An EMPTY io-list still performs record positioning for an advancing
        // transfer, so it consumes one record and reports end-of-file when
        // there is none. Returning Ok unconditionally instead would make the
        // reference's `DO WHILE (IOS == 0)` loop non-terminating.
        std::string skip;
        return src.next(skip) ? ListIO::Ok : ListIO::Eof;
    }
    std::string rec;
    size_t pos = 0;
    bool have = false;
    int filled = 0;
    long repeat = 0;
    bool repeat_null = false;
    double repeat_value = 0.0;

    while (filled < count) {
        if (repeat > 0) {
            if (!repeat_null) data[filled] = repeat_value;
            ++filled;
            --repeat;
            continue;
        }
        if (!have) {
            if (!src.next(rec)) return ListIO::Eof;
            pos = 0;
            have = true;
        }
        // gfortran treats a TAB in list-directed input as a blank, not as the
        // comma that separates a null value. Only a comma makes a null.
        while (pos < rec.size() && (rec[pos] == ' ' || rec[pos] == '\t')) ++pos;
        if (pos >= rec.size()) { have = false; continue; }
        if (rec[pos] == '/') return ListIO::Ok;          // terminator
        if (rec[pos] == ',') {                           // a null value
            ++pos;
            ++filled;                                     // item left unchanged
            continue;
        }
        long r = scan_repeat(rec, pos);
        if (r > 0) {
            if (pos >= rec.size() || is_sep(rec[pos]) || rec[pos] == '/') {
                repeat = r; repeat_null = true;           // `r*` -- r null values
                continue;
            }
            double v;
            if (!scan_real(rec, pos, v)) return ListIO::Bad;
            repeat = r; repeat_null = false; repeat_value = v;
            continue;
        }
        double v;
        if (!scan_real(rec, pos, v)) return ListIO::Bad;
        data[filled] = v;
        ++filled;
        // Consume the separator that ended the datum. A comma is the separator
        // itself; blanks are skipped by the loop head next time round.
        if (pos < rec.size() && rec[pos] == ',') ++pos;
    }
    return ListIO::Ok;
}

}  // namespace

void Read_OL_Input(char* OL_InputFileName, int Unit_OL_Input, int NumChannels, double** Channels,
                   int* n_Channels_rows, int* n_Channels_cols, errorvariables_view_t* ErrVar) {
    (void)Unit_OL_Input;   // a Fortran unit number has no C representation; the
                           // reference opens and closes it itself, so the unit
                           // is not part of the (data in) -> (data out) contract.

    // INTENT(OUT) ALLOCATABLE: not allocated until the reference allocates it.
    // C_NULL_PTR is what the wrapper reads as "not allocated" (P6).
    *Channels = nullptr;
    *n_Channels_rows = 0;
    *n_Channels_cols = 0;

    const std::string name = fortran_trim(OL_InputFileName, OL_INPUT_FILENAME_LEN);

    // INQUIRE (FILE = OL_InputFileName, EXIST = FileExists)
    struct stat sb;
    const bool FileExists = !name.empty() && ::stat(name.c_str(), &sb) == 0;

    if (!FileExists) {
        ErrVar->aviFAIL = -1;
        assign_errmsg(ErrVar, name + " does not exist");
    } else {
        // OPEN(..., STATUS='OLD', FORM='FORMATTED', IOSTAT=IOS, ACTION='READ')
        std::FILE* fp = std::fopen(name.c_str(), "r");
        if (fp == nullptr) {
            ErrVar->aviFAIL = -1;
            assign_errmsg(ErrVar, "Cannot open " + name);
        } else {
            FileRecords src(fp);
            std::vector<double> TmpData(NumChannels > 0 ? static_cast<size_t>(NumChannels) : 0, 0.0);

            // LINE = '!' ; NumComments = -1
            std::string Line = "!";
            int NumComments = -1;
            ListIO ios = ListIO::Ok;

            while (Line.find('!') != std::string::npos ||
                   Line.find('#') != std::string::npos ||
                   Line.find('%') != std::string::npos) {
                ++NumComments;
                std::string rec;
                if (src.next(rec)) {
                    // CHARACTER(1024) :: Line -- an 'A' edit read blank-fills
                    // the whole declared width and TRUNCATES a longer record.
                    if (rec.size() > 1024) rec.resize(1024);
                    Line = rec;
                } else {
                    // The record source ran out. gfortran leaves LINE unchanged
                    // on an end-of-file read, which would spin here forever on
                    // an all-comment file; the reference has the same hole and
                    // this transcription does not invent an answer for it --
                    // it stops, which is the only behaviour that terminates.
                    break;
                }
            }

            int NumDataLines = 0;

            // READ(LINE,*,IOSTAT=IOS) ( TmpData(I), I=1,NumChannels )
            {
                OneRecord one(Line);
                ios = read_list_reals(one, TmpData.data(), NumChannels);
            }

            while (ios == ListIO::Ok) {
                ++NumDataLines;
                ios = read_list_reals(src, TmpData.data(), NumChannels);
            }

            if (NumDataLines < 1) {
                // WRITE (NumString,'(I11)') NumComments -- an I11 edit is RIGHT
                // JUSTIFIED in eleven columns, and CHARACTER(15) blank-pads the
                // remaining four. TRIM removes the four; the LEADING blanks of
                // the I11 field stay, and they are in the message.
                char NumString[16];
                std::snprintf(NumString, sizeof(NumString), "%11d", NumComments);
                std::string ns(NumString);
                while (!ns.empty() && ns.back() == ' ') ns.pop_back();
                ErrVar->aviFAIL = -1;
                assign_errmsg(ErrVar,
                              "Error: " + ns +
                              " comment lines were found in the uniform wind file, "
                              "but the first data line does not contain the proper format.");
                std::fclose(fp);
                fp = nullptr;
            }

            // ALLOCATE(Channels(NumDataLines,NumChannels))
            const long rows = NumDataLines;
            const long cols = NumChannels;
            const long nelem = (rows > 0 && cols > 0) ? rows * cols : 0;
            double* buf = static_cast<double*>(std::malloc(
                static_cast<size_t>(nelem > 0 ? nelem : 1) * sizeof(double)));
            *Channels = buf;
            *n_Channels_rows = static_cast<int>(rows);
            *n_Channels_cols = static_cast<int>(cols);

            if (fp != nullptr) {
                // REWIND, then skip the comment lines
                std::rewind(fp);
                for (int i = 1; i <= NumComments; ++i) {
                    std::string rec;
                    if (!src.next(rec)) break;
                }

                for (long i = 1; i <= rows; ++i) {
                    ListIO r = read_list_reals(src, TmpData.data(), NumChannels);
                    if (r == ListIO::Bad) {
                        std::fclose(fp);
                        fp = nullptr;
                        src.fp = nullptr;
                    }
                    // Channels(I,:) = TmpData -- Fortran is column-major, so the
                    // row is STRIDED: element (i,j) sits at (j-1)*rows + (i-1).
                    for (long j = 1; j <= cols; ++j)
                        buf[(j - 1) * rows + (i - 1)] = TmpData[static_cast<size_t>(j - 1)];
                }
            }
            if (fp != nullptr) std::fclose(fp);
        }
    }

    if (ErrVar->aviFAIL < 0)
        assign_errmsg(ErrVar, "Read_OL_Input:" + trimmed_errmsg(ErrVar));
}

// VIT allocate-on-return support. Frees a buffer that the translation
// handed to the Fortran wrapper, using the allocator that made it.
// Weak: several translations may each define it; the linker keeps one.
#include <cstdlib>
extern "C" {
    __attribute__((weak)) void vit_free(void* vit_p) { std::free(vit_p); }
}

// --- Fortran-callable C wrapper ---
extern "C" {
    void read_ol_input_c(char* OL_InputFileName, int Unit_OL_Input, int NumChannels, double** Channels, int* n_Channels_rows, int* n_Channels_cols, errorvariables_view_t* ErrVar) {
        Read_OL_Input(OL_InputFileName, Unit_OL_Input, NumChannels, Channels, n_Channels_rows, n_Channels_cols, ErrVar);
    }
}
