// C++ implementation of Fortran function: ReadAvrSWAP
// Generated by VIT (Verified Incremental Translator)
// Integrated by `vit integrate`. What verified this function,
// and how strongly, is recorded in the campaign's evidence for
// ReadAvrSWAP -- not here: integration does not verify anything.

#include "vit_types.h"
#include "vit_translated.h"

// --- User-provided C++ implementation ---
// VIT Translation Scaffold
// Function: ReadAvrSWAP
// Source: ReadSetParameters.f90
// Module: ReadSetParameters
// Fortran: SUBROUTINE ReadAvrSWAP(avrSWAP, LocalVar, CntrPar, ErrVar)
// Reference built with: -fdefault-real-8 -fdefault-double-8 -ffp-contract=off
// Source MD5: 5b2dcf10ae7b
// VIT: 0.1.0
// Status: unverified
// Generated: 2026-08-12T02:12:58Z

#include "vit_types.h"

#include <cmath>
#include <cstdio>
#include <cstring>

namespace {

// Constants.f90:22-23. Both are declared REAL(DbKi), and the literal that
// initialises each carries NO kind suffix -- so under this campaign's
// -fdefault-real-8 the literal is itself parsed at kind 8 and no narrowing
// happens anywhere. Written here as the same decimal text.
constexpr double R2D = 57.2957795130;
constexpr double D2R = 0.01745329251;

// The message the already-loaded branch assigns. ErrVar%ErrMsg is
// CHARACTER(:), ALLOCATABLE, so the Fortran assignment REALLOCATES it to
// exactly this length -- it does not blank-fill a fixed width.
const char ALREADY_LOADED_MSG[] =
    "ERROR: This ROSCO dynamic library has already been loaded.";
constexpr int ALREADY_LOADED_LEN = (int)(sizeof(ALREADY_LOADED_MSG) - 1);

}  // namespace

void ReadAvrSWAP(float* avrSWAP, localvariables_view_t* LocalVar,
                 controlparameters_view_t* CntrPar, errorvariables_view_t* ErrVar) {
    // Index used for looping through blades. INTEGER(IntKi) :: K
    int K;

    // Load variables from calling program (See Appendix A of Bladed User's Guide):
    //
    // avrSWAP is REAL(ReKi) and ReKi is C_FLOAT (Constants.f90:18), so every
    // read below is a float widened to double -- exact, and NOT the same thing
    // as reading a double. NINT is round-half-away-from-zero, which is
    // std::lround and not a cast and not rint.
    LocalVar->iStatus = (int)std::lround((double)avrSWAP[0]);
    LocalVar->Time = avrSWAP[1];
    LocalVar->DT = avrSWAP[2];
    LocalVar->VS_MechGenPwr = avrSWAP[13];
    LocalVar->VS_GenPwr = avrSWAP[14];
    LocalVar->GenSpeed = avrSWAP[19];
    LocalVar->RotSpeed = avrSWAP[20];
    LocalVar->GenTqMeas = avrSWAP[22];
    LocalVar->NacVane = (double)avrSWAP[23] * R2D;
    LocalVar->HorWindV = avrSWAP[26];
    LocalVar->rootMOOP[0] = avrSWAP[29];
    LocalVar->rootMOOP[1] = avrSWAP[30];
    LocalVar->rootMOOP[2] = avrSWAP[31];
    LocalVar->NacHeading = (double)avrSWAP[36] * R2D;
    // This is the translational acceleration of the tower top in the non-rotating frame
    LocalVar->FA_Acc_TT = avrSWAP[52];
    // This is the translational acceleration of the tower top in the non-rotating frame
    LocalVar->SS_Acc_TT = avrSWAP[53];
    // This is the rotational aceleration of the nacelle in the shaft frame
    LocalVar->NacIMU_FA_RAcc = avrSWAP[82];
    LocalVar->Azimuth = avrSWAP[59];
    LocalVar->NumBl = (int)std::lround((double)avrSWAP[60]);

    if (CntrPar->Ext_Interface > 0) {  // Use extended bladed interface

        // Platform signals
        LocalVar->PtfmTDX = avrSWAP[1000];
        LocalVar->PtfmTDY = avrSWAP[1001];
        LocalVar->PtfmTDZ = avrSWAP[1002];
        LocalVar->PtfmRDX = avrSWAP[1003];
        LocalVar->PtfmRDY = avrSWAP[1004];
        LocalVar->PtfmRDZ = avrSWAP[1005];
        LocalVar->PtfmTVX = avrSWAP[1006];
        LocalVar->PtfmTVY = avrSWAP[1007];
        LocalVar->PtfmTVZ = avrSWAP[1008];
        LocalVar->PtfmRVX = avrSWAP[1009];
        LocalVar->PtfmRVY = avrSWAP[1010];
        LocalVar->PtfmRVZ = avrSWAP[1011];
        LocalVar->PtfmTAX = avrSWAP[1012];
        LocalVar->PtfmTAY = avrSWAP[1013];
        LocalVar->PtfmTAZ = avrSWAP[1014];
        LocalVar->PtfmRAX = avrSWAP[1015];
        LocalVar->PtfmRAY = avrSWAP[1016];
        LocalVar->PtfmRAZ = avrSWAP[1017];

    }

    // Check that we haven't already loaded this dynamic library
    if (LocalVar->iStatus == 0) {
        if (LocalVar->AlreadyInitialized == 0) {
            LocalVar->AlreadyInitialized = 1;
        } else {
            ErrVar->aviFAIL = -1;
            // ErrVar%ErrMsg = '...' on a CHARACTER(:), ALLOCATABLE field is a
            // REALLOCATING assignment: the new length is the literal's, not the
            // old one's. The staging buffer's capacity is finite, so an
            // assignment that does not fit is REFUSED and reported rather than
            // truncated -- a shortened message is the one wrong answer a byte
            // comparison cannot tell from a right one.
            if (ALREADY_LOADED_LEN <= (int)ErrVar->n_ErrMsg_cap) {
                std::memcpy(ErrVar->ErrMsg, ALREADY_LOADED_MSG,
                            (size_t)ALREADY_LOADED_LEN);
                ErrVar->n_ErrMsg = (int32_t)ALREADY_LOADED_LEN;
            } else {
                std::fprintf(stderr,
                             "VIT: ReadAvrSWAP: ErrVar%%ErrMsg needs %d bytes, "
                             "staging buffer holds %d; field left unchanged\n",
                             ALREADY_LOADED_LEN, (int)ErrVar->n_ErrMsg_cap);
            }
            return;
        }
    }

    // --- NJA: usually feedback back the previous pitch command helps for numerical stability, sometimes it does not...
    if (LocalVar->iStatus == 0) {
        LocalVar->BlPitch[0] = avrSWAP[3];
        LocalVar->BlPitch[1] = avrSWAP[32];
        LocalVar->BlPitch[2] = avrSWAP[33];
    } else {

        // Subtract pitch actuator fault for blade K - This in a sense would make the controller blind to the pitch fault
        if (CntrPar->PF_Mode == 1) {
            for (K = 1; K <= LocalVar->NumBl; K++) {
                // This assumes that the pitch actuator fault is hardware fault
                LocalVar->BlPitch[K - 1] =
                    LocalVar->PitComAct[K - 1] - CntrPar->PF_Offsets[K - 1];  // why is PitCom used and not PitComAct??
            }
        } else {
            LocalVar->BlPitch[0] = LocalVar->PitComAct[0];
            LocalVar->BlPitch[1] = LocalVar->PitComAct[1];
            LocalVar->BlPitch[2] = LocalVar->PitComAct[2];
        }

    }

    // `REAL(LocalVar%NumBl)` names no kind, so under -fdefault-real-8 it is
    // kind 8 and the reciprocal is formed in double. The grouping is the
    // reference's: a reciprocal FIRST, then one multiply, and a left-to-right
    // sum inside the parentheses.
    LocalVar->BlPitchCMeas =
        (1.0 / (double)LocalVar->NumBl) *
        ((LocalVar->BlPitch[0] + LocalVar->BlPitch[1]) + LocalVar->BlPitch[2]);

    // TODO: Technically, LocalVar%Time > 0, too, but this restart is in many places as a reset
    if (LocalVar->iStatus == 0) {
        LocalVar->restart = 1;
    } else {
        LocalVar->restart = 0;
    }

    // FA_Acc_TT is in the non-rotating tower-top frame, so we need to convert it to the rotating (nacelle) frame of reference
    LocalVar->FA_Acc_Nac = LocalVar->FA_Acc_TT * std::cos(LocalVar->NacHeading * D2R) +
                           LocalVar->SS_Acc_TT * std::sin(LocalVar->NacHeading * D2R);

    // Increment timestep counter
    if (LocalVar->iStatus == 0 && LocalVar->Time == 0) {
        LocalVar->n_DT = 0;
    } else {
        LocalVar->n_DT = LocalVar->n_DT + 1;
    }
}

// --- Fortran-callable C wrapper ---
extern "C" {
    void readavrswap_c(float* avrSWAP, localvariables_view_t* LocalVar, controlparameters_view_t* CntrPar, errorvariables_view_t* ErrVar) {
        ReadAvrSWAP(avrSWAP, LocalVar, CntrPar, ErrVar);
    }
}
