! ROSCO IO
! This file is automatically generated by write_registry.py using ROSCO v2.10.1
! For any modification to the registry, please edit the rosco_types.yaml accordingly
 
MODULE ROSCO_IO
    USE, INTRINSIC :: ISO_C_Binding
    USE ROSCO_Types
    USE ReadSetParameters
    USE Constants
IMPLICIT NONE


    ! Auto-generated interface for C++ implementation of Debug
    INTERFACE
        SUBROUTINE debug_c(LocalVar, CntrPar, DebugVar, ErrVar, avrSWAP, RootName, size_avcOUTNAME) BIND(C, NAME='debug_c')
            USE ISO_C_BINDING
            TYPE(C_PTR), VALUE :: LocalVar
            TYPE(C_PTR), VALUE :: CntrPar
            TYPE(C_PTR), VALUE :: DebugVar
            TYPE(C_PTR), VALUE :: ErrVar
            REAL(C_FLOAT), INTENT(INOUT) :: avrSWAP(*)
            CHARACTER(KIND=C_CHAR), INTENT(IN) :: RootName(*)
            INTEGER(C_INT), VALUE :: size_avcOUTNAME
        END SUBROUTINE debug_c
    END INTERFACE


    ! Auto-generated interface for C++ implementation of WriteRestartFile
    INTERFACE
        SUBROUTINE writerestartfile_c(LocalVar, CntrPar, ErrVar, objInst, RootName, size_avcOUTNAME) BIND(C, NAME='writerestartfile_c')
            USE ISO_C_BINDING
            TYPE(C_PTR), VALUE :: LocalVar
            TYPE(C_PTR), VALUE :: CntrPar
            TYPE(C_PTR), VALUE :: ErrVar
            TYPE(C_PTR), VALUE :: objInst
            CHARACTER(KIND=C_CHAR), INTENT(IN) :: RootName(*)
            INTEGER(C_INT), VALUE :: size_avcOUTNAME
        END SUBROUTINE writerestartfile_c
    END INTERFACE

CONTAINS

    SUBROUTINE WriteRestartFile(LocalVar, CntrPar, ErrVar, objInst, RootName, size_avcOUTNAME)
        USE ISO_C_BINDING
        USE vit_localvariables_view, ONLY: localvariables_view_t, vit_populate_localvariables, vit_copy_scalars_to_localvariables
        USE vit_controlparameters_view, ONLY: controlparameters_view_t, vit_populate_controlparameters, vit_copy_scalars_to_controlparameters
        USE vit_errorvariables_view, ONLY: errorvariables_view_t, vit_populate_errorvariables, vit_copy_scalars_to_errorvariables
        IMPLICIT NONE
        TYPE(LOCALVARIABLES), INTENT(IN), TARGET :: LocalVar
        TYPE(CONTROLPARAMETERS), INTENT(INOUT), TARGET :: CntrPar
        TYPE(ERRORVARIABLES), INTENT(INOUT), TARGET :: ErrVar
        TYPE(OBJECTINSTANCES), INTENT(INOUT), TARGET :: objInst
        INTEGER(4), INTENT(IN) :: size_avcOUTNAME
        CHARACTER(SIZE_AVCOUTNAME), INTENT(IN) :: RootName
        CHARACTER(KIND=C_CHAR) :: RootName_c(size_avcOUTNAME)
        INTEGER :: vit_i_RootName
        TYPE(localvariables_view_t), TARGET :: LocalVar_view
        TYPE(controlparameters_view_t), TARGET :: CntrPar_view
        TYPE(errorvariables_view_t), TARGET :: ErrVar_view
        ! Populate view structs from Fortran types
        CALL vit_populate_localvariables(LocalVar, LocalVar_view)
        CALL vit_populate_controlparameters(CntrPar, CntrPar_view)
        CALL vit_populate_errorvariables(ErrVar, ErrVar_view)
        ! Convert CHARACTER args to C_CHAR arrays
        DO vit_i_RootName = 1, size_avcOUTNAME
            RootName_c(vit_i_RootName) = RootName(vit_i_RootName:vit_i_RootName)
        END DO
        CALL writerestartfile_c(C_LOC(LocalVar_view), C_LOC(CntrPar_view), C_LOC(ErrVar_view), C_LOC(objInst), RootName_c, size_avcOUTNAME)
        ! Copy modified scalars back from view to Fortran type
        CALL vit_copy_scalars_to_controlparameters(CntrPar_view, CntrPar)
        CALL vit_copy_scalars_to_errorvariables(ErrVar_view, ErrVar)
    END SUBROUTINE WriteRestartFile

 
SUBROUTINE ReadRestartFile(avrSWAP, LocalVar, CntrPar, objInst, PerfData, RootName, size_avcOUTNAME, ErrVar)
    TYPE(LocalVariables), INTENT(INOUT)             :: LocalVar
    TYPE(ControlParameters), INTENT(INOUT)          :: CntrPar
    TYPE(ObjectInstances), INTENT(INOUT)            :: objInst
    TYPE(PerformanceData), INTENT(INOUT)            :: PerfData
    TYPE(ErrorVariables), INTENT(INOUT)             :: ErrVar
    REAL(ReKi), INTENT(IN)                          :: avrSWAP(*)
    INTEGER(IntKi), INTENT(IN)                      :: size_avcOUTNAME
    CHARACTER(size_avcOUTNAME), INTENT(IN)        :: RootName 
    
    INTEGER(IntKi)               :: Un                  ! I/O unit for pack/unpack (checkpoint & restart)
    INTEGER(IntKi)               :: I                   ! Generic index.
    CHARACTER(128)               :: InFile              ! Input checkpoint file
    INTEGER(IntKi)               :: ErrStat
    CHARACTER(128)               :: ErrMsg              
    CHARACTER(128)               :: n_t_global          ! timestep number as a string

    WRITE(n_t_global, '(I0.0)' ) NINT(avrSWAP(2)/avrSWAP(3))
    InFile = TRIM(RootName)//TRIM( n_t_global )//'.RO.chkp'
    CALL GetNewUnit(Un, ErrVar)
    OPEN(unit=Un, FILE=TRIM(InFile), STATUS='UNKNOWN', FORM='UNFORMATTED' , ACCESS='STREAM', IOSTAT=ErrStat, ACTION='READ' )

    IF ( ErrStat /= 0 ) THEN
        ErrVar%aviFAIL = 1
        ErrVar%ErrMsg  = 'ROSCO_IO: Cannot open checkpoint file '//TRIM(InFile)//' for reading'

    ELSE
        READ( Un, IOSTAT=ErrStat) LocalVar%iStatus
        READ( Un, IOSTAT=ErrStat) LocalVar%AlreadyInitialized
        READ( Un, IOSTAT=ErrStat) LocalVar%RestartWSE
        READ( Un, IOSTAT=ErrStat) LocalVar%Time
        READ( Un, IOSTAT=ErrStat) LocalVar%DT
        READ( Un, IOSTAT=ErrStat) LocalVar%WriteThisStep
        READ( Un, IOSTAT=ErrStat) LocalVar%n_DT
        READ( Un, IOSTAT=ErrStat) LocalVar%Time_Last
        READ( Un, IOSTAT=ErrStat) LocalVar%VS_GenPwr
        READ( Un, IOSTAT=ErrStat) LocalVar%GenSpeed
        READ( Un, IOSTAT=ErrStat) LocalVar%RotSpeed
        READ( Un, IOSTAT=ErrStat) LocalVar%NacHeading
        READ( Un, IOSTAT=ErrStat) LocalVar%NacVane
        READ( Un, IOSTAT=ErrStat) LocalVar%NacVaneF
        READ( Un, IOSTAT=ErrStat) LocalVar%WindDir
        READ( Un, IOSTAT=ErrStat) LocalVar%HorWindV
        READ( Un, IOSTAT=ErrStat) LocalVar%HorWindV_F
        READ( Un, IOSTAT=ErrStat) LocalVar%rootMOOP(1)
        READ( Un, IOSTAT=ErrStat) LocalVar%rootMOOP(2)
        READ( Un, IOSTAT=ErrStat) LocalVar%rootMOOP(3)
        READ( Un, IOSTAT=ErrStat) LocalVar%rootMOOPF(1)
        READ( Un, IOSTAT=ErrStat) LocalVar%rootMOOPF(2)
        READ( Un, IOSTAT=ErrStat) LocalVar%rootMOOPF(3)
        READ( Un, IOSTAT=ErrStat) LocalVar%BlPitch(1)
        READ( Un, IOSTAT=ErrStat) LocalVar%BlPitch(2)
        READ( Un, IOSTAT=ErrStat) LocalVar%BlPitch(3)
        READ( Un, IOSTAT=ErrStat) LocalVar%BlPitchCMeas
        READ( Un, IOSTAT=ErrStat) LocalVar%Azimuth
        READ( Un, IOSTAT=ErrStat) LocalVar%OL_Azimuth
        READ( Un, IOSTAT=ErrStat) LocalVar%AzUnwrapped
        READ( Un, IOSTAT=ErrStat) LocalVar%AzError
        READ( Un, IOSTAT=ErrStat) LocalVar%GenTqAz
        READ( Un, IOSTAT=ErrStat) LocalVar%AzBuffer(1)
        READ( Un, IOSTAT=ErrStat) LocalVar%AzBuffer(2)
        READ( Un, IOSTAT=ErrStat) LocalVar%NumBl
        READ( Un, IOSTAT=ErrStat) LocalVar%FA_Acc_TT
        READ( Un, IOSTAT=ErrStat) LocalVar%SS_Acc_TT
        READ( Un, IOSTAT=ErrStat) LocalVar%FA_Acc_Nac
        READ( Un, IOSTAT=ErrStat) LocalVar%NacIMU_FA_RAcc
        READ( Un, IOSTAT=ErrStat) LocalVar%FA_AccHPF
        READ( Un, IOSTAT=ErrStat) LocalVar%FA_AccHPFI
        READ( Un, IOSTAT=ErrStat) LocalVar%FA_PitCom(1)
        READ( Un, IOSTAT=ErrStat) LocalVar%FA_PitCom(2)
        READ( Un, IOSTAT=ErrStat) LocalVar%FA_PitCom(3)
        READ( Un, IOSTAT=ErrStat) LocalVar%VS_RefSpd
        READ( Un, IOSTAT=ErrStat) LocalVar%VS_RefSpd_TSR
        READ( Un, IOSTAT=ErrStat) LocalVar%VS_RefSpd_TRA
        READ( Un, IOSTAT=ErrStat) LocalVar%VS_RefSpd_RL
        READ( Un, IOSTAT=ErrStat) LocalVar%PC_RefSpd
        READ( Un, IOSTAT=ErrStat) LocalVar%PC_RefSpd_SS
        READ( Un, IOSTAT=ErrStat) LocalVar%PC_RefSpd_PRC
        READ( Un, IOSTAT=ErrStat) LocalVar%RotSpeedF
        READ( Un, IOSTAT=ErrStat) LocalVar%GenSpeedF
        READ( Un, IOSTAT=ErrStat) LocalVar%GenTq
        READ( Un, IOSTAT=ErrStat) LocalVar%GenTqMeas
        READ( Un, IOSTAT=ErrStat) LocalVar%GenArTq
        READ( Un, IOSTAT=ErrStat) LocalVar%GenBrTq
        READ( Un, IOSTAT=ErrStat) LocalVar%VS_KOmega2_GenTq
        READ( Un, IOSTAT=ErrStat) LocalVar%VS_ConstPwr_GenTq
        READ( Un, IOSTAT=ErrStat) LocalVar%IPC_PitComF(1)
        READ( Un, IOSTAT=ErrStat) LocalVar%IPC_PitComF(2)
        READ( Un, IOSTAT=ErrStat) LocalVar%IPC_PitComF(3)
        READ( Un, IOSTAT=ErrStat) LocalVar%PC_KP
        READ( Un, IOSTAT=ErrStat) LocalVar%PC_KI
        READ( Un, IOSTAT=ErrStat) LocalVar%PC_KD
        READ( Un, IOSTAT=ErrStat) LocalVar%PC_TF
        READ( Un, IOSTAT=ErrStat) LocalVar%PC_MaxPit
        READ( Un, IOSTAT=ErrStat) LocalVar%PC_MinPit
        READ( Un, IOSTAT=ErrStat) LocalVar%PC_PitComT
        READ( Un, IOSTAT=ErrStat) LocalVar%PC_PitComT_Last
        READ( Un, IOSTAT=ErrStat) LocalVar%BlPitchCMeasF
        READ( Un, IOSTAT=ErrStat) LocalVar%PC_PitComT_IPC(1)
        READ( Un, IOSTAT=ErrStat) LocalVar%PC_PitComT_IPC(2)
        READ( Un, IOSTAT=ErrStat) LocalVar%PC_PitComT_IPC(3)
        READ( Un, IOSTAT=ErrStat) LocalVar%PC_PwrErr
        READ( Un, IOSTAT=ErrStat) LocalVar%PC_SpdErr
        READ( Un, IOSTAT=ErrStat) LocalVar%IPC_AxisTilt_1P
        READ( Un, IOSTAT=ErrStat) LocalVar%IPC_AxisYaw_1P
        READ( Un, IOSTAT=ErrStat) LocalVar%IPC_AxisTilt_2P
        READ( Un, IOSTAT=ErrStat) LocalVar%IPC_AxisYaw_2P
        READ( Un, IOSTAT=ErrStat) LocalVar%axisTilt_1P
        READ( Un, IOSTAT=ErrStat) LocalVar%axisYaw_1P
        READ( Un, IOSTAT=ErrStat) LocalVar%axisYawF_1P
        READ( Un, IOSTAT=ErrStat) LocalVar%axisTilt_2P
        READ( Un, IOSTAT=ErrStat) LocalVar%axisYaw_2P
        READ( Un, IOSTAT=ErrStat) LocalVar%axisYawF_2P
        READ( Un, IOSTAT=ErrStat) LocalVar%IPC_KI(1)
        READ( Un, IOSTAT=ErrStat) LocalVar%IPC_KI(2)
        READ( Un, IOSTAT=ErrStat) LocalVar%IPC_KP(1)
        READ( Un, IOSTAT=ErrStat) LocalVar%IPC_KP(2)
        READ( Un, IOSTAT=ErrStat) LocalVar%IPC_IntSat
        READ( Un, IOSTAT=ErrStat) LocalVar%PC_State
        READ( Un, IOSTAT=ErrStat) LocalVar%PitCom(1)
        READ( Un, IOSTAT=ErrStat) LocalVar%PitCom(2)
        READ( Un, IOSTAT=ErrStat) LocalVar%PitCom(3)
        READ( Un, IOSTAT=ErrStat) LocalVar%PitCom_SD(1)
        READ( Un, IOSTAT=ErrStat) LocalVar%PitCom_SD(2)
        READ( Un, IOSTAT=ErrStat) LocalVar%PitCom_SD(3)
        READ( Un, IOSTAT=ErrStat) LocalVar%PitComAct(1)
        READ( Un, IOSTAT=ErrStat) LocalVar%PitComAct(2)
        READ( Un, IOSTAT=ErrStat) LocalVar%PitComAct(3)
        READ( Un, IOSTAT=ErrStat) LocalVar%SS_DelOmegaF
        READ( Un, IOSTAT=ErrStat) LocalVar%TestType
        READ( Un, IOSTAT=ErrStat) LocalVar%Kp_Float
        READ( Un, IOSTAT=ErrStat) LocalVar%VS_MaxTq
        READ( Un, IOSTAT=ErrStat) LocalVar%VS_LastGenTrq
        READ( Un, IOSTAT=ErrStat) LocalVar%VS_LastGenPwr
        READ( Un, IOSTAT=ErrStat) LocalVar%VS_MechGenPwr
        READ( Un, IOSTAT=ErrStat) LocalVar%VS_SpdErrAr
        READ( Un, IOSTAT=ErrStat) LocalVar%VS_SpdErrBr
        READ( Un, IOSTAT=ErrStat) LocalVar%VS_SpdErr
        READ( Un, IOSTAT=ErrStat) LocalVar%VS_State
        READ( Un, IOSTAT=ErrStat) LocalVar%VS_Rgn3Pitch
        READ( Un, IOSTAT=ErrStat) LocalVar%WE_Vw
        READ( Un, IOSTAT=ErrStat) LocalVar%WE_Vw_F
        READ( Un, IOSTAT=ErrStat) LocalVar%WE_VwI
        READ( Un, IOSTAT=ErrStat) LocalVar%WE_VwIdot
        READ( Un, IOSTAT=ErrStat) LocalVar%WE_Op
        READ( Un, IOSTAT=ErrStat) LocalVar%WE_Op_Last
        READ( Un, IOSTAT=ErrStat) LocalVar%VS_LastGenTrqF
        READ( Un, IOSTAT=ErrStat) LocalVar%PRC_WSE_F
        READ( Un, IOSTAT=ErrStat) LocalVar%PRC_R_Speed
        READ( Un, IOSTAT=ErrStat) LocalVar%PRC_R_Torque
        READ( Un, IOSTAT=ErrStat) LocalVar%PRC_R_Pitch
        READ( Un, IOSTAT=ErrStat) LocalVar%PRC_R_Total
        READ( Un, IOSTAT=ErrStat) LocalVar%PRC_Min_Pitch
        READ( Un, IOSTAT=ErrStat) LocalVar%PS_Min_Pitch
        READ( Un, IOSTAT=ErrStat) LocalVar%OL_Index
        READ( Un, IOSTAT=ErrStat) LocalVar%SU_Stage
        READ( Un, IOSTAT=ErrStat) LocalVar%SU_LoadStageStartTime
        READ( Un, IOSTAT=ErrStat) LocalVar%SU_RotSpeedF
        READ( Un, IOSTAT=ErrStat) LocalVar%SD_Trigger
        READ( Un, IOSTAT=ErrStat) LocalVar%SD_BlPitchF
        READ( Un, IOSTAT=ErrStat) LocalVar%SD_NacVaneF
        READ( Un, IOSTAT=ErrStat) LocalVar%SD_GenSpeedF
        READ( Un, IOSTAT=ErrStat) LocalVar%SD_Stage
        READ( Un, IOSTAT=ErrStat) LocalVar%SD_StageStartTime
        READ( Un, IOSTAT=ErrStat) LocalVar%SD_MaxPitchRate
        READ( Un, IOSTAT=ErrStat) LocalVar%SD_MaxTorqueRate
        READ( Un, IOSTAT=ErrStat) LocalVar%GenTq_SD
        READ( Un, IOSTAT=ErrStat) LocalVar%Fl_PitCom
        READ( Un, IOSTAT=ErrStat) LocalVar%NACIMU_FA_AccF
        READ( Un, IOSTAT=ErrStat) LocalVar%FA_AccF
        READ( Un, IOSTAT=ErrStat) LocalVar%FA_Hist
        READ( Un, IOSTAT=ErrStat) LocalVar%TRA_LastRefSpd
        READ( Un, IOSTAT=ErrStat) LocalVar%VS_RefSpeed
        READ( Un, IOSTAT=ErrStat) LocalVar%PtfmTDX
        READ( Un, IOSTAT=ErrStat) LocalVar%PtfmTDY
        READ( Un, IOSTAT=ErrStat) LocalVar%PtfmTDZ
        READ( Un, IOSTAT=ErrStat) LocalVar%PtfmRDX
        READ( Un, IOSTAT=ErrStat) LocalVar%PtfmRDY
        READ( Un, IOSTAT=ErrStat) LocalVar%PtfmRDZ
        READ( Un, IOSTAT=ErrStat) LocalVar%PtfmTVX
        READ( Un, IOSTAT=ErrStat) LocalVar%PtfmTVY
        READ( Un, IOSTAT=ErrStat) LocalVar%PtfmTVZ
        READ( Un, IOSTAT=ErrStat) LocalVar%PtfmRVX
        READ( Un, IOSTAT=ErrStat) LocalVar%PtfmRVY
        READ( Un, IOSTAT=ErrStat) LocalVar%PtfmRVZ
        READ( Un, IOSTAT=ErrStat) LocalVar%PtfmTAX
        READ( Un, IOSTAT=ErrStat) LocalVar%PtfmTAY
        READ( Un, IOSTAT=ErrStat) LocalVar%PtfmTAZ
        READ( Un, IOSTAT=ErrStat) LocalVar%PtfmRAX
        READ( Un, IOSTAT=ErrStat) LocalVar%PtfmRAY
        READ( Un, IOSTAT=ErrStat) LocalVar%PtfmRAZ
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_DesiredL(1)
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_DesiredL(2)
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_DesiredL(3)
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_DesiredL(4)
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_DesiredL(5)
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_DesiredL(6)
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_DesiredL(7)
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_DesiredL(8)
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_DesiredL(9)
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_DesiredL(10)
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_DesiredL(11)
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_DesiredL(12)
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_ActuatedL(1)
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_ActuatedL(2)
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_ActuatedL(3)
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_ActuatedL(4)
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_ActuatedL(5)
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_ActuatedL(6)
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_ActuatedL(7)
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_ActuatedL(8)
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_ActuatedL(9)
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_ActuatedL(10)
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_ActuatedL(11)
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_ActuatedL(12)
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_ActuatedDL(1)
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_ActuatedDL(2)
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_ActuatedDL(3)
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_ActuatedDL(4)
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_ActuatedDL(5)
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_ActuatedDL(6)
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_ActuatedDL(7)
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_ActuatedDL(8)
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_ActuatedDL(9)
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_ActuatedDL(10)
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_ActuatedDL(11)
        READ( Un, IOSTAT=ErrStat) LocalVar%CC_ActuatedDL(12)
        READ( Un, IOSTAT=ErrStat) LocalVar%StC_Input(1)
        READ( Un, IOSTAT=ErrStat) LocalVar%StC_Input(2)
        READ( Un, IOSTAT=ErrStat) LocalVar%StC_Input(3)
        READ( Un, IOSTAT=ErrStat) LocalVar%StC_Input(4)
        READ( Un, IOSTAT=ErrStat) LocalVar%StC_Input(5)
        READ( Un, IOSTAT=ErrStat) LocalVar%StC_Input(6)
        READ( Un, IOSTAT=ErrStat) LocalVar%StC_Input(7)
        READ( Un, IOSTAT=ErrStat) LocalVar%StC_Input(8)
        READ( Un, IOSTAT=ErrStat) LocalVar%StC_Input(9)
        READ( Un, IOSTAT=ErrStat) LocalVar%StC_Input(10)
        READ( Un, IOSTAT=ErrStat) LocalVar%StC_Input(11)
        READ( Un, IOSTAT=ErrStat) LocalVar%StC_Input(12)
        READ( Un, IOSTAT=ErrStat) LocalVar%Flp_Angle(1)
        READ( Un, IOSTAT=ErrStat) LocalVar%Flp_Angle(2)
        READ( Un, IOSTAT=ErrStat) LocalVar%Flp_Angle(3)
        READ( Un, IOSTAT=ErrStat) LocalVar%RootMyb_Last(1)
        READ( Un, IOSTAT=ErrStat) LocalVar%RootMyb_Last(2)
        READ( Un, IOSTAT=ErrStat) LocalVar%RootMyb_Last(3)
        READ( Un, IOSTAT=ErrStat) LocalVar%ACC_INFILE_SIZE
        ALLOCATE(LocalVar%ACC_INFILE(LocalVar%ACC_INFILE_SIZE))
        READ( Un, IOSTAT=ErrStat) LocalVar%ACC_INFILE
        READ( Un, IOSTAT=ErrStat) LocalVar%restart
        READ( Un, IOSTAT=ErrStat) LocalVar%AWC_complexangle(1)
        READ( Un, IOSTAT=ErrStat) LocalVar%AWC_complexangle(2)
        READ( Un, IOSTAT=ErrStat) LocalVar%AWC_complexangle(3)
        READ( Un, IOSTAT=ErrStat) LocalVar%TiltMean
        READ( Un, IOSTAT=ErrStat) LocalVar%YawMean
        READ( Un, IOSTAT=ErrStat) LocalVar%ZMQ_ID
        READ( Un, IOSTAT=ErrStat) LocalVar%ZMQ_YawOffset
        READ( Un, IOSTAT=ErrStat) LocalVar%ZMQ_TorqueOffset
        READ( Un, IOSTAT=ErrStat) LocalVar%ZMQ_PitOffset(1)
        READ( Un, IOSTAT=ErrStat) LocalVar%ZMQ_PitOffset(2)
        READ( Un, IOSTAT=ErrStat) LocalVar%ZMQ_PitOffset(3)
        READ( Un, IOSTAT=ErrStat) LocalVar%ZMQ_R_Speed
        READ( Un, IOSTAT=ErrStat) LocalVar%ZMQ_R_Torque
        READ( Un, IOSTAT=ErrStat) LocalVar%ZMQ_R_Pitch
        READ( Un, IOSTAT=ErrStat) LocalVar%WE%om_r
        READ( Un, IOSTAT=ErrStat) LocalVar%WE%v_t
        READ( Un, IOSTAT=ErrStat) LocalVar%WE%v_m
        READ( Un, IOSTAT=ErrStat) LocalVar%WE%v_h
        READ( Un, IOSTAT=ErrStat) LocalVar%WE%P
        READ( Un, IOSTAT=ErrStat) LocalVar%WE%xh
        READ( Un, IOSTAT=ErrStat) LocalVar%WE%K
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%lpf1_a1
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%lpf1_a0
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%lpf1_b1
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%lpf1_b0
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%lpf1_InputSignalLast
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%lpf1_OutputSignalLast
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%lpf2_a2
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%lpf2_a1
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%lpf2_a0
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%lpf2_b2
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%lpf2_b1
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%lpf2_b0
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%lpf2_InputSignalLast2
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%lpf2_OutputSignalLast2
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%lpf2_InputSignalLast1
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%lpf2_OutputSignalLast1
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%lpfV_a2
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%lpfV_a1
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%lpfV_a0
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%lpfV_b2
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%lpfV_b1
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%lpfV_b0
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%lpfV_InputSignalLast2
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%lpfV_OutputSignalLast2
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%lpfV_InputSignalLast1
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%lpfV_OutputSignalLast1
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%hpf_InputSignalLast
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%hpf_OutputSignalLast
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%nfs_OutputSignalLast1
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%nfs_OutputSignalLast2
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%nfs_InputSignalLast1
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%nfs_InputSignalLast2
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%nfs_b2
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%nfs_b0
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%nfs_a2
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%nfs_a1
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%nfs_a0
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%nf_OutputSignalLast1
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%nf_OutputSignalLast2
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%nf_InputSignalLast1
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%nf_InputSignalLast2
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%nf_b2
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%nf_b1
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%nf_b0
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%nf_a1
        READ( Un, IOSTAT=ErrStat) LocalVar%FP%nf_a0
        READ( Un, IOSTAT=ErrStat) LocalVar%piP%ITerm
        READ( Un, IOSTAT=ErrStat) LocalVar%piP%ITermLast
        READ( Un, IOSTAT=ErrStat) LocalVar%piP%ITerm2
        READ( Un, IOSTAT=ErrStat) LocalVar%piP%ITermLast2
        READ( Un, IOSTAT=ErrStat) LocalVar%piP%ELast
        READ( Un, IOSTAT=ErrStat) LocalVar%resP%res_OutputSignalLast1
        READ( Un, IOSTAT=ErrStat) LocalVar%resP%res_OutputSignalLast2
        READ( Un, IOSTAT=ErrStat) LocalVar%resP%res_InputSignalLast1
        READ( Un, IOSTAT=ErrStat) LocalVar%resP%res_InputSignalLast2
        READ( Un, IOSTAT=ErrStat) LocalVar%rlP%LastSignal
        READ( Un, IOSTAT=ErrStat) objInst%instLPF
        READ( Un, IOSTAT=ErrStat) objInst%instSecLPF
        READ( Un, IOSTAT=ErrStat) objInst%instSecLPFV
        READ( Un, IOSTAT=ErrStat) objInst%instHPF
        READ( Un, IOSTAT=ErrStat) objInst%instNotchSlopes
        READ( Un, IOSTAT=ErrStat) objInst%instNotch
        READ( Un, IOSTAT=ErrStat) objInst%instPI
        READ( Un, IOSTAT=ErrStat) objInst%instRes
        READ( Un, IOSTAT=ErrStat) objInst%instRL
        Close ( Un )
        IF ( ErrStat /= 0 ) THEN
            ErrVar%aviFAIL = 1
            ErrVar%ErrMsg  = 'ROSCO_IO: Error reading checkpoint file.'
        ENDIF
    ENDIF
    ! Read Parameter files
    CALL ReadControlParameterFileSub(CntrPar, LocalVar, LocalVar%ACC_INFILE, LocalVar%ACC_INFILE_SIZE, RootName, ErrVar)
    IF (CntrPar%WE_Mode > 0) THEN
        CALL READCpFile(CntrPar, PerfData, ErrVar)
    ENDIF
END SUBROUTINE ReadRestartFile

 
    SUBROUTINE Debug(LocalVar, CntrPar, DebugVar, ErrVar, avrSWAP, RootName, size_avcOUTNAME)
        USE ISO_C_BINDING
        USE vit_localvariables_view, ONLY: localvariables_view_t, vit_populate_localvariables
        USE vit_controlparameters_view, ONLY: controlparameters_view_t, vit_populate_controlparameters
        USE vit_errorvariables_view, ONLY: errorvariables_view_t, vit_populate_errorvariables
        IMPLICIT NONE
        TYPE(LOCALVARIABLES), INTENT(IN), TARGET :: LocalVar
        TYPE(CONTROLPARAMETERS), INTENT(IN), TARGET :: CntrPar
        TYPE(DEBUGVARIABLES), INTENT(IN), TARGET :: DebugVar
        TYPE(ERRORVARIABLES), INTENT(INOUT), TARGET :: ErrVar
        REAL(4), INTENT(INOUT) :: avrSWAP(*)
        INTEGER(4), INTENT(IN) :: size_avcOUTNAME
        CHARACTER(SIZE_AVCOUTNAME), INTENT(IN) :: RootName
        CHARACTER(KIND=C_CHAR) :: RootName_c(size_avcOUTNAME)
        INTEGER :: vit_i_RootName
        TYPE(localvariables_view_t), TARGET :: LocalVar_view
        TYPE(controlparameters_view_t), TARGET :: CntrPar_view
        TYPE(errorvariables_view_t), TARGET :: ErrVar_view
        ! Populate view structs from Fortran types
        CALL vit_populate_localvariables(LocalVar, LocalVar_view)
        CALL vit_populate_controlparameters(CntrPar, CntrPar_view)
        CALL vit_populate_errorvariables(ErrVar, ErrVar_view)
        ! Convert CHARACTER args to C_CHAR arrays
        DO vit_i_RootName = 1, size_avcOUTNAME
            RootName_c(vit_i_RootName) = RootName(vit_i_RootName:vit_i_RootName)
        END DO
        CALL debug_c(C_LOC(LocalVar_view), C_LOC(CntrPar_view), C_LOC(DebugVar), C_LOC(ErrVar_view), avrSWAP, RootName_c, size_avcOUTNAME)
    END SUBROUTINE Debug

END MODULE ROSCO_IO
