// C++ implementation of Fortran function: wrap_360
// Generated by VIT (Verified Incremental Translator)
// After verification: wrap_360 kernel PASSED

#include <algorithm>
#include <cmath>

// --- User-provided C++ implementation ---
double wrap_360(double x) {
    if (x < 0.0) {
        return x + 360.0;
    } else if (x >= 360.0) {
        return x - 360.0;
    } else {
        return x;
    }
}

// --- Fortran-callable C wrapper ---
extern "C" {
    double wrap_360_c(double x) {
        return wrap_360(x);
    }
}
