// C++ implementation of Fortran function: wrap_180
// Generated by VIT (Verified Incremental Translator)
// After verification: wrap_180 kernel PASSED

#include <algorithm>
#include <cmath>

// --- User-provided C++ implementation ---
// VIT Translation
// Function: wrap_180
// Source: Functions.f90
// Module: Functions
// Fortran: FUNCTION wrap_180(x)
// Status: verified

double wrap_180(double x) {
    if (x <= -180.0) {
        return x + 360.0;
    } else if (x > 180.0) {
        return x - 360.0;
    } else {
        return x;
    }
}

// --- Fortran-callable C wrapper ---
extern "C" {
    double wrap_180_c(double x) {
        return wrap_180(x);
    }
}
