#!/usr/bin/env python3
"""Derive corpus round 4 for the ReadControlParameterFileSub probe.

WHY THERE IS A ROUND 4. Rounds 1-3 (28 shipped `Examples/DISCON*.IN` + 9
derived) were built to reach ARMS. The mutation sweep asks a different
question -- can the corpus tell the translation from a WRONG translation -- and
it answered 116 of 207. Each file here is derived from `Examples/DISCON.IN` for
a NAMED group of survivors, and the group is written next to it so a later
reader can check the claim rather than inherit it.

ADDITION, NOT MODIFICATION (P5). `derive_corpus.py` is untouched and its nine
files are re-generated by it, byte for byte; this script only writes names that
do not exist there. Both write into the same directory, which the probe globs.

    python3 evidence/ReadControlParameterFileSub/derive_corpus_r4.py

Run from the repository root.
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
BASE = ROOT / 'Examples' / 'DISCON.IN'
OUT = ROOT / 'evidence' / 'ReadControlParameterFileSub' / 'corpus'

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from derive_corpus import sub, drop            # noqa: E402  (P4: not re-typed)

OLF = '/workspace/ROSCO-r2/Examples/example_inputs/Example_OL_Input.dat'


def ol(lines, **kw):
    """Round 2's own OL preamble, imported in spirit: OL_Mode on, a real OL
    file, breakpoint column 1. `Example_OL_Input.dat` has FOUR columns, and
    `Read_OL_Input` reads exactly OL_Count of them -- so every case below is
    built to make OL_Count come out at 4, and the count is written out."""
    out = sub(lines, 'OL_Mode', str(kw.pop('OL_Mode')))
    out = sub(out, 'OL_Filename', OLF)
    out = sub(out, 'Ind_Breakpoint', '1')
    for k, v in kw.items():
        out = sub(out, k, v)
    return out


def main():
    base = BASE.read_text().split('\n')
    OUT.mkdir(parents=True, exist_ok=True)
    files = {}
    raw = {}

    # ---------------------------------------------------------------- 1-11
    # THE `AllowDefault` PREDICATES. Ten `parse_*` calls pass
    # `(<flag> == <n>) ? 1 : 0` as ParseInput's AllowDefault, and a mutant that
    # flips the comparison flips whether a MISSING line is fatal. Nothing in
    # rounds 1-3 has any of these lines missing, so all ten predicates are
    # evaluated and none of them DECIDES anything: 10 compare_op survivors.
    #
    # One dropped line per file, and which way the kill falls does not matter --
    # if the base file's flag makes the default allowed, the reference parses
    # and the mutant errors; if it does not, the reference errors and the mutant
    # parses. Either way the two disagree, which is what the corpus was missing.
    for stem, key in [
            ('ad_lpfdamping', 'F_LPFDamping'),
            ('ad_notch_n', 'F_GenSpdNotch_N'),
            ('ad_twrtop_n', 'F_TwrTopNotch_N'),
            ('ad_sscorner', 'F_SSCornerFreq'),
            ('ad_yawerr', 'F_YawErr'),
            ('ad_flcorner', 'F_FlCornerFreq'),
            ('ad_flhighpass', 'F_FlHighPassFreq'),
            ('ad_flpcorner', 'F_FlpCornerFreq'),
            ('ad_vsrefspd', 'F_VSRefSpdCornerFreq'),
            ('ad_notch_ind', 'F_GenSpdNotch_Ind'),
            ('ad_vsfbp_n', 'VS_FBP_n')]:
        files[f'{stem}.IN'] = drop(base, key)

    # ------------------------------------------------------------------- 12
    # THE PRC ARM. `PRC_R_Torque`'s AllowDefault is
    # `(PRC_Mode /= 2) .OR. (PRC_Comm /= PRC_Comm_Constant)`, and DISCON.IN has
    # PRC_Mode 0 -- so the first disjunct is TRUE in every file of rounds 1-3
    # and the constant `PRC_Comm_Constant = 0` decides nothing. Turning PRC_Mode
    # to 2 with PRC_Comm at 0 makes the whole predicate hang on that constant.
    p = sub(base, 'PRC_Mode', '2')
    p = sub(p, 'PRC_Comm', '0')
    files['prc2_r_torque.IN'] = drop(p, 'PRC_R_Torque')

    # ------------------------------------------------------------------- 13
    # A GROUPING THE REFERENCE WROTE. `VS_MinOMTq = VS_Rgn2K*VS_MinOMSpd**2` is
    # `a*(x*x)` in Fortran and is transcribed as `a*(x*x)`; `assoc_reorder`
    # rewrites it `(a*x)*x`. DISCON.IN's own pair (2.31055, 34.64286) gives the
    # SAME double both ways, and so does every other file in the corpus, which
    # is exactly RT2's finding written as a survivor. One digit moves it:
    #
    #     2.31056*(34.64286*34.64286) = 2772.967171682305
    #    (2.31056*34.64286)*34.64286  = 2772.9671716823045
    #
    # -- 1 ULP, and the probe compares fields for exact equality.
    files['assoc_rgn2k.IN'] = sub(base, 'VS_Rgn2K', '2.31056')

    # ------------------------------------------------------------------- 14
    # Ind_BldPitch WITH A ZERO IN IT. Round 2 has (2,2,2) and (2,3,4); both make
    # all three `Ind_BldPitch(i) > 0` tests TRUE, so an index_offset mutant that
    # reads a NEIGHBOUR reads another positive number and nothing moves. A zero
    # in slot 1 separates them, and the duplicate-index tests then compare a
    # zero against a non-zero rather than two equal non-zeros.
    #     OL_Count = 1 + 0(bp1) + 1(bp2) + 1(bp3) + 1(GenTq) = 4.
    files['bp_zero_first.IN'] = ol(base, OL_Mode=1, Ind_BldPitch='0 3 4',
                                   Ind_GenTq='2', Ind_YawRate='0',
                                   Ind_Azimuth='0', Ind_R_Speed='0',
                                   Ind_R_Torque='0', Ind_R_Pitch='0',
                                   Ind_CableControl='0', Ind_StructControl='0')

    # ---------------------------------------------------------------- 15-16
    # TWO CABLE CHANNELS, AND TWO STRUCTURAL ONES. Round 2's `ol_cc_stc` has
    # exactly ONE of each, so `I` never leaves 1 -- and at I == 1, `I - 1` and
    # `1 - I` are the same subscript. Eight `swap_operands` survivors and the
    # two `I_OL = I_OL + 1` counters live in those two loops.
    #     OL_Count = 1 + 1(BldPitch, all duplicates) + 2(cables) = 4.
    c = ol(base, OL_Mode=1, Ind_BldPitch='2 2 2',
           Ind_GenTq='0', Ind_YawRate='0', Ind_Azimuth='0',
           Ind_R_Speed='0', Ind_R_Torque='0', Ind_R_Pitch='0',
           Ind_CableControl='3 4', Ind_StructControl='0')
    c = sub(c, 'CC_Mode', '2')
    c = sub(c, 'CC_Group_N', '2')
    c = sub(c, 'CC_GroupIndex', '1 2')
    files['cc2.IN'] = c

    s = ol(base, OL_Mode=1, Ind_BldPitch='2 2 2',
           Ind_GenTq='0', Ind_YawRate='0', Ind_Azimuth='0',
           Ind_R_Speed='0', Ind_R_Torque='0', Ind_R_Pitch='0',
           Ind_CableControl='0', Ind_StructControl='3 4')
    s = sub(s, 'StC_Mode', '2')
    s = sub(s, 'StC_Group_N', '2')
    s = sub(s, 'StC_GroupIndex', '1 2')
    files['stc2.IN'] = s

    # ---------------------------------------------------------------- 17-18
    # THE TWO SHAPES P13's OWN DOCSTRING NAMES: a CRLF file and a file with no
    # trailing newline. `two parsers of that kind agree on all fourteen real
    # input files and diverge on a tab, a CRLF, a missing trailing newline`.
    # The translation carries an explicit `if (!cur.empty() && cur.back() ==
    # '\r') cur.pop_back();` on both of its record boundaries and an
    # `if (any)` flush for a last record with no newline; nothing in rounds 1-3
    # reaches either, and four survivors sit on those three lines.
    #
    # These are BYTE transforms, so they are written from the file rather than
    # from the line list.
    text = BASE.read_text()
    raw['crlf.IN'] = text.replace('\n', '\r\n')
    raw['noeol.IN'] = text.rstrip('\n')

    for name, lines in sorted(files.items()):
        p = OUT / name
        p.write_text('\n'.join(lines))
        if len(lines) == len(base):
            nd = sum(1 for a, b in zip(base, lines) if a != b)
            how = '%d line(s) edited in place' % nd
        else:
            how = '%d line(s) removed' % (len(base) - len(lines))
        print('%-24s %4d lines, %s' % (name, len(lines), how))
    for name, blob in sorted(raw.items()):
        (OUT / name).write_text(blob, newline='')
        print('%-24s %4d bytes, byte transform of Examples/DISCON.IN'
              % (name, len(blob)))


if __name__ == '__main__':
    sys.exit(main())
