! GENERATED by evidence/ReadControlParameterFileSub/gen_probe.py -- do not edit.
!
! A standalone differential probe: run the Fortran reference and the C++
! translation over the SAME real DISCON.IN and compare every component of
! TYPE(ControlParameters). See the generator's docstring for what this is and,
! more importantly, what it is not.
!
!   ./vit_rcpfs_probe <DISCON.IN> [<DISCON.IN> ...]
!
PROGRAM vit_rcpfs_probe
    USE, INTRINSIC :: ISO_C_BINDING
    USE ROSCO_Types
    USE ReadSetParameters, ONLY : ReadControlParameterFileSub
    USE vit_controlparameters_view
    USE vit_localvariables_view
    USE vit_errorvariables_view
    IMPLICIT NONE

    INTERFACE
        SUBROUTINE readcontrolparameterfilesub_c(CntrPar, LocalVar, accINFILE, &
                accINFILE_size, RootName, ErrVar) BIND(C, NAME='readcontrolparameterfilesub_c')
            USE, INTRINSIC :: ISO_C_BINDING
            TYPE(C_PTR), VALUE :: CntrPar
            TYPE(C_PTR), VALUE :: LocalVar
            CHARACTER(KIND=C_CHAR) :: accINFILE(*)
            INTEGER(C_INT), VALUE :: accINFILE_size
            CHARACTER(KIND=C_CHAR) :: RootName(*)
            TYPE(C_PTR), VALUE :: ErrVar
        END SUBROUTINE
    END INTERFACE

    TYPE(ControlParameters), TARGET :: ref, cpp
    TYPE(LocalVariables),    TARGET :: lv_ref, lv_cpp
    TYPE(ErrorVariables),    TARGET :: ev_ref, ev_cpp
    TYPE(controlparameters_view_t), TARGET :: cv
    TYPE(localvariables_view_t),    TARGET :: lvv
    TYPE(errorvariables_view_t),    TARGET :: evv

    INTEGER :: nargs, iarg, n, i, nbad, nart, total_bad, total_art, total_cases
    ! ONE blank, used to empty BOTH sides. TYPE(ControlParameters) has
    ! components with no default initialisation -- WE_CP_n is one -- and the
    ! reference assigns neither, so their value is whatever the storage held.
    ! Two separate blanks make that garbage DIFFER and the probe reports a
    ! difference in a field NEITHER side wrote. Sharing one blank makes the
    ! undefined fields identical on both sides, which is the only way this
    ! probe can be about the two implementations rather than about the stack.
    TYPE(ControlParameters), SAVE :: blank
    CHARACTER(1024) :: path
    CHARACTER(:), ALLOCATABLE :: acc(:)
    CHARACTER(:), ALLOCATABLE :: root
    CHARACTER(KIND=C_CHAR), ALLOCATABLE :: acc_c(:), root_c(:)
    CHARACTER(256) :: current

    total_bad = 0
    total_art = 0
    total_cases = 0
    nargs = COMMAND_ARGUMENT_COUNT()
    IF (nargs == 0) THEN
        PRINT *, 'usage: vit_rcpfs_probe <DISCON.IN> [...]'
        STOP 2
    END IF

    DO iarg = 1, nargs
        CALL GET_COMMAND_ARGUMENT(iarg, path)
        current = path(1:MIN(256, LEN_TRIM(path)))
        nbad = 0
        nart = 0
        n = LEN_TRIM(path)

        ! accINFILE is CHARACTER(accINFILE_size), DIMENSION(accINFILE_size) and
        ! every use in the reference is accINFILE(1). RootName is the same width.
        ALLOCATE(CHARACTER(n) :: acc(n))
        DO i = 1, n
            acc(i) = ' '
        END DO
        acc(1) = path(1:n)
        ALLOCATE(CHARACTER(n) :: root)
        root = path(1:n)

        ! ---- the REFERENCE -------------------------------------------------
        CALL init_local(lv_ref)
        CALL init_err(ev_ref)
        CALL wipe(ref)
        CALL ReadControlParameterFileSub(ref, lv_ref, acc, n, root, ev_ref)

        ! ---- the TRANSLATION -----------------------------------------------
        CALL init_local(lv_cpp)
        CALL init_err(ev_cpp)
        CALL wipe(cpp)
        CALL vit_populate_controlparameters(cpp, cv)
        CALL vit_populate_localvariables(lv_cpp, lvv)
        CALL vit_populate_errorvariables(ev_cpp, evv)
        ALLOCATE(acc_c(n * n), root_c(n))
        DO i = 1, n * n
            acc_c(i) = ' '
        END DO
        DO i = 1, n
            acc_c(i) = path(i:i)
            root_c(i) = path(i:i)
        END DO
        CALL readcontrolparameterfilesub_c(C_LOC(cv), C_LOC(lvv), acc_c, n, root_c, C_LOC(evv))
        CALL vit_view_in_controlparameters(cv, cpp)
        CALL vit_copy_scalars_to_errorvariables(evv, ev_cpp)
        DEALLOCATE(acc_c, root_c)

        ! ---- compare -------------------------------------------------------
        IF (ev_ref%aviFAIL /= ev_cpp%aviFAIL) CALL bad("ErrVar%aviFAIL", "value differs")
        IF (ALLOCATED(ev_ref%ErrMsg) .NEQV. ALLOCATED(ev_cpp%ErrMsg)) THEN
            CALL bad("ErrVar%ErrMsg", "ALLOCATED differs")
        ELSE IF (ALLOCATED(ev_ref%ErrMsg)) THEN
            IF (ev_ref%ErrMsg /= ev_cpp%ErrMsg) CALL bad("ErrVar%ErrMsg", "value differs")
        END IF

    IF (ref%ZMQ_ID /= cpp%ZMQ_ID) CALL bad("ZMQ_ID", "value differs")
    IF (ref%LoggingLevel /= cpp%LoggingLevel) CALL bad("LoggingLevel", "value differs")
    IF (ref%Echo /= cpp%Echo) CALL bad("Echo", "value differs")
    IF (ref%Ext_Interface /= cpp%Ext_Interface) CALL bad("Ext_Interface", "value differs")
    IF (ref%DT_Out /= cpp%DT_Out) CALL bad("DT_Out", "value differs")
    IF (ref%n_DT_Out /= cpp%n_DT_Out) CALL bad("n_DT_Out", "value differs")
    IF (ref%n_DT_ZMQ /= cpp%n_DT_ZMQ) CALL bad("n_DT_ZMQ", "value differs")
    IF (ref%F_LPFType /= cpp%F_LPFType) CALL bad("F_LPFType", "value differs")
    IF (ref%F_LPFCornerFreq /= cpp%F_LPFCornerFreq) CALL bad("F_LPFCornerFreq", "value differs")
    IF (ref%F_LPFDamping /= cpp%F_LPFDamping) CALL bad("F_LPFDamping", "value differs")
    IF (ref%F_NumNotchFilts /= cpp%F_NumNotchFilts) CALL bad("F_NumNotchFilts", "value differs")
    IF (ref%F_GenSpdNotch_N /= cpp%F_GenSpdNotch_N) CALL bad("F_GenSpdNotch_N", "value differs")
    IF (ALLOCATED(ref%F_GenSpdNotch_Ind) .NEQV. ALLOCATED(cpp%F_GenSpdNotch_Ind)) THEN
        IF ((.NOT. ALLOCATED(ref%F_GenSpdNotch_Ind)) .AND. SIZE(cpp%F_GenSpdNotch_Ind) == 0) THEN
            CALL artifact("F_GenSpdNotch_Ind")
        ELSE
            CALL bad("F_GenSpdNotch_Ind", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%F_GenSpdNotch_Ind)) THEN
        IF (ANY(SHAPE(ref%F_GenSpdNotch_Ind) /= SHAPE(cpp%F_GenSpdNotch_Ind))) THEN
            CALL bad("F_GenSpdNotch_Ind", "SHAPE differs")
        ELSE IF (SIZE(ref%F_GenSpdNotch_Ind) > 0) THEN
            IF (ANY(ref%F_GenSpdNotch_Ind /= cpp%F_GenSpdNotch_Ind)) CALL bad("F_GenSpdNotch_Ind", "value differs")
        END IF
    END IF
    IF (ref%F_TwrTopNotch_N /= cpp%F_TwrTopNotch_N) CALL bad("F_TwrTopNotch_N", "value differs")
    IF (ALLOCATED(ref%F_TwrTopNotch_Ind) .NEQV. ALLOCATED(cpp%F_TwrTopNotch_Ind)) THEN
        IF ((.NOT. ALLOCATED(ref%F_TwrTopNotch_Ind)) .AND. SIZE(cpp%F_TwrTopNotch_Ind) == 0) THEN
            CALL artifact("F_TwrTopNotch_Ind")
        ELSE
            CALL bad("F_TwrTopNotch_Ind", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%F_TwrTopNotch_Ind)) THEN
        IF (ANY(SHAPE(ref%F_TwrTopNotch_Ind) /= SHAPE(cpp%F_TwrTopNotch_Ind))) THEN
            CALL bad("F_TwrTopNotch_Ind", "SHAPE differs")
        ELSE IF (SIZE(ref%F_TwrTopNotch_Ind) > 0) THEN
            IF (ANY(ref%F_TwrTopNotch_Ind /= cpp%F_TwrTopNotch_Ind)) CALL bad("F_TwrTopNotch_Ind", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%F_NotchFreqs) .NEQV. ALLOCATED(cpp%F_NotchFreqs)) THEN
        IF ((.NOT. ALLOCATED(ref%F_NotchFreqs)) .AND. SIZE(cpp%F_NotchFreqs) == 0) THEN
            CALL artifact("F_NotchFreqs")
        ELSE
            CALL bad("F_NotchFreqs", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%F_NotchFreqs)) THEN
        IF (ANY(SHAPE(ref%F_NotchFreqs) /= SHAPE(cpp%F_NotchFreqs))) THEN
            CALL bad("F_NotchFreqs", "SHAPE differs")
        ELSE IF (SIZE(ref%F_NotchFreqs) > 0) THEN
            IF (ANY(ref%F_NotchFreqs /= cpp%F_NotchFreqs)) CALL bad("F_NotchFreqs", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%F_NotchBetaNum) .NEQV. ALLOCATED(cpp%F_NotchBetaNum)) THEN
        IF ((.NOT. ALLOCATED(ref%F_NotchBetaNum)) .AND. SIZE(cpp%F_NotchBetaNum) == 0) THEN
            CALL artifact("F_NotchBetaNum")
        ELSE
            CALL bad("F_NotchBetaNum", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%F_NotchBetaNum)) THEN
        IF (ANY(SHAPE(ref%F_NotchBetaNum) /= SHAPE(cpp%F_NotchBetaNum))) THEN
            CALL bad("F_NotchBetaNum", "SHAPE differs")
        ELSE IF (SIZE(ref%F_NotchBetaNum) > 0) THEN
            IF (ANY(ref%F_NotchBetaNum /= cpp%F_NotchBetaNum)) CALL bad("F_NotchBetaNum", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%F_NotchBetaDen) .NEQV. ALLOCATED(cpp%F_NotchBetaDen)) THEN
        IF ((.NOT. ALLOCATED(ref%F_NotchBetaDen)) .AND. SIZE(cpp%F_NotchBetaDen) == 0) THEN
            CALL artifact("F_NotchBetaDen")
        ELSE
            CALL bad("F_NotchBetaDen", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%F_NotchBetaDen)) THEN
        IF (ANY(SHAPE(ref%F_NotchBetaDen) /= SHAPE(cpp%F_NotchBetaDen))) THEN
            CALL bad("F_NotchBetaDen", "SHAPE differs")
        ELSE IF (SIZE(ref%F_NotchBetaDen) > 0) THEN
            IF (ANY(ref%F_NotchBetaDen /= cpp%F_NotchBetaDen)) CALL bad("F_NotchBetaDen", "value differs")
        END IF
    END IF
    IF (ref%F_SSCornerFreq /= cpp%F_SSCornerFreq) CALL bad("F_SSCornerFreq", "value differs")
    IF (ref%F_WECornerFreq /= cpp%F_WECornerFreq) CALL bad("F_WECornerFreq", "value differs")
    IF (ALLOCATED(ref%F_FlCornerFreq) .NEQV. ALLOCATED(cpp%F_FlCornerFreq)) THEN
        IF ((.NOT. ALLOCATED(ref%F_FlCornerFreq)) .AND. SIZE(cpp%F_FlCornerFreq) == 0) THEN
            CALL artifact("F_FlCornerFreq")
        ELSE
            CALL bad("F_FlCornerFreq", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%F_FlCornerFreq)) THEN
        IF (ANY(SHAPE(ref%F_FlCornerFreq) /= SHAPE(cpp%F_FlCornerFreq))) THEN
            CALL bad("F_FlCornerFreq", "SHAPE differs")
        ELSE IF (SIZE(ref%F_FlCornerFreq) > 0) THEN
            IF (ANY(ref%F_FlCornerFreq /= cpp%F_FlCornerFreq)) CALL bad("F_FlCornerFreq", "value differs")
        END IF
    END IF
    IF (ref%F_FlHighPassFreq /= cpp%F_FlHighPassFreq) CALL bad("F_FlHighPassFreq", "value differs")
    IF (ref%F_YawErr /= cpp%F_YawErr) CALL bad("F_YawErr", "value differs")
    IF (ALLOCATED(ref%F_FlpCornerFreq) .NEQV. ALLOCATED(cpp%F_FlpCornerFreq)) THEN
        IF ((.NOT. ALLOCATED(ref%F_FlpCornerFreq)) .AND. SIZE(cpp%F_FlpCornerFreq) == 0) THEN
            CALL artifact("F_FlpCornerFreq")
        ELSE
            CALL bad("F_FlpCornerFreq", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%F_FlpCornerFreq)) THEN
        IF (ANY(SHAPE(ref%F_FlpCornerFreq) /= SHAPE(cpp%F_FlpCornerFreq))) THEN
            CALL bad("F_FlpCornerFreq", "SHAPE differs")
        ELSE IF (SIZE(ref%F_FlpCornerFreq) > 0) THEN
            IF (ANY(ref%F_FlpCornerFreq /= cpp%F_FlpCornerFreq)) CALL bad("F_FlpCornerFreq", "value differs")
        END IF
    END IF
    IF (ref%F_VSRefSpdCornerFreq /= cpp%F_VSRefSpdCornerFreq) CALL bad("F_VSRefSpdCornerFreq", "value differs")
    IF (ref%TRA_Mode /= cpp%TRA_Mode) CALL bad("TRA_Mode", "value differs")
    IF (ref%TRA_ExclSpeed /= cpp%TRA_ExclSpeed) CALL bad("TRA_ExclSpeed", "value differs")
    IF (ref%TRA_ExclBand /= cpp%TRA_ExclBand) CALL bad("TRA_ExclBand", "value differs")
    IF (ref%TRA_RateLimit /= cpp%TRA_RateLimit) CALL bad("TRA_RateLimit", "value differs")
    IF (ref%TD_Mode /= cpp%TD_Mode) CALL bad("TD_Mode", "value differs")
    IF (ref%FA_HPFCornerFreq /= cpp%FA_HPFCornerFreq) CALL bad("FA_HPFCornerFreq", "value differs")
    IF (ref%FA_IntSat /= cpp%FA_IntSat) CALL bad("FA_IntSat", "value differs")
    IF (ref%FA_KI /= cpp%FA_KI) CALL bad("FA_KI", "value differs")
    IF (ref%IPC_ControlMode /= cpp%IPC_ControlMode) CALL bad("IPC_ControlMode", "value differs")
    IF (ALLOCATED(ref%IPC_Vramp) .NEQV. ALLOCATED(cpp%IPC_Vramp)) THEN
        IF ((.NOT. ALLOCATED(ref%IPC_Vramp)) .AND. SIZE(cpp%IPC_Vramp) == 0) THEN
            CALL artifact("IPC_Vramp")
        ELSE
            CALL bad("IPC_Vramp", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%IPC_Vramp)) THEN
        IF (ANY(SHAPE(ref%IPC_Vramp) /= SHAPE(cpp%IPC_Vramp))) THEN
            CALL bad("IPC_Vramp", "SHAPE differs")
        ELSE IF (SIZE(ref%IPC_Vramp) > 0) THEN
            IF (ANY(ref%IPC_Vramp /= cpp%IPC_Vramp)) CALL bad("IPC_Vramp", "value differs")
        END IF
    END IF
    IF (ref%IPC_IntSat /= cpp%IPC_IntSat) CALL bad("IPC_IntSat", "value differs")
    IF (ref%IPC_SatMode /= cpp%IPC_SatMode) CALL bad("IPC_SatMode", "value differs")
    IF (ALLOCATED(ref%IPC_KP) .NEQV. ALLOCATED(cpp%IPC_KP)) THEN
        IF ((.NOT. ALLOCATED(ref%IPC_KP)) .AND. SIZE(cpp%IPC_KP) == 0) THEN
            CALL artifact("IPC_KP")
        ELSE
            CALL bad("IPC_KP", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%IPC_KP)) THEN
        IF (ANY(SHAPE(ref%IPC_KP) /= SHAPE(cpp%IPC_KP))) THEN
            CALL bad("IPC_KP", "SHAPE differs")
        ELSE IF (SIZE(ref%IPC_KP) > 0) THEN
            IF (ANY(ref%IPC_KP /= cpp%IPC_KP)) CALL bad("IPC_KP", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%IPC_KI) .NEQV. ALLOCATED(cpp%IPC_KI)) THEN
        IF ((.NOT. ALLOCATED(ref%IPC_KI)) .AND. SIZE(cpp%IPC_KI) == 0) THEN
            CALL artifact("IPC_KI")
        ELSE
            CALL bad("IPC_KI", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%IPC_KI)) THEN
        IF (ANY(SHAPE(ref%IPC_KI) /= SHAPE(cpp%IPC_KI))) THEN
            CALL bad("IPC_KI", "SHAPE differs")
        ELSE IF (SIZE(ref%IPC_KI) > 0) THEN
            IF (ANY(ref%IPC_KI /= cpp%IPC_KI)) CALL bad("IPC_KI", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%IPC_aziOffset) .NEQV. ALLOCATED(cpp%IPC_aziOffset)) THEN
        IF ((.NOT. ALLOCATED(ref%IPC_aziOffset)) .AND. SIZE(cpp%IPC_aziOffset) == 0) THEN
            CALL artifact("IPC_aziOffset")
        ELSE
            CALL bad("IPC_aziOffset", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%IPC_aziOffset)) THEN
        IF (ANY(SHAPE(ref%IPC_aziOffset) /= SHAPE(cpp%IPC_aziOffset))) THEN
            CALL bad("IPC_aziOffset", "SHAPE differs")
        ELSE IF (SIZE(ref%IPC_aziOffset) > 0) THEN
            IF (ANY(ref%IPC_aziOffset /= cpp%IPC_aziOffset)) CALL bad("IPC_aziOffset", "value differs")
        END IF
    END IF
    IF (ref%IPC_CornerFreqAct /= cpp%IPC_CornerFreqAct) CALL bad("IPC_CornerFreqAct", "value differs")
    IF (ref%PC_ControlMode /= cpp%PC_ControlMode) CALL bad("PC_ControlMode", "value differs")
    IF (ref%PC_GS_n /= cpp%PC_GS_n) CALL bad("PC_GS_n", "value differs")
    IF (ALLOCATED(ref%PC_GS_angles) .NEQV. ALLOCATED(cpp%PC_GS_angles)) THEN
        IF ((.NOT. ALLOCATED(ref%PC_GS_angles)) .AND. SIZE(cpp%PC_GS_angles) == 0) THEN
            CALL artifact("PC_GS_angles")
        ELSE
            CALL bad("PC_GS_angles", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%PC_GS_angles)) THEN
        IF (ANY(SHAPE(ref%PC_GS_angles) /= SHAPE(cpp%PC_GS_angles))) THEN
            CALL bad("PC_GS_angles", "SHAPE differs")
        ELSE IF (SIZE(ref%PC_GS_angles) > 0) THEN
            IF (ANY(ref%PC_GS_angles /= cpp%PC_GS_angles)) CALL bad("PC_GS_angles", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%PC_GS_KP) .NEQV. ALLOCATED(cpp%PC_GS_KP)) THEN
        IF ((.NOT. ALLOCATED(ref%PC_GS_KP)) .AND. SIZE(cpp%PC_GS_KP) == 0) THEN
            CALL artifact("PC_GS_KP")
        ELSE
            CALL bad("PC_GS_KP", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%PC_GS_KP)) THEN
        IF (ANY(SHAPE(ref%PC_GS_KP) /= SHAPE(cpp%PC_GS_KP))) THEN
            CALL bad("PC_GS_KP", "SHAPE differs")
        ELSE IF (SIZE(ref%PC_GS_KP) > 0) THEN
            IF (ANY(ref%PC_GS_KP /= cpp%PC_GS_KP)) CALL bad("PC_GS_KP", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%PC_GS_KI) .NEQV. ALLOCATED(cpp%PC_GS_KI)) THEN
        IF ((.NOT. ALLOCATED(ref%PC_GS_KI)) .AND. SIZE(cpp%PC_GS_KI) == 0) THEN
            CALL artifact("PC_GS_KI")
        ELSE
            CALL bad("PC_GS_KI", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%PC_GS_KI)) THEN
        IF (ANY(SHAPE(ref%PC_GS_KI) /= SHAPE(cpp%PC_GS_KI))) THEN
            CALL bad("PC_GS_KI", "SHAPE differs")
        ELSE IF (SIZE(ref%PC_GS_KI) > 0) THEN
            IF (ANY(ref%PC_GS_KI /= cpp%PC_GS_KI)) CALL bad("PC_GS_KI", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%PC_GS_KD) .NEQV. ALLOCATED(cpp%PC_GS_KD)) THEN
        IF ((.NOT. ALLOCATED(ref%PC_GS_KD)) .AND. SIZE(cpp%PC_GS_KD) == 0) THEN
            CALL artifact("PC_GS_KD")
        ELSE
            CALL bad("PC_GS_KD", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%PC_GS_KD)) THEN
        IF (ANY(SHAPE(ref%PC_GS_KD) /= SHAPE(cpp%PC_GS_KD))) THEN
            CALL bad("PC_GS_KD", "SHAPE differs")
        ELSE IF (SIZE(ref%PC_GS_KD) > 0) THEN
            IF (ANY(ref%PC_GS_KD /= cpp%PC_GS_KD)) CALL bad("PC_GS_KD", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%PC_GS_TF) .NEQV. ALLOCATED(cpp%PC_GS_TF)) THEN
        IF ((.NOT. ALLOCATED(ref%PC_GS_TF)) .AND. SIZE(cpp%PC_GS_TF) == 0) THEN
            CALL artifact("PC_GS_TF")
        ELSE
            CALL bad("PC_GS_TF", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%PC_GS_TF)) THEN
        IF (ANY(SHAPE(ref%PC_GS_TF) /= SHAPE(cpp%PC_GS_TF))) THEN
            CALL bad("PC_GS_TF", "SHAPE differs")
        ELSE IF (SIZE(ref%PC_GS_TF) > 0) THEN
            IF (ANY(ref%PC_GS_TF /= cpp%PC_GS_TF)) CALL bad("PC_GS_TF", "value differs")
        END IF
    END IF
    IF (ref%PC_MaxPit /= cpp%PC_MaxPit) CALL bad("PC_MaxPit", "value differs")
    IF (ref%PC_MinPit /= cpp%PC_MinPit) CALL bad("PC_MinPit", "value differs")
    IF (ref%PC_MaxRat /= cpp%PC_MaxRat) CALL bad("PC_MaxRat", "value differs")
    IF (ref%PC_MinRat /= cpp%PC_MinRat) CALL bad("PC_MinRat", "value differs")
    IF (ref%PC_RefSpd /= cpp%PC_RefSpd) CALL bad("PC_RefSpd", "value differs")
    IF (ref%PC_FinePit /= cpp%PC_FinePit) CALL bad("PC_FinePit", "value differs")
    IF (ref%PC_Switch /= cpp%PC_Switch) CALL bad("PC_Switch", "value differs")
    IF (ref%VS_ControlMode /= cpp%VS_ControlMode) CALL bad("VS_ControlMode", "value differs")
    IF (ref%VS_ConstPower /= cpp%VS_ConstPower) CALL bad("VS_ConstPower", "value differs")
    IF (ref%VS_FBP /= cpp%VS_FBP) CALL bad("VS_FBP", "value differs")
    IF (ref%VS_GenEff /= cpp%VS_GenEff) CALL bad("VS_GenEff", "value differs")
    IF (ref%VS_ArSatTq /= cpp%VS_ArSatTq) CALL bad("VS_ArSatTq", "value differs")
    IF (ref%VS_MaxRat /= cpp%VS_MaxRat) CALL bad("VS_MaxRat", "value differs")
    IF (ref%VS_MaxTq /= cpp%VS_MaxTq) CALL bad("VS_MaxTq", "value differs")
    IF (ref%VS_MinTq /= cpp%VS_MinTq) CALL bad("VS_MinTq", "value differs")
    IF (ref%VS_MinOMSpd /= cpp%VS_MinOMSpd) CALL bad("VS_MinOMSpd", "value differs")
    IF (ref%VS_Rgn2K /= cpp%VS_Rgn2K) CALL bad("VS_Rgn2K", "value differs")
    IF (ref%VS_RtPwr /= cpp%VS_RtPwr) CALL bad("VS_RtPwr", "value differs")
    IF (ref%VS_RtTq /= cpp%VS_RtTq) CALL bad("VS_RtTq", "value differs")
    IF (ref%VS_RefSpd /= cpp%VS_RefSpd) CALL bad("VS_RefSpd", "value differs")
    IF (ref%VS_n /= cpp%VS_n) CALL bad("VS_n", "value differs")
    IF (ALLOCATED(ref%VS_KP) .NEQV. ALLOCATED(cpp%VS_KP)) THEN
        IF ((.NOT. ALLOCATED(ref%VS_KP)) .AND. SIZE(cpp%VS_KP) == 0) THEN
            CALL artifact("VS_KP")
        ELSE
            CALL bad("VS_KP", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%VS_KP)) THEN
        IF (ANY(SHAPE(ref%VS_KP) /= SHAPE(cpp%VS_KP))) THEN
            CALL bad("VS_KP", "SHAPE differs")
        ELSE IF (SIZE(ref%VS_KP) > 0) THEN
            IF (ANY(ref%VS_KP /= cpp%VS_KP)) CALL bad("VS_KP", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%VS_KI) .NEQV. ALLOCATED(cpp%VS_KI)) THEN
        IF ((.NOT. ALLOCATED(ref%VS_KI)) .AND. SIZE(cpp%VS_KI) == 0) THEN
            CALL artifact("VS_KI")
        ELSE
            CALL bad("VS_KI", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%VS_KI)) THEN
        IF (ANY(SHAPE(ref%VS_KI) /= SHAPE(cpp%VS_KI))) THEN
            CALL bad("VS_KI", "SHAPE differs")
        ELSE IF (SIZE(ref%VS_KI) > 0) THEN
            IF (ANY(ref%VS_KI /= cpp%VS_KI)) CALL bad("VS_KI", "value differs")
        END IF
    END IF
    IF (ref%VS_TSRopt /= cpp%VS_TSRopt) CALL bad("VS_TSRopt", "value differs")
    IF (ref%VS_FBP_n /= cpp%VS_FBP_n) CALL bad("VS_FBP_n", "value differs")
    IF (ALLOCATED(ref%VS_FBP_U) .NEQV. ALLOCATED(cpp%VS_FBP_U)) THEN
        IF ((.NOT. ALLOCATED(ref%VS_FBP_U)) .AND. SIZE(cpp%VS_FBP_U) == 0) THEN
            CALL artifact("VS_FBP_U")
        ELSE
            CALL bad("VS_FBP_U", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%VS_FBP_U)) THEN
        IF (ANY(SHAPE(ref%VS_FBP_U) /= SHAPE(cpp%VS_FBP_U))) THEN
            CALL bad("VS_FBP_U", "SHAPE differs")
        ELSE IF (SIZE(ref%VS_FBP_U) > 0) THEN
            IF (ANY(ref%VS_FBP_U /= cpp%VS_FBP_U)) CALL bad("VS_FBP_U", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%VS_FBP_Omega) .NEQV. ALLOCATED(cpp%VS_FBP_Omega)) THEN
        IF ((.NOT. ALLOCATED(ref%VS_FBP_Omega)) .AND. SIZE(cpp%VS_FBP_Omega) == 0) THEN
            CALL artifact("VS_FBP_Omega")
        ELSE
            CALL bad("VS_FBP_Omega", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%VS_FBP_Omega)) THEN
        IF (ANY(SHAPE(ref%VS_FBP_Omega) /= SHAPE(cpp%VS_FBP_Omega))) THEN
            CALL bad("VS_FBP_Omega", "SHAPE differs")
        ELSE IF (SIZE(ref%VS_FBP_Omega) > 0) THEN
            IF (ANY(ref%VS_FBP_Omega /= cpp%VS_FBP_Omega)) CALL bad("VS_FBP_Omega", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%VS_FBP_Tau) .NEQV. ALLOCATED(cpp%VS_FBP_Tau)) THEN
        IF ((.NOT. ALLOCATED(ref%VS_FBP_Tau)) .AND. SIZE(cpp%VS_FBP_Tau) == 0) THEN
            CALL artifact("VS_FBP_Tau")
        ELSE
            CALL bad("VS_FBP_Tau", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%VS_FBP_Tau)) THEN
        IF (ANY(SHAPE(ref%VS_FBP_Tau) /= SHAPE(cpp%VS_FBP_Tau))) THEN
            CALL bad("VS_FBP_Tau", "SHAPE differs")
        ELSE IF (SIZE(ref%VS_FBP_Tau) > 0) THEN
            IF (ANY(ref%VS_FBP_Tau /= cpp%VS_FBP_Tau)) CALL bad("VS_FBP_Tau", "value differs")
        END IF
    END IF
    IF (ref%SS_Mode /= cpp%SS_Mode) CALL bad("SS_Mode", "value differs")
    IF (ref%SS_VSGain /= cpp%SS_VSGain) CALL bad("SS_VSGain", "value differs")
    IF (ref%SS_PCGain /= cpp%SS_PCGain) CALL bad("SS_PCGain", "value differs")
    IF (ref%PRC_Mode /= cpp%PRC_Mode) CALL bad("PRC_Mode", "value differs")
    IF (ref%PRC_Comm /= cpp%PRC_Comm) CALL bad("PRC_Comm", "value differs")
    IF (ALLOCATED(ref%PRC_WindSpeeds) .NEQV. ALLOCATED(cpp%PRC_WindSpeeds)) THEN
        IF ((.NOT. ALLOCATED(ref%PRC_WindSpeeds)) .AND. SIZE(cpp%PRC_WindSpeeds) == 0) THEN
            CALL artifact("PRC_WindSpeeds")
        ELSE
            CALL bad("PRC_WindSpeeds", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%PRC_WindSpeeds)) THEN
        IF (ANY(SHAPE(ref%PRC_WindSpeeds) /= SHAPE(cpp%PRC_WindSpeeds))) THEN
            CALL bad("PRC_WindSpeeds", "SHAPE differs")
        ELSE IF (SIZE(ref%PRC_WindSpeeds) > 0) THEN
            IF (ANY(ref%PRC_WindSpeeds /= cpp%PRC_WindSpeeds)) CALL bad("PRC_WindSpeeds", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%PRC_GenSpeeds) .NEQV. ALLOCATED(cpp%PRC_GenSpeeds)) THEN
        IF ((.NOT. ALLOCATED(ref%PRC_GenSpeeds)) .AND. SIZE(cpp%PRC_GenSpeeds) == 0) THEN
            CALL artifact("PRC_GenSpeeds")
        ELSE
            CALL bad("PRC_GenSpeeds", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%PRC_GenSpeeds)) THEN
        IF (ANY(SHAPE(ref%PRC_GenSpeeds) /= SHAPE(cpp%PRC_GenSpeeds))) THEN
            CALL bad("PRC_GenSpeeds", "SHAPE differs")
        ELSE IF (SIZE(ref%PRC_GenSpeeds) > 0) THEN
            IF (ANY(ref%PRC_GenSpeeds /= cpp%PRC_GenSpeeds)) CALL bad("PRC_GenSpeeds", "value differs")
        END IF
    END IF
    IF (ref%PRC_n /= cpp%PRC_n) CALL bad("PRC_n", "value differs")
    IF (ref%PRC_LPF_Freq /= cpp%PRC_LPF_Freq) CALL bad("PRC_LPF_Freq", "value differs")
    IF (ref%PRC_R_Torque /= cpp%PRC_R_Torque) CALL bad("PRC_R_Torque", "value differs")
    IF (ref%PRC_R_Speed /= cpp%PRC_R_Speed) CALL bad("PRC_R_Speed", "value differs")
    IF (ref%PRC_R_Pitch /= cpp%PRC_R_Pitch) CALL bad("PRC_R_Pitch", "value differs")
    IF (ref%PRC_Table_n /= cpp%PRC_Table_n) CALL bad("PRC_Table_n", "value differs")
    IF (ALLOCATED(ref%PRC_Pitch_Table) .NEQV. ALLOCATED(cpp%PRC_Pitch_Table)) THEN
        IF ((.NOT. ALLOCATED(ref%PRC_Pitch_Table)) .AND. SIZE(cpp%PRC_Pitch_Table) == 0) THEN
            CALL artifact("PRC_Pitch_Table")
        ELSE
            CALL bad("PRC_Pitch_Table", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%PRC_Pitch_Table)) THEN
        IF (ANY(SHAPE(ref%PRC_Pitch_Table) /= SHAPE(cpp%PRC_Pitch_Table))) THEN
            CALL bad("PRC_Pitch_Table", "SHAPE differs")
        ELSE IF (SIZE(ref%PRC_Pitch_Table) > 0) THEN
            IF (ANY(ref%PRC_Pitch_Table /= cpp%PRC_Pitch_Table)) CALL bad("PRC_Pitch_Table", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%PRC_R_Table) .NEQV. ALLOCATED(cpp%PRC_R_Table)) THEN
        IF ((.NOT. ALLOCATED(ref%PRC_R_Table)) .AND. SIZE(cpp%PRC_R_Table) == 0) THEN
            CALL artifact("PRC_R_Table")
        ELSE
            CALL bad("PRC_R_Table", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%PRC_R_Table)) THEN
        IF (ANY(SHAPE(ref%PRC_R_Table) /= SHAPE(cpp%PRC_R_Table))) THEN
            CALL bad("PRC_R_Table", "SHAPE differs")
        ELSE IF (SIZE(ref%PRC_R_Table) > 0) THEN
            IF (ANY(ref%PRC_R_Table /= cpp%PRC_R_Table)) CALL bad("PRC_R_Table", "value differs")
        END IF
    END IF
    IF (ref%WE_Mode /= cpp%WE_Mode) CALL bad("WE_Mode", "value differs")
    IF (ref%WE_BladeRadius /= cpp%WE_BladeRadius) CALL bad("WE_BladeRadius", "value differs")
    IF (ref%WE_CP_n /= cpp%WE_CP_n) CALL bad("WE_CP_n", "value differs")
    IF (ALLOCATED(ref%WE_CP) .NEQV. ALLOCATED(cpp%WE_CP)) THEN
        IF ((.NOT. ALLOCATED(ref%WE_CP)) .AND. SIZE(cpp%WE_CP) == 0) THEN
            CALL artifact("WE_CP")
        ELSE
            CALL bad("WE_CP", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%WE_CP)) THEN
        IF (ANY(SHAPE(ref%WE_CP) /= SHAPE(cpp%WE_CP))) THEN
            CALL bad("WE_CP", "SHAPE differs")
        ELSE IF (SIZE(ref%WE_CP) > 0) THEN
            IF (ANY(ref%WE_CP /= cpp%WE_CP)) CALL bad("WE_CP", "value differs")
        END IF
    END IF
    IF (ref%WE_Gamma /= cpp%WE_Gamma) CALL bad("WE_Gamma", "value differs")
    IF (ref%WE_GearboxRatio /= cpp%WE_GearboxRatio) CALL bad("WE_GearboxRatio", "value differs")
    IF (ref%WE_Jtot /= cpp%WE_Jtot) CALL bad("WE_Jtot", "value differs")
    IF (ref%WE_RhoAir /= cpp%WE_RhoAir) CALL bad("WE_RhoAir", "value differs")
    IF (ref%PerfFileName /= cpp%PerfFileName) CALL bad("PerfFileName", "value differs")
    IF (ALLOCATED(ref%PerfTableSize) .NEQV. ALLOCATED(cpp%PerfTableSize)) THEN
        IF ((.NOT. ALLOCATED(ref%PerfTableSize)) .AND. SIZE(cpp%PerfTableSize) == 0) THEN
            CALL artifact("PerfTableSize")
        ELSE
            CALL bad("PerfTableSize", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%PerfTableSize)) THEN
        IF (ANY(SHAPE(ref%PerfTableSize) /= SHAPE(cpp%PerfTableSize))) THEN
            CALL bad("PerfTableSize", "SHAPE differs")
        ELSE IF (SIZE(ref%PerfTableSize) > 0) THEN
            IF (ANY(ref%PerfTableSize /= cpp%PerfTableSize)) CALL bad("PerfTableSize", "value differs")
        END IF
    END IF
    IF (ref%WE_FOPoles_N /= cpp%WE_FOPoles_N) CALL bad("WE_FOPoles_N", "value differs")
    IF (ALLOCATED(ref%WE_FOPoles_v) .NEQV. ALLOCATED(cpp%WE_FOPoles_v)) THEN
        IF ((.NOT. ALLOCATED(ref%WE_FOPoles_v)) .AND. SIZE(cpp%WE_FOPoles_v) == 0) THEN
            CALL artifact("WE_FOPoles_v")
        ELSE
            CALL bad("WE_FOPoles_v", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%WE_FOPoles_v)) THEN
        IF (ANY(SHAPE(ref%WE_FOPoles_v) /= SHAPE(cpp%WE_FOPoles_v))) THEN
            CALL bad("WE_FOPoles_v", "SHAPE differs")
        ELSE IF (SIZE(ref%WE_FOPoles_v) > 0) THEN
            IF (ANY(ref%WE_FOPoles_v /= cpp%WE_FOPoles_v)) CALL bad("WE_FOPoles_v", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%WE_FOPoles) .NEQV. ALLOCATED(cpp%WE_FOPoles)) THEN
        IF ((.NOT. ALLOCATED(ref%WE_FOPoles)) .AND. SIZE(cpp%WE_FOPoles) == 0) THEN
            CALL artifact("WE_FOPoles")
        ELSE
            CALL bad("WE_FOPoles", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%WE_FOPoles)) THEN
        IF (ANY(SHAPE(ref%WE_FOPoles) /= SHAPE(cpp%WE_FOPoles))) THEN
            CALL bad("WE_FOPoles", "SHAPE differs")
        ELSE IF (SIZE(ref%WE_FOPoles) > 0) THEN
            IF (ANY(ref%WE_FOPoles /= cpp%WE_FOPoles)) CALL bad("WE_FOPoles", "value differs")
        END IF
    END IF
    IF (ref%Y_ControlMode /= cpp%Y_ControlMode) CALL bad("Y_ControlMode", "value differs")
    IF (ref%Y_uSwitch /= cpp%Y_uSwitch) CALL bad("Y_uSwitch", "value differs")
    IF (ALLOCATED(ref%Y_ErrThresh) .NEQV. ALLOCATED(cpp%Y_ErrThresh)) THEN
        IF ((.NOT. ALLOCATED(ref%Y_ErrThresh)) .AND. SIZE(cpp%Y_ErrThresh) == 0) THEN
            CALL artifact("Y_ErrThresh")
        ELSE
            CALL bad("Y_ErrThresh", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%Y_ErrThresh)) THEN
        IF (ANY(SHAPE(ref%Y_ErrThresh) /= SHAPE(cpp%Y_ErrThresh))) THEN
            CALL bad("Y_ErrThresh", "SHAPE differs")
        ELSE IF (SIZE(ref%Y_ErrThresh) > 0) THEN
            IF (ANY(ref%Y_ErrThresh /= cpp%Y_ErrThresh)) CALL bad("Y_ErrThresh", "value differs")
        END IF
    END IF
    IF (ref%Y_Rate /= cpp%Y_Rate) CALL bad("Y_Rate", "value differs")
    IF (ref%Y_MErrSet /= cpp%Y_MErrSet) CALL bad("Y_MErrSet", "value differs")
    IF (ref%Y_IPC_IntSat /= cpp%Y_IPC_IntSat) CALL bad("Y_IPC_IntSat", "value differs")
    IF (ref%Y_IPC_KP /= cpp%Y_IPC_KP) CALL bad("Y_IPC_KP", "value differs")
    IF (ref%Y_IPC_KI /= cpp%Y_IPC_KI) CALL bad("Y_IPC_KI", "value differs")
    IF (ref%PS_Mode /= cpp%PS_Mode) CALL bad("PS_Mode", "value differs")
    IF (ref%PS_BldPitchMin_N /= cpp%PS_BldPitchMin_N) CALL bad("PS_BldPitchMin_N", "value differs")
    IF (ALLOCATED(ref%PS_WindSpeeds) .NEQV. ALLOCATED(cpp%PS_WindSpeeds)) THEN
        IF ((.NOT. ALLOCATED(ref%PS_WindSpeeds)) .AND. SIZE(cpp%PS_WindSpeeds) == 0) THEN
            CALL artifact("PS_WindSpeeds")
        ELSE
            CALL bad("PS_WindSpeeds", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%PS_WindSpeeds)) THEN
        IF (ANY(SHAPE(ref%PS_WindSpeeds) /= SHAPE(cpp%PS_WindSpeeds))) THEN
            CALL bad("PS_WindSpeeds", "SHAPE differs")
        ELSE IF (SIZE(ref%PS_WindSpeeds) > 0) THEN
            IF (ANY(ref%PS_WindSpeeds /= cpp%PS_WindSpeeds)) CALL bad("PS_WindSpeeds", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%PS_BldPitchMin) .NEQV. ALLOCATED(cpp%PS_BldPitchMin)) THEN
        IF ((.NOT. ALLOCATED(ref%PS_BldPitchMin)) .AND. SIZE(cpp%PS_BldPitchMin) == 0) THEN
            CALL artifact("PS_BldPitchMin")
        ELSE
            CALL bad("PS_BldPitchMin", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%PS_BldPitchMin)) THEN
        IF (ANY(SHAPE(ref%PS_BldPitchMin) /= SHAPE(cpp%PS_BldPitchMin))) THEN
            CALL bad("PS_BldPitchMin", "SHAPE differs")
        ELSE IF (SIZE(ref%PS_BldPitchMin) > 0) THEN
            IF (ANY(ref%PS_BldPitchMin /= cpp%PS_BldPitchMin)) CALL bad("PS_BldPitchMin", "value differs")
        END IF
    END IF
    IF (ref%SU_Mode /= cpp%SU_Mode) CALL bad("SU_Mode", "value differs")
    IF (ref%SU_StartTime /= cpp%SU_StartTime) CALL bad("SU_StartTime", "value differs")
    IF (ref%SU_FW_MinDuration /= cpp%SU_FW_MinDuration) CALL bad("SU_FW_MinDuration", "value differs")
    IF (ref%SU_RotorSpeedThresh /= cpp%SU_RotorSpeedThresh) CALL bad("SU_RotorSpeedThresh", "value differs")
    IF (ref%SU_RotorSpeedCornerFreq /= cpp%SU_RotorSpeedCornerFreq) CALL bad("SU_RotorSpeedCornerFreq", "value differs")
    IF (ref%SU_LoadStages_N /= cpp%SU_LoadStages_N) CALL bad("SU_LoadStages_N", "value differs")
    IF (ALLOCATED(ref%SU_LoadStages) .NEQV. ALLOCATED(cpp%SU_LoadStages)) THEN
        IF ((.NOT. ALLOCATED(ref%SU_LoadStages)) .AND. SIZE(cpp%SU_LoadStages) == 0) THEN
            CALL artifact("SU_LoadStages")
        ELSE
            CALL bad("SU_LoadStages", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%SU_LoadStages)) THEN
        IF (ANY(SHAPE(ref%SU_LoadStages) /= SHAPE(cpp%SU_LoadStages))) THEN
            CALL bad("SU_LoadStages", "SHAPE differs")
        ELSE IF (SIZE(ref%SU_LoadStages) > 0) THEN
            IF (ANY(ref%SU_LoadStages /= cpp%SU_LoadStages)) CALL bad("SU_LoadStages", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%SU_LoadRampDuration) .NEQV. ALLOCATED(cpp%SU_LoadRampDuration)) THEN
        IF ((.NOT. ALLOCATED(ref%SU_LoadRampDuration)) .AND. SIZE(cpp%SU_LoadRampDuration) == 0) THEN
            CALL artifact("SU_LoadRampDuration")
        ELSE
            CALL bad("SU_LoadRampDuration", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%SU_LoadRampDuration)) THEN
        IF (ANY(SHAPE(ref%SU_LoadRampDuration) /= SHAPE(cpp%SU_LoadRampDuration))) THEN
            CALL bad("SU_LoadRampDuration", "SHAPE differs")
        ELSE IF (SIZE(ref%SU_LoadRampDuration) > 0) THEN
            IF (ANY(ref%SU_LoadRampDuration /= cpp%SU_LoadRampDuration)) CALL bad("SU_LoadRampDuration", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%SU_LoadHoldDuration) .NEQV. ALLOCATED(cpp%SU_LoadHoldDuration)) THEN
        IF ((.NOT. ALLOCATED(ref%SU_LoadHoldDuration)) .AND. SIZE(cpp%SU_LoadHoldDuration) == 0) THEN
            CALL artifact("SU_LoadHoldDuration")
        ELSE
            CALL bad("SU_LoadHoldDuration", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%SU_LoadHoldDuration)) THEN
        IF (ANY(SHAPE(ref%SU_LoadHoldDuration) /= SHAPE(cpp%SU_LoadHoldDuration))) THEN
            CALL bad("SU_LoadHoldDuration", "SHAPE differs")
        ELSE IF (SIZE(ref%SU_LoadHoldDuration) > 0) THEN
            IF (ANY(ref%SU_LoadHoldDuration /= cpp%SU_LoadHoldDuration)) CALL bad("SU_LoadHoldDuration", "value differs")
        END IF
    END IF
    IF (ref%SD_Mode /= cpp%SD_Mode) CALL bad("SD_Mode", "value differs")
    IF (ref%SD_TimeActivate /= cpp%SD_TimeActivate) CALL bad("SD_TimeActivate", "value differs")
    IF (ref%SD_EnablePitch /= cpp%SD_EnablePitch) CALL bad("SD_EnablePitch", "value differs")
    IF (ref%SD_EnableYawError /= cpp%SD_EnableYawError) CALL bad("SD_EnableYawError", "value differs")
    IF (ref%SD_EnableGenSpeed /= cpp%SD_EnableGenSpeed) CALL bad("SD_EnableGenSpeed", "value differs")
    IF (ref%SD_EnableTime /= cpp%SD_EnableTime) CALL bad("SD_EnableTime", "value differs")
    IF (ref%SD_MaxPit /= cpp%SD_MaxPit) CALL bad("SD_MaxPit", "value differs")
    IF (ref%SD_PitchCornerFreq /= cpp%SD_PitchCornerFreq) CALL bad("SD_PitchCornerFreq", "value differs")
    IF (ref%SD_MaxYawError /= cpp%SD_MaxYawError) CALL bad("SD_MaxYawError", "value differs")
    IF (ref%SD_YawErrorCornerFreq /= cpp%SD_YawErrorCornerFreq) CALL bad("SD_YawErrorCornerFreq", "value differs")
    IF (ref%SD_MaxGenSpd /= cpp%SD_MaxGenSpd) CALL bad("SD_MaxGenSpd", "value differs")
    IF (ref%SD_GenSpdCornerFreq /= cpp%SD_GenSpdCornerFreq) CALL bad("SD_GenSpdCornerFreq", "value differs")
    IF (ref%SD_Time /= cpp%SD_Time) CALL bad("SD_Time", "value differs")
    IF (ref%SD_Method /= cpp%SD_Method) CALL bad("SD_Method", "value differs")
    IF (ALLOCATED(ref%SD_MaxTorqueRate) .NEQV. ALLOCATED(cpp%SD_MaxTorqueRate)) THEN
        IF ((.NOT. ALLOCATED(ref%SD_MaxTorqueRate)) .AND. SIZE(cpp%SD_MaxTorqueRate) == 0) THEN
            CALL artifact("SD_MaxTorqueRate")
        ELSE
            CALL bad("SD_MaxTorqueRate", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%SD_MaxTorqueRate)) THEN
        IF (ANY(SHAPE(ref%SD_MaxTorqueRate) /= SHAPE(cpp%SD_MaxTorqueRate))) THEN
            CALL bad("SD_MaxTorqueRate", "SHAPE differs")
        ELSE IF (SIZE(ref%SD_MaxTorqueRate) > 0) THEN
            IF (ANY(ref%SD_MaxTorqueRate /= cpp%SD_MaxTorqueRate)) CALL bad("SD_MaxTorqueRate", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%SD_MaxPitchRate) .NEQV. ALLOCATED(cpp%SD_MaxPitchRate)) THEN
        IF ((.NOT. ALLOCATED(ref%SD_MaxPitchRate)) .AND. SIZE(cpp%SD_MaxPitchRate) == 0) THEN
            CALL artifact("SD_MaxPitchRate")
        ELSE
            CALL bad("SD_MaxPitchRate", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%SD_MaxPitchRate)) THEN
        IF (ANY(SHAPE(ref%SD_MaxPitchRate) /= SHAPE(cpp%SD_MaxPitchRate))) THEN
            CALL bad("SD_MaxPitchRate", "SHAPE differs")
        ELSE IF (SIZE(ref%SD_MaxPitchRate) > 0) THEN
            IF (ANY(ref%SD_MaxPitchRate /= cpp%SD_MaxPitchRate)) CALL bad("SD_MaxPitchRate", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%SD_StagePitch) .NEQV. ALLOCATED(cpp%SD_StagePitch)) THEN
        IF ((.NOT. ALLOCATED(ref%SD_StagePitch)) .AND. SIZE(cpp%SD_StagePitch) == 0) THEN
            CALL artifact("SD_StagePitch")
        ELSE
            CALL bad("SD_StagePitch", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%SD_StagePitch)) THEN
        IF (ANY(SHAPE(ref%SD_StagePitch) /= SHAPE(cpp%SD_StagePitch))) THEN
            CALL bad("SD_StagePitch", "SHAPE differs")
        ELSE IF (SIZE(ref%SD_StagePitch) > 0) THEN
            IF (ANY(ref%SD_StagePitch /= cpp%SD_StagePitch)) CALL bad("SD_StagePitch", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%SD_StageTime) .NEQV. ALLOCATED(cpp%SD_StageTime)) THEN
        IF ((.NOT. ALLOCATED(ref%SD_StageTime)) .AND. SIZE(cpp%SD_StageTime) == 0) THEN
            CALL artifact("SD_StageTime")
        ELSE
            CALL bad("SD_StageTime", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%SD_StageTime)) THEN
        IF (ANY(SHAPE(ref%SD_StageTime) /= SHAPE(cpp%SD_StageTime))) THEN
            CALL bad("SD_StageTime", "SHAPE differs")
        ELSE IF (SIZE(ref%SD_StageTime) > 0) THEN
            IF (ANY(ref%SD_StageTime /= cpp%SD_StageTime)) CALL bad("SD_StageTime", "value differs")
        END IF
    END IF
    IF (ref%SD_Stage_N /= cpp%SD_Stage_N) CALL bad("SD_Stage_N", "value differs")
    IF (ref%Fl_Mode /= cpp%Fl_Mode) CALL bad("Fl_Mode", "value differs")
    IF (ref%Fl_n /= cpp%Fl_n) CALL bad("Fl_n", "value differs")
    IF (ALLOCATED(ref%Fl_Kp) .NEQV. ALLOCATED(cpp%Fl_Kp)) THEN
        IF ((.NOT. ALLOCATED(ref%Fl_Kp)) .AND. SIZE(cpp%Fl_Kp) == 0) THEN
            CALL artifact("Fl_Kp")
        ELSE
            CALL bad("Fl_Kp", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%Fl_Kp)) THEN
        IF (ANY(SHAPE(ref%Fl_Kp) /= SHAPE(cpp%Fl_Kp))) THEN
            CALL bad("Fl_Kp", "SHAPE differs")
        ELSE IF (SIZE(ref%Fl_Kp) > 0) THEN
            IF (ANY(ref%Fl_Kp /= cpp%Fl_Kp)) CALL bad("Fl_Kp", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%Fl_U) .NEQV. ALLOCATED(cpp%Fl_U)) THEN
        IF ((.NOT. ALLOCATED(ref%Fl_U)) .AND. SIZE(cpp%Fl_U) == 0) THEN
            CALL artifact("Fl_U")
        ELSE
            CALL bad("Fl_U", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%Fl_U)) THEN
        IF (ANY(SHAPE(ref%Fl_U) /= SHAPE(cpp%Fl_U))) THEN
            CALL bad("Fl_U", "SHAPE differs")
        ELSE IF (SIZE(ref%Fl_U) > 0) THEN
            IF (ANY(ref%Fl_U /= cpp%Fl_U)) CALL bad("Fl_U", "value differs")
        END IF
    END IF
    IF (ref%Flp_Mode /= cpp%Flp_Mode) CALL bad("Flp_Mode", "value differs")
    IF (ref%Flp_Angle /= cpp%Flp_Angle) CALL bad("Flp_Angle", "value differs")
    IF (ref%Flp_Kp /= cpp%Flp_Kp) CALL bad("Flp_Kp", "value differs")
    IF (ref%Flp_Ki /= cpp%Flp_Ki) CALL bad("Flp_Ki", "value differs")
    IF (ref%Flp_MaxPit /= cpp%Flp_MaxPit) CALL bad("Flp_MaxPit", "value differs")
    IF (ref%OL_Filename /= cpp%OL_Filename) CALL bad("OL_Filename", "value differs")
    IF (ref%OL_Mode /= cpp%OL_Mode) CALL bad("OL_Mode", "value differs")
    IF (ref%OL_BP_Mode /= cpp%OL_BP_Mode) CALL bad("OL_BP_Mode", "value differs")
    IF (ref%OL_BP_FiltFreq /= cpp%OL_BP_FiltFreq) CALL bad("OL_BP_FiltFreq", "value differs")
    IF (ref%Ind_Breakpoint /= cpp%Ind_Breakpoint) CALL bad("Ind_Breakpoint", "value differs")
    IF (ALLOCATED(ref%Ind_BldPitch) .NEQV. ALLOCATED(cpp%Ind_BldPitch)) THEN
        IF ((.NOT. ALLOCATED(ref%Ind_BldPitch)) .AND. SIZE(cpp%Ind_BldPitch) == 0) THEN
            CALL artifact("Ind_BldPitch")
        ELSE
            CALL bad("Ind_BldPitch", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%Ind_BldPitch)) THEN
        IF (ANY(SHAPE(ref%Ind_BldPitch) /= SHAPE(cpp%Ind_BldPitch))) THEN
            CALL bad("Ind_BldPitch", "SHAPE differs")
        ELSE IF (SIZE(ref%Ind_BldPitch) > 0) THEN
            IF (ANY(ref%Ind_BldPitch /= cpp%Ind_BldPitch)) CALL bad("Ind_BldPitch", "value differs")
        END IF
    END IF
    IF (ref%Ind_GenTq /= cpp%Ind_GenTq) CALL bad("Ind_GenTq", "value differs")
    IF (ref%Ind_YawRate /= cpp%Ind_YawRate) CALL bad("Ind_YawRate", "value differs")
    IF (ref%Ind_R_Speed /= cpp%Ind_R_Speed) CALL bad("Ind_R_Speed", "value differs")
    IF (ref%Ind_R_Torque /= cpp%Ind_R_Torque) CALL bad("Ind_R_Torque", "value differs")
    IF (ref%Ind_R_Pitch /= cpp%Ind_R_Pitch) CALL bad("Ind_R_Pitch", "value differs")
    IF (ref%Ind_Azimuth /= cpp%Ind_Azimuth) CALL bad("Ind_Azimuth", "value differs")
    IF (ALLOCATED(ref%RP_Gains) .NEQV. ALLOCATED(cpp%RP_Gains)) THEN
        IF ((.NOT. ALLOCATED(ref%RP_Gains)) .AND. SIZE(cpp%RP_Gains) == 0) THEN
            CALL artifact("RP_Gains")
        ELSE
            CALL bad("RP_Gains", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%RP_Gains)) THEN
        IF (ANY(SHAPE(ref%RP_Gains) /= SHAPE(cpp%RP_Gains))) THEN
            CALL bad("RP_Gains", "SHAPE differs")
        ELSE IF (SIZE(ref%RP_Gains) > 0) THEN
            IF (ANY(ref%RP_Gains /= cpp%RP_Gains)) CALL bad("RP_Gains", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%Ind_CableControl) .NEQV. ALLOCATED(cpp%Ind_CableControl)) THEN
        IF ((.NOT. ALLOCATED(ref%Ind_CableControl)) .AND. SIZE(cpp%Ind_CableControl) == 0) THEN
            CALL artifact("Ind_CableControl")
        ELSE
            CALL bad("Ind_CableControl", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%Ind_CableControl)) THEN
        IF (ANY(SHAPE(ref%Ind_CableControl) /= SHAPE(cpp%Ind_CableControl))) THEN
            CALL bad("Ind_CableControl", "SHAPE differs")
        ELSE IF (SIZE(ref%Ind_CableControl) > 0) THEN
            IF (ANY(ref%Ind_CableControl /= cpp%Ind_CableControl)) CALL bad("Ind_CableControl", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%Ind_StructControl) .NEQV. ALLOCATED(cpp%Ind_StructControl)) THEN
        IF ((.NOT. ALLOCATED(ref%Ind_StructControl)) .AND. SIZE(cpp%Ind_StructControl) == 0) THEN
            CALL artifact("Ind_StructControl")
        ELSE
            CALL bad("Ind_StructControl", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%Ind_StructControl)) THEN
        IF (ANY(SHAPE(ref%Ind_StructControl) /= SHAPE(cpp%Ind_StructControl))) THEN
            CALL bad("Ind_StructControl", "SHAPE differs")
        ELSE IF (SIZE(ref%Ind_StructControl) > 0) THEN
            IF (ANY(ref%Ind_StructControl /= cpp%Ind_StructControl)) CALL bad("Ind_StructControl", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%OL_Breakpoints) .NEQV. ALLOCATED(cpp%OL_Breakpoints)) THEN
        IF ((.NOT. ALLOCATED(ref%OL_Breakpoints)) .AND. SIZE(cpp%OL_Breakpoints) == 0) THEN
            CALL artifact("OL_Breakpoints")
        ELSE
            CALL bad("OL_Breakpoints", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%OL_Breakpoints)) THEN
        IF (ANY(SHAPE(ref%OL_Breakpoints) /= SHAPE(cpp%OL_Breakpoints))) THEN
            CALL bad("OL_Breakpoints", "SHAPE differs")
        ELSE IF (SIZE(ref%OL_Breakpoints) > 0) THEN
            IF (ANY(ref%OL_Breakpoints /= cpp%OL_Breakpoints)) CALL bad("OL_Breakpoints", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%OL_BldPitch1) .NEQV. ALLOCATED(cpp%OL_BldPitch1)) THEN
        IF ((.NOT. ALLOCATED(ref%OL_BldPitch1)) .AND. SIZE(cpp%OL_BldPitch1) == 0) THEN
            CALL artifact("OL_BldPitch1")
        ELSE
            CALL bad("OL_BldPitch1", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%OL_BldPitch1)) THEN
        IF (ANY(SHAPE(ref%OL_BldPitch1) /= SHAPE(cpp%OL_BldPitch1))) THEN
            CALL bad("OL_BldPitch1", "SHAPE differs")
        ELSE IF (SIZE(ref%OL_BldPitch1) > 0) THEN
            IF (ANY(ref%OL_BldPitch1 /= cpp%OL_BldPitch1)) CALL bad("OL_BldPitch1", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%OL_BldPitch2) .NEQV. ALLOCATED(cpp%OL_BldPitch2)) THEN
        IF ((.NOT. ALLOCATED(ref%OL_BldPitch2)) .AND. SIZE(cpp%OL_BldPitch2) == 0) THEN
            CALL artifact("OL_BldPitch2")
        ELSE
            CALL bad("OL_BldPitch2", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%OL_BldPitch2)) THEN
        IF (ANY(SHAPE(ref%OL_BldPitch2) /= SHAPE(cpp%OL_BldPitch2))) THEN
            CALL bad("OL_BldPitch2", "SHAPE differs")
        ELSE IF (SIZE(ref%OL_BldPitch2) > 0) THEN
            IF (ANY(ref%OL_BldPitch2 /= cpp%OL_BldPitch2)) CALL bad("OL_BldPitch2", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%OL_BldPitch3) .NEQV. ALLOCATED(cpp%OL_BldPitch3)) THEN
        IF ((.NOT. ALLOCATED(ref%OL_BldPitch3)) .AND. SIZE(cpp%OL_BldPitch3) == 0) THEN
            CALL artifact("OL_BldPitch3")
        ELSE
            CALL bad("OL_BldPitch3", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%OL_BldPitch3)) THEN
        IF (ANY(SHAPE(ref%OL_BldPitch3) /= SHAPE(cpp%OL_BldPitch3))) THEN
            CALL bad("OL_BldPitch3", "SHAPE differs")
        ELSE IF (SIZE(ref%OL_BldPitch3) > 0) THEN
            IF (ANY(ref%OL_BldPitch3 /= cpp%OL_BldPitch3)) CALL bad("OL_BldPitch3", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%OL_CableControl) .NEQV. ALLOCATED(cpp%OL_CableControl)) THEN
        IF ((.NOT. ALLOCATED(ref%OL_CableControl)) .AND. SIZE(cpp%OL_CableControl) == 0) THEN
            CALL artifact("OL_CableControl")
        ELSE
            CALL bad("OL_CableControl", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%OL_CableControl)) THEN
        IF (ANY(SHAPE(ref%OL_CableControl) /= SHAPE(cpp%OL_CableControl))) THEN
            CALL bad("OL_CableControl", "SHAPE differs")
        ELSE IF (SIZE(ref%OL_CableControl) > 0) THEN
            IF (ANY(ref%OL_CableControl /= cpp%OL_CableControl)) CALL bad("OL_CableControl", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%OL_StructControl) .NEQV. ALLOCATED(cpp%OL_StructControl)) THEN
        IF ((.NOT. ALLOCATED(ref%OL_StructControl)) .AND. SIZE(cpp%OL_StructControl) == 0) THEN
            CALL artifact("OL_StructControl")
        ELSE
            CALL bad("OL_StructControl", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%OL_StructControl)) THEN
        IF (ANY(SHAPE(ref%OL_StructControl) /= SHAPE(cpp%OL_StructControl))) THEN
            CALL bad("OL_StructControl", "SHAPE differs")
        ELSE IF (SIZE(ref%OL_StructControl) > 0) THEN
            IF (ANY(ref%OL_StructControl /= cpp%OL_StructControl)) CALL bad("OL_StructControl", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%OL_GenTq) .NEQV. ALLOCATED(cpp%OL_GenTq)) THEN
        IF ((.NOT. ALLOCATED(ref%OL_GenTq)) .AND. SIZE(cpp%OL_GenTq) == 0) THEN
            CALL artifact("OL_GenTq")
        ELSE
            CALL bad("OL_GenTq", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%OL_GenTq)) THEN
        IF (ANY(SHAPE(ref%OL_GenTq) /= SHAPE(cpp%OL_GenTq))) THEN
            CALL bad("OL_GenTq", "SHAPE differs")
        ELSE IF (SIZE(ref%OL_GenTq) > 0) THEN
            IF (ANY(ref%OL_GenTq /= cpp%OL_GenTq)) CALL bad("OL_GenTq", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%OL_YawRate) .NEQV. ALLOCATED(cpp%OL_YawRate)) THEN
        IF ((.NOT. ALLOCATED(ref%OL_YawRate)) .AND. SIZE(cpp%OL_YawRate) == 0) THEN
            CALL artifact("OL_YawRate")
        ELSE
            CALL bad("OL_YawRate", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%OL_YawRate)) THEN
        IF (ANY(SHAPE(ref%OL_YawRate) /= SHAPE(cpp%OL_YawRate))) THEN
            CALL bad("OL_YawRate", "SHAPE differs")
        ELSE IF (SIZE(ref%OL_YawRate) > 0) THEN
            IF (ANY(ref%OL_YawRate /= cpp%OL_YawRate)) CALL bad("OL_YawRate", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%OL_Azimuth) .NEQV. ALLOCATED(cpp%OL_Azimuth)) THEN
        IF ((.NOT. ALLOCATED(ref%OL_Azimuth)) .AND. SIZE(cpp%OL_Azimuth) == 0) THEN
            CALL artifact("OL_Azimuth")
        ELSE
            CALL bad("OL_Azimuth", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%OL_Azimuth)) THEN
        IF (ANY(SHAPE(ref%OL_Azimuth) /= SHAPE(cpp%OL_Azimuth))) THEN
            CALL bad("OL_Azimuth", "SHAPE differs")
        ELSE IF (SIZE(ref%OL_Azimuth) > 0) THEN
            IF (ANY(ref%OL_Azimuth /= cpp%OL_Azimuth)) CALL bad("OL_Azimuth", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%OL_R_Speed) .NEQV. ALLOCATED(cpp%OL_R_Speed)) THEN
        IF ((.NOT. ALLOCATED(ref%OL_R_Speed)) .AND. SIZE(cpp%OL_R_Speed) == 0) THEN
            CALL artifact("OL_R_Speed")
        ELSE
            CALL bad("OL_R_Speed", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%OL_R_Speed)) THEN
        IF (ANY(SHAPE(ref%OL_R_Speed) /= SHAPE(cpp%OL_R_Speed))) THEN
            CALL bad("OL_R_Speed", "SHAPE differs")
        ELSE IF (SIZE(ref%OL_R_Speed) > 0) THEN
            IF (ANY(ref%OL_R_Speed /= cpp%OL_R_Speed)) CALL bad("OL_R_Speed", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%OL_R_Torque) .NEQV. ALLOCATED(cpp%OL_R_Torque)) THEN
        IF ((.NOT. ALLOCATED(ref%OL_R_Torque)) .AND. SIZE(cpp%OL_R_Torque) == 0) THEN
            CALL artifact("OL_R_Torque")
        ELSE
            CALL bad("OL_R_Torque", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%OL_R_Torque)) THEN
        IF (ANY(SHAPE(ref%OL_R_Torque) /= SHAPE(cpp%OL_R_Torque))) THEN
            CALL bad("OL_R_Torque", "SHAPE differs")
        ELSE IF (SIZE(ref%OL_R_Torque) > 0) THEN
            IF (ANY(ref%OL_R_Torque /= cpp%OL_R_Torque)) CALL bad("OL_R_Torque", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%OL_R_Pitch) .NEQV. ALLOCATED(cpp%OL_R_Pitch)) THEN
        IF ((.NOT. ALLOCATED(ref%OL_R_Pitch)) .AND. SIZE(cpp%OL_R_Pitch) == 0) THEN
            CALL artifact("OL_R_Pitch")
        ELSE
            CALL bad("OL_R_Pitch", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%OL_R_Pitch)) THEN
        IF (ANY(SHAPE(ref%OL_R_Pitch) /= SHAPE(cpp%OL_R_Pitch))) THEN
            CALL bad("OL_R_Pitch", "SHAPE differs")
        ELSE IF (SIZE(ref%OL_R_Pitch) > 0) THEN
            IF (ANY(ref%OL_R_Pitch /= cpp%OL_R_Pitch)) CALL bad("OL_R_Pitch", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%OL_Channels) .NEQV. ALLOCATED(cpp%OL_Channels)) THEN
        IF ((.NOT. ALLOCATED(ref%OL_Channels)) .AND. SIZE(cpp%OL_Channels) == 0) THEN
            CALL artifact("OL_Channels")
        ELSE
            CALL bad("OL_Channels", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%OL_Channels)) THEN
        IF (ANY(SHAPE(ref%OL_Channels) /= SHAPE(cpp%OL_Channels))) THEN
            CALL bad("OL_Channels", "SHAPE differs")
        ELSE IF (SIZE(ref%OL_Channels) > 0) THEN
            IF (ANY(ref%OL_Channels /= cpp%OL_Channels)) CALL bad("OL_Channels", "value differs")
        END IF
    END IF
    IF (ref%PA_Mode /= cpp%PA_Mode) CALL bad("PA_Mode", "value differs")
    IF (ref%PA_CornerFreq /= cpp%PA_CornerFreq) CALL bad("PA_CornerFreq", "value differs")
    IF (ref%PA_Damping /= cpp%PA_Damping) CALL bad("PA_Damping", "value differs")
    IF (ref%AWC_Mode /= cpp%AWC_Mode) CALL bad("AWC_Mode", "value differs")
    IF (ref%AWC_NumModes /= cpp%AWC_NumModes) CALL bad("AWC_NumModes", "value differs")
    IF (ALLOCATED(ref%AWC_n) .NEQV. ALLOCATED(cpp%AWC_n)) THEN
        IF ((.NOT. ALLOCATED(ref%AWC_n)) .AND. SIZE(cpp%AWC_n) == 0) THEN
            CALL artifact("AWC_n")
        ELSE
            CALL bad("AWC_n", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%AWC_n)) THEN
        IF (ANY(SHAPE(ref%AWC_n) /= SHAPE(cpp%AWC_n))) THEN
            CALL bad("AWC_n", "SHAPE differs")
        ELSE IF (SIZE(ref%AWC_n) > 0) THEN
            IF (ANY(ref%AWC_n /= cpp%AWC_n)) CALL bad("AWC_n", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%AWC_harmonic) .NEQV. ALLOCATED(cpp%AWC_harmonic)) THEN
        IF ((.NOT. ALLOCATED(ref%AWC_harmonic)) .AND. SIZE(cpp%AWC_harmonic) == 0) THEN
            CALL artifact("AWC_harmonic")
        ELSE
            CALL bad("AWC_harmonic", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%AWC_harmonic)) THEN
        IF (ANY(SHAPE(ref%AWC_harmonic) /= SHAPE(cpp%AWC_harmonic))) THEN
            CALL bad("AWC_harmonic", "SHAPE differs")
        ELSE IF (SIZE(ref%AWC_harmonic) > 0) THEN
            IF (ANY(ref%AWC_harmonic /= cpp%AWC_harmonic)) CALL bad("AWC_harmonic", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%AWC_freq) .NEQV. ALLOCATED(cpp%AWC_freq)) THEN
        IF ((.NOT. ALLOCATED(ref%AWC_freq)) .AND. SIZE(cpp%AWC_freq) == 0) THEN
            CALL artifact("AWC_freq")
        ELSE
            CALL bad("AWC_freq", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%AWC_freq)) THEN
        IF (ANY(SHAPE(ref%AWC_freq) /= SHAPE(cpp%AWC_freq))) THEN
            CALL bad("AWC_freq", "SHAPE differs")
        ELSE IF (SIZE(ref%AWC_freq) > 0) THEN
            IF (ANY(ref%AWC_freq /= cpp%AWC_freq)) CALL bad("AWC_freq", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%AWC_amp) .NEQV. ALLOCATED(cpp%AWC_amp)) THEN
        IF ((.NOT. ALLOCATED(ref%AWC_amp)) .AND. SIZE(cpp%AWC_amp) == 0) THEN
            CALL artifact("AWC_amp")
        ELSE
            CALL bad("AWC_amp", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%AWC_amp)) THEN
        IF (ANY(SHAPE(ref%AWC_amp) /= SHAPE(cpp%AWC_amp))) THEN
            CALL bad("AWC_amp", "SHAPE differs")
        ELSE IF (SIZE(ref%AWC_amp) > 0) THEN
            IF (ANY(ref%AWC_amp /= cpp%AWC_amp)) CALL bad("AWC_amp", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%AWC_clockangle) .NEQV. ALLOCATED(cpp%AWC_clockangle)) THEN
        IF ((.NOT. ALLOCATED(ref%AWC_clockangle)) .AND. SIZE(cpp%AWC_clockangle) == 0) THEN
            CALL artifact("AWC_clockangle")
        ELSE
            CALL bad("AWC_clockangle", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%AWC_clockangle)) THEN
        IF (ANY(SHAPE(ref%AWC_clockangle) /= SHAPE(cpp%AWC_clockangle))) THEN
            CALL bad("AWC_clockangle", "SHAPE differs")
        ELSE IF (SIZE(ref%AWC_clockangle) > 0) THEN
            IF (ANY(ref%AWC_clockangle /= cpp%AWC_clockangle)) CALL bad("AWC_clockangle", "value differs")
        END IF
    END IF
    IF (ref%AWC_phaseoffset /= cpp%AWC_phaseoffset) CALL bad("AWC_phaseoffset", "value differs")
    IF (ALLOCATED(ref%AWC_CntrGains) .NEQV. ALLOCATED(cpp%AWC_CntrGains)) THEN
        IF ((.NOT. ALLOCATED(ref%AWC_CntrGains)) .AND. SIZE(cpp%AWC_CntrGains) == 0) THEN
            CALL artifact("AWC_CntrGains")
        ELSE
            CALL bad("AWC_CntrGains", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%AWC_CntrGains)) THEN
        IF (ANY(SHAPE(ref%AWC_CntrGains) /= SHAPE(cpp%AWC_CntrGains))) THEN
            CALL bad("AWC_CntrGains", "SHAPE differs")
        ELSE IF (SIZE(ref%AWC_CntrGains) > 0) THEN
            IF (ANY(ref%AWC_CntrGains /= cpp%AWC_CntrGains)) CALL bad("AWC_CntrGains", "value differs")
        END IF
    END IF
    IF (ref%PF_Mode /= cpp%PF_Mode) CALL bad("PF_Mode", "value differs")
    IF (ALLOCATED(ref%PF_Offsets) .NEQV. ALLOCATED(cpp%PF_Offsets)) THEN
        IF ((.NOT. ALLOCATED(ref%PF_Offsets)) .AND. SIZE(cpp%PF_Offsets) == 0) THEN
            CALL artifact("PF_Offsets")
        ELSE
            CALL bad("PF_Offsets", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%PF_Offsets)) THEN
        IF (ANY(SHAPE(ref%PF_Offsets) /= SHAPE(cpp%PF_Offsets))) THEN
            CALL bad("PF_Offsets", "SHAPE differs")
        ELSE IF (SIZE(ref%PF_Offsets) > 0) THEN
            IF (ANY(ref%PF_Offsets /= cpp%PF_Offsets)) CALL bad("PF_Offsets", "value differs")
        END IF
    END IF
    IF (ALLOCATED(ref%PF_TimeStuck) .NEQV. ALLOCATED(cpp%PF_TimeStuck)) THEN
        IF ((.NOT. ALLOCATED(ref%PF_TimeStuck)) .AND. SIZE(cpp%PF_TimeStuck) == 0) THEN
            CALL artifact("PF_TimeStuck")
        ELSE
            CALL bad("PF_TimeStuck", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%PF_TimeStuck)) THEN
        IF (ANY(SHAPE(ref%PF_TimeStuck) /= SHAPE(cpp%PF_TimeStuck))) THEN
            CALL bad("PF_TimeStuck", "SHAPE differs")
        ELSE IF (SIZE(ref%PF_TimeStuck) > 0) THEN
            IF (ANY(ref%PF_TimeStuck /= cpp%PF_TimeStuck)) CALL bad("PF_TimeStuck", "value differs")
        END IF
    END IF
    IF (ref%Ext_Mode /= cpp%Ext_Mode) CALL bad("Ext_Mode", "value differs")
    IF (ref%DLL_FileName /= cpp%DLL_FileName) CALL bad("DLL_FileName", "value differs")
    IF (ref%DLL_InFile /= cpp%DLL_InFile) CALL bad("DLL_InFile", "value differs")
    IF (ref%DLL_ProcName /= cpp%DLL_ProcName) CALL bad("DLL_ProcName", "value differs")
    IF (ref%ZMQ_Mode /= cpp%ZMQ_Mode) CALL bad("ZMQ_Mode", "value differs")
    IF (ref%ZMQ_CommAddress /= cpp%ZMQ_CommAddress) CALL bad("ZMQ_CommAddress", "value differs")
    IF (ref%ZMQ_UpdatePeriod /= cpp%ZMQ_UpdatePeriod) CALL bad("ZMQ_UpdatePeriod", "value differs")
    IF (ref%CC_Mode /= cpp%CC_Mode) CALL bad("CC_Mode", "value differs")
    IF (ref%CC_Group_N /= cpp%CC_Group_N) CALL bad("CC_Group_N", "value differs")
    IF (ref%CC_ActTau /= cpp%CC_ActTau) CALL bad("CC_ActTau", "value differs")
    IF (ALLOCATED(ref%CC_GroupIndex) .NEQV. ALLOCATED(cpp%CC_GroupIndex)) THEN
        IF ((.NOT. ALLOCATED(ref%CC_GroupIndex)) .AND. SIZE(cpp%CC_GroupIndex) == 0) THEN
            CALL artifact("CC_GroupIndex")
        ELSE
            CALL bad("CC_GroupIndex", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%CC_GroupIndex)) THEN
        IF (ANY(SHAPE(ref%CC_GroupIndex) /= SHAPE(cpp%CC_GroupIndex))) THEN
            CALL bad("CC_GroupIndex", "SHAPE differs")
        ELSE IF (SIZE(ref%CC_GroupIndex) > 0) THEN
            IF (ANY(ref%CC_GroupIndex /= cpp%CC_GroupIndex)) CALL bad("CC_GroupIndex", "value differs")
        END IF
    END IF
    IF (ref%StC_Mode /= cpp%StC_Mode) CALL bad("StC_Mode", "value differs")
    IF (ref%StC_Group_N /= cpp%StC_Group_N) CALL bad("StC_Group_N", "value differs")
    IF (ALLOCATED(ref%StC_GroupIndex) .NEQV. ALLOCATED(cpp%StC_GroupIndex)) THEN
        IF ((.NOT. ALLOCATED(ref%StC_GroupIndex)) .AND. SIZE(cpp%StC_GroupIndex) == 0) THEN
            CALL artifact("StC_GroupIndex")
        ELSE
            CALL bad("StC_GroupIndex", "ALLOCATED differs")
        END IF
    ELSE IF (ALLOCATED(ref%StC_GroupIndex)) THEN
        IF (ANY(SHAPE(ref%StC_GroupIndex) /= SHAPE(cpp%StC_GroupIndex))) THEN
            CALL bad("StC_GroupIndex", "SHAPE differs")
        ELSE IF (SIZE(ref%StC_GroupIndex) > 0) THEN
            IF (ANY(ref%StC_GroupIndex /= cpp%StC_GroupIndex)) CALL bad("StC_GroupIndex", "value differs")
        END IF
    END IF
    IF (ref%PC_RtTq99 /= cpp%PC_RtTq99) CALL bad("PC_RtTq99", "value differs")
    IF (ref%VS_MaxOMTq /= cpp%VS_MaxOMTq) CALL bad("VS_MaxOMTq", "value differs")
    IF (ref%VS_MinOMTq /= cpp%VS_MinOMTq) CALL bad("VS_MinOMTq", "value differs")

        total_cases = total_cases + 1
        total_bad = total_bad + nbad
        total_art = total_art + nart
        IF (nbad == 0) THEN
            WRITE(*,'(A,A,A,I0,A)') '  ok    ', TRIM(current), &
                '   213 of 213 fields identical, ', nart, ' unallocated-vs-empty'
        ELSE
            WRITE(*,'(A,A,A,I0,A,I0,A)') '  FAIL  ', TRIM(current), '   ', nbad, &
                ' field(s) differ, ', nart, ' unallocated-vs-empty'
        END IF
        DEALLOCATE(acc, root)
    END DO

    WRITE(*,'(A)') ''
    WRITE(*,'(A,I0,A,I0,A,I0)') 'cases ', total_cases, &
        '   FIELD (translation) ', total_bad, &
        '   COPYBK (the view cannot express unallocated) ', total_art
    IF (total_bad /= 0) STOP 1

CONTAINS

    SUBROUTINE bad(fld, why)
        CHARACTER(*), INTENT(IN) :: fld, why
        nbad = nbad + 1
        WRITE(*,'(A,A,A,A,A,A)') '        FIELD  ', TRIM(current), '  ', fld, '  ', why
    END SUBROUTINE

    ! THE COPY-BACK CANNOT EXPRESS `UNALLOCATED`, AND THAT IS ONE CAUSE
    ! REPORTING ONCE PER FIELD.
    !
    ! `vit_view_in_controlparameters` (vit_controlparameters_view.f90:1371-1373)
    ! reads the view's (pointer, extent) pair and writes
    !
    !     ELSE IF (view%n_X == 0) THEN
    !         ALLOCATE(dest%X(0))   ! allocated-empty, distinct from unallocated
    !
    ! so a NULL pointer with extent 0 -- which is what an ALLOCATABLE the
    ! reference never touched looks like from C -- comes back ALLOCATED with
    ! size zero. Unallocated is not reachable through the view at all. This is
    ! P6 ("absence must not render as a value") in the copy-back, NOT a defect
    ! in the translation: the translation did not write the field, and there is
    ! no value on the C side that would have said so.
    !
    ! Counted rather than suppressed. A field whose reference side IS allocated,
    ! or whose C++ side comes back with a non-zero size, goes to `bad`.
    SUBROUTINE artifact(fld)
        CHARACTER(*), INTENT(IN) :: fld
        nart = nart + 1
        WRITE(*,'(A,A,A,A)') '        COPYBK ', TRIM(current), '  ', fld
    END SUBROUTINE

    ! The reference reads LocalVar%DT and nothing else (the harness planner's
    ! own read set: "LocalVar: reads 1 field(s): DT"). It is the divisor of
    ! n_DT_Out and n_DT_ZMQ, so it must be non-zero and it must be the same on
    ! both sides.
    SUBROUTINE init_local(lv)
        TYPE(LocalVariables), INTENT(INOUT) :: lv
        lv%DT = 0.01_DbKi
    END SUBROUTINE

    SUBROUTINE init_err(ev)
        TYPE(ErrorVariables), INTENT(INOUT) :: ev
        ev%aviFAIL = 0
        ev%size_avcMSG = 1024
        IF (ALLOCATED(ev%ErrMsg)) DEALLOCATE(ev%ErrMsg)
        ev%ErrMsg = ''
    END SUBROUTINE

    ! Both sides must start from the SAME ControlParameters, and the one the
    ! reference requires is one with every ALLOCATABLE UNALLOCATED -- ParseAry
    ! reports "array was already allocated" otherwise. A fresh local is that,
    ! but this program reuses two, so they are emptied between cases.
    SUBROUTINE wipe(cp)
        TYPE(ControlParameters), INTENT(INOUT) :: cp
        cp = blank
    END SUBROUTINE

END PROGRAM vit_rcpfs_probe

