// VIT Translation
// Function: PIIController
// Source: Controllers.f90
// Module: Controllers
// Fortran: FUNCTION PIIController(error, error2, kp, ki, ki2, minValue, maxValue, DT, I0, piP, reset, inst)
// Status: unverified

// Auto-generated C struct for Fortran TYPE(piParams)
// Generated by VIT (Verified Incremental Translator)

#ifndef PIPARAMS_T_H
#define PIPARAMS_T_H

typedef struct {
    double ITerm[1024];
    double ITermLast[1024];
    double ITerm2[1024];
    double ITermLast2[1024];
    double ELast[1024];
} piparams_t;

#endif // PIPARAMS_T_H

#include <algorithm>

double piicontroller(double error, double error2, double kp, double ki, double ki2, double minValue, double maxValue, double DT, double I0, piparams_t* piP, int reset, int* inst) {
    int idx = *inst - 1;  // Fortran 1-based -> C 0-based
    double result;

    if (reset) {
        piP->ITerm[idx] = I0;
        piP->ITermLast[idx] = I0;
        piP->ITerm2[idx] = I0;
        piP->ITermLast2[idx] = I0;

        result = I0;
    } else {
        double PTerm = kp * error;
        piP->ITerm[idx] = piP->ITerm[idx] + DT * ki * error;
        piP->ITerm2[idx] = piP->ITerm2[idx] + DT * ki2 * error2;
        piP->ITerm[idx] = std::min(std::max(piP->ITerm[idx], minValue), maxValue);
        piP->ITerm2[idx] = std::min(std::max(piP->ITerm2[idx], minValue), maxValue);
        result = PTerm + piP->ITerm[idx] + piP->ITerm2[idx];
        result = std::min(std::max(result, minValue), maxValue);

        piP->ITermLast[idx] = piP->ITerm[idx];
    }
    *inst = *inst + 1;

    return result;
}
