// VIT Translation
// Function: PitchControl
// Source: Controllers.f90
// Module: Controllers
// Fortran: SUBROUTINE PitchControl(avrSWAP, CntrPar, LocalVar, objInst, DebugVar, ErrVar)
// Source MD5: 9c79c278f64a
// VIT: 0.1.0
// Status: unverified
// Generated: 2026-03-24T17:41:38Z

// Auto-generated view struct for Fortran TYPE(ControlParameters)
// Generated by VIT (Verified Incremental Translator)
// ALLOCATABLE fields exposed as pointer+size pairs.
// Scalars and CHARACTER fields copied directly.
// 2D arrays use column-major layout: mat[col * n_rows + row]

#ifndef CONTROLPARAMETERS_VIEW_T_H
#define CONTROLPARAMETERS_VIEW_T_H

#include <stdint.h>

typedef struct {
    // --- Scalar and fixed-size fields ---
    int ZMQ_ID;
    int LoggingLevel;
    int Echo;
    int Ext_Interface;
    double DT_Out;
    int n_DT_Out;
    int n_DT_ZMQ;
    int F_LPFType;
    double F_LPFCornerFreq;
    double F_LPFDamping;
    int F_NumNotchFilts;
    int F_GenSpdNotch_N;
    int F_TwrTopNotch_N;
    double F_SSCornerFreq;
    double F_WECornerFreq;
    double F_FlHighPassFreq;
    double F_YawErr;
    double F_VSRefSpdCornerFreq;
    int TRA_Mode;
    double TRA_ExclSpeed;
    double TRA_ExclBand;
    double TRA_RateLimit;
    int TD_Mode;
    double FA_HPFCornerFreq;
    double FA_IntSat;
    double FA_KI;
    int IPC_ControlMode;
    double IPC_IntSat;
    int IPC_SatMode;
    double IPC_CornerFreqAct;
    int PC_ControlMode;
    int PC_GS_n;
    double PC_MaxPit;
    double PC_MinPit;
    double PC_MaxRat;
    double PC_MinRat;
    double PC_RefSpd;
    double PC_FinePit;
    double PC_Switch;
    int VS_ControlMode;
    int VS_ConstPower;
    int VS_FBP;
    double VS_GenEff;
    double VS_ArSatTq;
    double VS_MaxRat;
    double VS_MaxTq;
    double VS_MinTq;
    double VS_MinOMSpd;
    double VS_Rgn2K;
    double VS_RtPwr;
    double VS_RtTq;
    double VS_RefSpd;
    int VS_n;
    double VS_TSRopt;
    int VS_FBP_n;
    int SS_Mode;
    double SS_VSGain;
    double SS_PCGain;
    int PRC_Mode;
    int PRC_Comm;
    int PRC_n;
    double PRC_LPF_Freq;
    double PRC_R_Torque;
    double PRC_R_Speed;
    double PRC_R_Pitch;
    int PRC_Table_n;
    int WE_Mode;
    double WE_BladeRadius;
    int WE_CP_n;
    double WE_Gamma;
    double WE_GearboxRatio;
    double WE_Jtot;
    double WE_RhoAir;
    char PerfFileName[1024];
    int WE_FOPoles_N;
    int Y_ControlMode;
    double Y_uSwitch;
    double Y_Rate;
    double Y_MErrSet;
    double Y_IPC_IntSat;
    double Y_IPC_KP;
    double Y_IPC_KI;
    int PS_Mode;
    int PS_BldPitchMin_N;
    int SU_Mode;
    double SU_StartTime;
    double SU_FW_MinDuration;
    double SU_RotorSpeedThresh;
    double SU_RotorSpeedCornerFreq;
    int SU_LoadStages_N;
    int SD_Mode;
    double SD_TimeActivate;
    int SD_EnablePitch;
    int SD_EnableYawError;
    int SD_EnableGenSpeed;
    int SD_EnableTime;
    double SD_MaxPit;
    double SD_PitchCornerFreq;
    double SD_MaxYawError;
    double SD_YawErrorCornerFreq;
    double SD_MaxGenSpd;
    double SD_GenSpdCornerFreq;
    double SD_Time;
    int SD_Method;
    int SD_Stage_N;
    int Fl_Mode;
    int Fl_n;
    int Flp_Mode;
    double Flp_Angle;
    double Flp_Kp;
    double Flp_Ki;
    double Flp_MaxPit;
    char OL_Filename[1024];
    int OL_Mode;
    int OL_BP_Mode;
    double OL_BP_FiltFreq;
    int Ind_Breakpoint;
    int Ind_GenTq;
    int Ind_YawRate;
    int Ind_R_Speed;
    int Ind_R_Torque;
    int Ind_R_Pitch;
    int Ind_Azimuth;
    int PA_Mode;
    double PA_CornerFreq;
    double PA_Damping;
    int AWC_Mode;
    int AWC_NumModes;
    double AWC_phaseoffset;
    int PF_Mode;
    int Ext_Mode;
    char DLL_FileName[1024];
    char DLL_InFile[1024];
    char DLL_ProcName[1024];
    int ZMQ_Mode;
    char ZMQ_CommAddress[256];
    double ZMQ_UpdatePeriod;
    int CC_Mode;
    int CC_Group_N;
    double CC_ActTau;
    int StC_Mode;
    int StC_Group_N;
    double PC_RtTq99;
    double VS_MaxOMTq;
    double VS_MinOMTq;

    // --- ALLOCATABLE fields (pointer + size) ---
    int* F_GenSpdNotch_Ind;
    int32_t n_F_GenSpdNotch_Ind;
    int* F_TwrTopNotch_Ind;
    int32_t n_F_TwrTopNotch_Ind;
    double* F_NotchFreqs;
    int32_t n_F_NotchFreqs;
    double* F_NotchBetaNum;
    int32_t n_F_NotchBetaNum;
    double* F_NotchBetaDen;
    int32_t n_F_NotchBetaDen;
    double* F_FlCornerFreq;
    int32_t n_F_FlCornerFreq;
    double* F_FlpCornerFreq;
    int32_t n_F_FlpCornerFreq;
    double* IPC_Vramp;
    int32_t n_IPC_Vramp;
    double* IPC_KP;
    int32_t n_IPC_KP;
    double* IPC_KI;
    int32_t n_IPC_KI;
    double* IPC_aziOffset;
    int32_t n_IPC_aziOffset;
    double* PC_GS_angles;
    int32_t n_PC_GS_angles;
    double* PC_GS_KP;
    int32_t n_PC_GS_KP;
    double* PC_GS_KI;
    int32_t n_PC_GS_KI;
    double* PC_GS_KD;
    int32_t n_PC_GS_KD;
    double* PC_GS_TF;
    int32_t n_PC_GS_TF;
    double* VS_KP;
    int32_t n_VS_KP;
    double* VS_KI;
    int32_t n_VS_KI;
    double* VS_FBP_U;
    int32_t n_VS_FBP_U;
    double* VS_FBP_Omega;
    int32_t n_VS_FBP_Omega;
    double* VS_FBP_Tau;
    int32_t n_VS_FBP_Tau;
    double* PRC_WindSpeeds;
    int32_t n_PRC_WindSpeeds;
    double* PRC_GenSpeeds;
    int32_t n_PRC_GenSpeeds;
    double* PRC_Pitch_Table;
    int32_t n_PRC_Pitch_Table;
    double* PRC_R_Table;
    int32_t n_PRC_R_Table;
    double* WE_CP;
    int32_t n_WE_CP;
    int* PerfTableSize;
    int32_t n_PerfTableSize;
    double* WE_FOPoles_v;
    int32_t n_WE_FOPoles_v;
    double* WE_FOPoles;
    int32_t n_WE_FOPoles;
    double* Y_ErrThresh;
    int32_t n_Y_ErrThresh;
    double* PS_WindSpeeds;
    int32_t n_PS_WindSpeeds;
    double* PS_BldPitchMin;
    int32_t n_PS_BldPitchMin;
    double* SU_LoadStages;
    int32_t n_SU_LoadStages;
    double* SU_LoadRampDuration;
    int32_t n_SU_LoadRampDuration;
    double* SU_LoadHoldDuration;
    int32_t n_SU_LoadHoldDuration;
    double* SD_MaxTorqueRate;
    int32_t n_SD_MaxTorqueRate;
    double* SD_MaxPitchRate;
    int32_t n_SD_MaxPitchRate;
    double* SD_StagePitch;
    int32_t n_SD_StagePitch;
    double* SD_StageTime;
    int32_t n_SD_StageTime;
    double* Fl_Kp;
    int32_t n_Fl_Kp;
    double* Fl_U;
    int32_t n_Fl_U;
    int* Ind_BldPitch;
    int32_t n_Ind_BldPitch;
    double* RP_Gains;
    int32_t n_RP_Gains;
    int* Ind_CableControl;
    int32_t n_Ind_CableControl;
    int* Ind_StructControl;
    int32_t n_Ind_StructControl;
    double* OL_Breakpoints;
    int32_t n_OL_Breakpoints;
    double* OL_BldPitch1;
    int32_t n_OL_BldPitch1;
    double* OL_BldPitch2;
    int32_t n_OL_BldPitch2;
    double* OL_BldPitch3;
    int32_t n_OL_BldPitch3;
    double* OL_CableControl;  // column-major
    int32_t n_OL_CableControl_rows;
    int32_t n_OL_CableControl_cols;
    double* OL_StructControl;  // column-major
    int32_t n_OL_StructControl_rows;
    int32_t n_OL_StructControl_cols;
    double* OL_GenTq;
    int32_t n_OL_GenTq;
    double* OL_YawRate;
    int32_t n_OL_YawRate;
    double* OL_Azimuth;
    int32_t n_OL_Azimuth;
    double* OL_R_Speed;
    int32_t n_OL_R_Speed;
    double* OL_R_Torque;
    int32_t n_OL_R_Torque;
    double* OL_R_Pitch;
    int32_t n_OL_R_Pitch;
    double* OL_Channels;  // column-major
    int32_t n_OL_Channels_rows;
    int32_t n_OL_Channels_cols;
    int* AWC_n;
    int32_t n_AWC_n;
    int* AWC_harmonic;
    int32_t n_AWC_harmonic;
    double* AWC_freq;
    int32_t n_AWC_freq;
    double* AWC_amp;
    int32_t n_AWC_amp;
    double* AWC_clockangle;
    int32_t n_AWC_clockangle;
    double* AWC_CntrGains;
    int32_t n_AWC_CntrGains;
    double* PF_Offsets;
    int32_t n_PF_Offsets;
    double* PF_TimeStuck;
    int32_t n_PF_TimeStuck;
    int* CC_GroupIndex;
    int32_t n_CC_GroupIndex;
    int* StC_GroupIndex;
    int32_t n_StC_GroupIndex;
} controlparameters_view_t;

#endif // CONTROLPARAMETERS_VIEW_T_H

// Auto-generated C struct for Fortran TYPE(DebugVariables)
// Generated by VIT (Verified Incremental Translator)

#ifndef DEBUGVARIABLES_T_H
#define DEBUGVARIABLES_T_H

typedef struct {
    double WE_Cp;
    double WE_b;
    double WE_w;
    double WE_t;
    double WE_Vm;
    double WE_Vt;
    double WE_Vw;
    double WE_lambda;
    double PC_PICommand;
    double GenSpeedF;
    double RotSpeedF;
    double NacIMU_FA_AccF;
    double FA_AccF;
    double Fl_PitCom;
    double PC_MinPit;
    double axisTilt_1P;
    double axisYaw_1P;
    double axisTilt_2P;
    double axisYaw_2P;
    double YawRateCom;
    double NacHeadingTarget;
    double NacVaneOffset;
    double Yaw_Err;
    double YawState;
    double VS_RefSpd;
    double PC_RefSpd;
} debugvariables_t;

#endif // DEBUGVARIABLES_T_H

// Auto-generated C struct for Fortran TYPE(ErrorVariables)
// Generated by VIT (Verified Incremental Translator)

#ifndef ERRORVARIABLES_T_H
#define ERRORVARIABLES_T_H

typedef struct {
    int size_avcMSG;
    int aviFAIL;
    int ErrStat;
    char ErrMsg[1024];
} errorvariables_t;

#endif // ERRORVARIABLES_T_H

// Auto-generated C struct for Fortran TYPE(FilterParameters)
// Generated by VIT (Verified Incremental Translator)

#ifndef FILTERPARAMETERS_T_H
#define FILTERPARAMETERS_T_H

typedef struct {
    double lpf1_a1[1024];
    double lpf1_a0[1024];
    double lpf1_b1[1024];
    double lpf1_b0[1024];
    double lpf1_InputSignalLast[1024];
    double lpf1_OutputSignalLast[1024];
    double lpf2_a2[1024];
    double lpf2_a1[1024];
    double lpf2_a0[1024];
    double lpf2_b2[1024];
    double lpf2_b1[1024];
    double lpf2_b0[1024];
    double lpf2_InputSignalLast2[1024];
    double lpf2_OutputSignalLast2[1024];
    double lpf2_InputSignalLast1[1024];
    double lpf2_OutputSignalLast1[1024];
    double lpfV_a2[1024];
    double lpfV_a1[1024];
    double lpfV_a0[1024];
    double lpfV_b2[1024];
    double lpfV_b1[1024];
    double lpfV_b0[1024];
    double lpfV_InputSignalLast2[1024];
    double lpfV_OutputSignalLast2[1024];
    double lpfV_InputSignalLast1[1024];
    double lpfV_OutputSignalLast1[1024];
    double hpf_InputSignalLast[1024];
    double hpf_OutputSignalLast[1024];
    double nfs_OutputSignalLast1[1024];
    double nfs_OutputSignalLast2[1024];
    double nfs_InputSignalLast1[1024];
    double nfs_InputSignalLast2[1024];
    double nfs_b2[1024];
    double nfs_b0[1024];
    double nfs_a2[1024];
    double nfs_a1[1024];
    double nfs_a0[1024];
    double nf_OutputSignalLast1[1024];
    double nf_OutputSignalLast2[1024];
    double nf_InputSignalLast1[1024];
    double nf_InputSignalLast2[1024];
    double nf_b2[1024];
    double nf_b1[1024];
    double nf_b0[1024];
    double nf_a1[1024];
    double nf_a0[1024];
} filterparameters_t;

#endif // FILTERPARAMETERS_T_H

// Auto-generated C struct for Fortran TYPE(ObjectInstances)
// Generated by VIT (Verified Incremental Translator)

#ifndef OBJECTINSTANCES_T_H
#define OBJECTINSTANCES_T_H

typedef struct {
    int instLPF;
    int instSecLPF;
    int instSecLPFV;
    int instHPF;
    int instNotchSlopes;
    int instNotch;
    int instPI;
    int instRes;
    int instRL;
} objectinstances_t;

#endif // OBJECTINSTANCES_T_H

// Auto-generated C struct for Fortran TYPE(piParams)
// Generated by VIT (Verified Incremental Translator)

#ifndef PIPARAMS_T_H
#define PIPARAMS_T_H

typedef struct {
    double ITerm[1024];
    double ITermLast[1024];
    double ITerm2[1024];
    double ITermLast2[1024];
    double ELast[1024];
} piparams_t;

#endif // PIPARAMS_T_H

// Auto-generated C struct for Fortran TYPE(resParams)
// Generated by VIT (Verified Incremental Translator)

#ifndef RESPARAMS_T_H
#define RESPARAMS_T_H

typedef struct {
    double res_OutputSignalLast1[1024];
    double res_OutputSignalLast2[1024];
    double res_InputSignalLast1[1024];
    double res_InputSignalLast2[1024];
} resparams_t;

#endif // RESPARAMS_T_H

// Auto-generated C struct for Fortran TYPE(rlParams)
// Generated by VIT (Verified Incremental Translator)

#ifndef RLPARAMS_T_H
#define RLPARAMS_T_H

typedef struct {
    double LastSignal[1024];
} rlparams_t;

#endif // RLPARAMS_T_H

// Auto-generated C struct for Fortran TYPE(WE)
// Generated by VIT (Verified Incremental Translator)
// Note: Fortran uses column-major order.
//   Fortran P(i,j) maps to C P[j-1][i-1].

#ifndef WE_T_H
#define WE_T_H

typedef struct {
    double om_r;
    double v_t;
    double v_m;
    double v_h;
    double P[3][3];
    double xh[3][1];
    double K[3][1];
} we_t;

#endif // WE_T_H

// Auto-generated C struct for Fortran TYPE(LocalVariables)
// Generated by VIT (Verified Incremental Translator)

#ifndef LOCALVARIABLES_T_H
#define LOCALVARIABLES_T_H

typedef struct {
    int iStatus;
    int AlreadyInitialized;
    int RestartWSE;
    double Time;
    double DT;
    int WriteThisStep;
    int n_DT;
    double Time_Last;
    double VS_GenPwr;
    double GenSpeed;
    double RotSpeed;
    double NacHeading;
    double NacVane;
    double NacVaneF;
    double WindDir;
    double HorWindV;
    double HorWindV_F;
    double rootMOOP[3];
    double rootMOOPF[3];
    double BlPitch[3];
    double BlPitchCMeas;
    double Azimuth;
    double OL_Azimuth;
    double AzUnwrapped;
    double AzError;
    double GenTqAz;
    double AzBuffer[2];
    int NumBl;
    double FA_Acc_TT;
    double SS_Acc_TT;
    double FA_Acc_Nac;
    double NacIMU_FA_RAcc;
    double FA_AccHPF;
    double FA_AccHPFI;
    double FA_PitCom[3];
    double VS_RefSpd;
    double VS_RefSpd_TSR;
    double VS_RefSpd_TRA;
    double VS_RefSpd_RL;
    double PC_RefSpd;
    double PC_RefSpd_SS;
    double PC_RefSpd_PRC;
    double RotSpeedF;
    double GenSpeedF;
    double GenTq;
    double GenTqMeas;
    double GenArTq;
    double GenBrTq;
    double VS_KOmega2_GenTq;
    double VS_ConstPwr_GenTq;
    double IPC_PitComF[3];
    double PC_KP;
    double PC_KI;
    double PC_KD;
    double PC_TF;
    double PC_MaxPit;
    double PC_MinPit;
    double PC_PitComT;
    double PC_PitComT_Last;
    double BlPitchCMeasF;
    double PC_PitComT_IPC[3];
    double PC_PwrErr;
    double PC_SpdErr;
    double IPC_AxisTilt_1P;
    double IPC_AxisYaw_1P;
    double IPC_AxisTilt_2P;
    double IPC_AxisYaw_2P;
    double axisTilt_1P;
    double axisYaw_1P;
    double axisYawF_1P;
    double axisTilt_2P;
    double axisYaw_2P;
    double axisYawF_2P;
    double IPC_KI[2];
    double IPC_KP[2];
    double IPC_IntSat;
    int PC_State;
    double PitCom[3];
    double PitCom_SD[3];
    double PitComAct[3];
    double SS_DelOmegaF;
    double TestType;
    double Kp_Float;
    double VS_MaxTq;
    double VS_LastGenTrq;
    double VS_LastGenPwr;
    double VS_MechGenPwr;
    double VS_SpdErrAr;
    double VS_SpdErrBr;
    double VS_SpdErr;
    int VS_State;
    double VS_Rgn3Pitch;
    double WE_Vw;
    double WE_Vw_F;
    double WE_VwI;
    double WE_VwIdot;
    int WE_Op;
    int WE_Op_Last;
    double VS_LastGenTrqF;
    double PRC_WSE_F;
    double PRC_R_Speed;
    double PRC_R_Torque;
    double PRC_R_Pitch;
    double PRC_R_Total;
    double PRC_Min_Pitch;
    double PS_Min_Pitch;
    double OL_Index;
    int SU_Stage;
    double SU_LoadStageStartTime;
    double SU_RotSpeedF;
    int SD_Trigger;
    double SD_BlPitchF;
    double SD_NacVaneF;
    double SD_GenSpeedF;
    int SD_Stage;
    double SD_StageStartTime;
    double SD_MaxPitchRate;
    double SD_MaxTorqueRate;
    double GenTq_SD;
    double Fl_PitCom;
    double NACIMU_FA_AccF;
    double FA_AccF;
    int FA_Hist;
    double TRA_LastRefSpd;
    double VS_RefSpeed;
    double PtfmTDX;
    double PtfmTDY;
    double PtfmTDZ;
    double PtfmRDX;
    double PtfmRDY;
    double PtfmRDZ;
    double PtfmTVX;
    double PtfmTVY;
    double PtfmTVZ;
    double PtfmRVX;
    double PtfmRVY;
    double PtfmRVZ;
    double PtfmTAX;
    double PtfmTAY;
    double PtfmTAZ;
    double PtfmRAX;
    double PtfmRAY;
    double PtfmRAZ;
    double CC_DesiredL[12];
    double CC_ActuatedL[12];
    double CC_ActuatedDL[12];
    double StC_Input[12];
    double Flp_Angle[3];
    double RootMyb_Last[3];
    int ACC_INFILE_SIZE;
    char ACC_INFILE[1024];
    int restart;
    double AWC_complexangle_re[3];
    double AWC_complexangle_im[3];
    double TiltMean;
    double YawMean;
    int ZMQ_ID;
    double ZMQ_YawOffset;
    double ZMQ_TorqueOffset;
    double ZMQ_PitOffset[3];
    double ZMQ_R_Speed;
    double ZMQ_R_Torque;
    double ZMQ_R_Pitch;
    we_t WE;
    filterparameters_t FP;
    piparams_t piP;
    resparams_t resP;
    rlparams_t rlP;
} localvariables_t;

#endif // LOCALVARIABLES_T_H

#include <algorithm>
#include <cstring>
#include <cstdio>

#include "rosco_constants.h"

// Callee entry points
extern "C" {
    double picontroller_c(double error, double kp, double ki,
                          double minValue, double maxValue, double DT,
                          double I0, piparams_t* piP, int reset, int* inst);
    double interp1d_c(double* xData, int n_xData, double* yData, int n_yData,
                      double xq, errorvariables_t* ErrVar);
    double saturate_c(double val, double minval, double maxval);
    double ratelimit_c(double inputSignal, double minRate, double maxRate, double DT,
                       int reset, rlparams_t* rlP, int* inst,
                       int has_ResetValue, double ResetValue);
    void ipc_c(controlparameters_view_t* CntrPar, localvariables_t* LocalVar,
               objectinstances_t* objInst, debugvariables_t* DebugVar,
               errorvariables_t* ErrVar);
    void foreaftdamping_c(controlparameters_view_t* CntrPar, localvariables_t* LocalVar,
                          objectinstances_t* objInst);
    double pitchsaturation_c(localvariables_t* LocalVar, controlparameters_view_t* CntrPar,
                             objectinstances_t* objInst, debugvariables_t* DebugVar,
                             errorvariables_t* ErrVar);
    double floatingfeedback_c(localvariables_t* LocalVar, controlparameters_view_t* CntrPar,
                              objectinstances_t* objInst, errorvariables_t* ErrVar);
    void activewakecontrol_c(controlparameters_view_t* CntrPar, localvariables_t* LocalVar,
                             debugvariables_t* DebugVar, objectinstances_t* objInst);
    double lpfilter_c(double InputSignal, double DT, double CornerFreq,
                      filterparameters_t* FP, int iStatus, int reset, int* inst,
                      int has_InitialValue, double InitialValue);
    double seclpfilter_c(double InputSignal, double DT, double CornerFreq,
                         double Damp, filterparameters_t* FP, int iStatus,
                         int reset, int* inst,
                         int has_InitialValue, double InitialValue);
}

void PitchControl(float* avrSWAP, controlparameters_view_t* CntrPar, localvariables_t* LocalVar, objectinstances_t* objInst, debugvariables_t* DebugVar, errorvariables_t* ErrVar) {
    // PitchControl: master blade pitch controller
    // Orchestrates collective pitch PI, IPC, tower damping, floating feedback,
    // pitch saturation, AWC, shutdown, actuator model, and fault handling.

    // Load PC State
    if (LocalVar->PC_State == PC_State_Enabled) {
        LocalVar->PC_MaxPit = CntrPar->PC_MaxPit;
    } else {
        LocalVar->PC_MaxPit = CntrPar->PC_FinePit;
    }

    // Hold blade pitch at last value in pre-startup mode
    if ((CntrPar->SU_Mode > 0) && (LocalVar->SU_Stage == -1)) {
        LocalVar->PC_MaxPit = LocalVar->BlPitchCMeas;
        LocalVar->PC_MinPit = LocalVar->BlPitchCMeas;
    }

    // Gain scheduling via interpolation
    LocalVar->PC_KP = interp1d_c(CntrPar->PC_GS_angles, CntrPar->n_PC_GS_angles,
                                  CntrPar->PC_GS_KP, CntrPar->n_PC_GS_KP,
                                  LocalVar->BlPitchCMeasF, ErrVar);
    LocalVar->PC_KI = interp1d_c(CntrPar->PC_GS_angles, CntrPar->n_PC_GS_angles,
                                  CntrPar->PC_GS_KI, CntrPar->n_PC_GS_KI,
                                  LocalVar->BlPitchCMeasF, ErrVar);
    LocalVar->PC_KD = interp1d_c(CntrPar->PC_GS_angles, CntrPar->n_PC_GS_angles,
                                  CntrPar->PC_GS_KD, CntrPar->n_PC_GS_KD,
                                  LocalVar->BlPitchCMeasF, ErrVar);
    LocalVar->PC_TF = interp1d_c(CntrPar->PC_GS_angles, CntrPar->n_PC_GS_angles,
                                  CntrPar->PC_GS_TF, CntrPar->n_PC_GS_TF,
                                  LocalVar->BlPitchCMeasF, ErrVar);

    // Collective pitch PI controller
    LocalVar->PC_PitComT = picontroller_c(
        LocalVar->PC_SpdErr, LocalVar->PC_KP, LocalVar->PC_KI,
        LocalVar->PC_MinPit, LocalVar->PC_MaxPit,
        LocalVar->DT, LocalVar->BlPitch[0],
        &LocalVar->piP, (LocalVar->restart != 0), &objInst->instPI);
    DebugVar->PC_PICommand = LocalVar->PC_PitComT;

    // Individual pitch control
    if ((CntrPar->IPC_ControlMode >= 1) || (CntrPar->Y_ControlMode == 2)) {
        ipc_c(CntrPar, LocalVar, objInst, DebugVar, ErrVar);
    } else {
        LocalVar->IPC_PitComF[0] = 0.0;
        LocalVar->IPC_PitComF[1] = 0.0;
        LocalVar->IPC_PitComF[2] = 0.0;
    }

    // Tower fore-aft damping
    if (CntrPar->TD_Mode > 0) {
        foreaftdamping_c(CntrPar, LocalVar, objInst);
    } else {
        LocalVar->FA_PitCom[0] = 0.0;
        LocalVar->FA_PitCom[1] = 0.0;
        LocalVar->FA_PitCom[2] = 0.0;
    }

    // Pitch saturation
    if (CntrPar->PS_Mode > 0) {
        LocalVar->PC_MinPit = pitchsaturation_c(LocalVar, CntrPar, objInst, DebugVar, ErrVar);
        LocalVar->PC_MinPit = std::max(LocalVar->PC_MinPit, CntrPar->PC_FinePit);
    } else {
        LocalVar->PC_MinPit = CntrPar->PC_FinePit;
    }
    DebugVar->PC_MinPit = LocalVar->PC_MinPit;

    // Floating feedback
    if (CntrPar->Fl_Mode > 0) {
        LocalVar->Fl_PitCom = floatingfeedback_c(LocalVar, CntrPar, objInst, ErrVar);
        DebugVar->Fl_PitCom = LocalVar->Fl_PitCom;
        LocalVar->PC_PitComT += LocalVar->Fl_PitCom;
    }

    // Saturate collective pitch
    LocalVar->PC_PitComT = saturate_c(LocalVar->PC_PitComT, LocalVar->PC_MinPit, CntrPar->PC_MaxPit);
    LocalVar->PC_PitComT = ratelimit_c(LocalVar->PC_PitComT, CntrPar->PC_MinRat, CntrPar->PC_MaxRat,
                                        LocalVar->DT, (LocalVar->restart != 0),
                                        &LocalVar->rlP, &objInst->instRL,
                                        1, LocalVar->BlPitchCMeas);
    LocalVar->PC_PitComT_Last = LocalVar->PC_PitComT;

    // Combine and saturate individual pitch commands
    for (int K = 0; K < LocalVar->NumBl; K++) {
        LocalVar->PitCom[K] = LocalVar->PC_PitComT + LocalVar->FA_PitCom[K];
        LocalVar->PitCom[K] = saturate_c(LocalVar->PitCom[K], LocalVar->PC_MinPit, CntrPar->PC_MaxPit);
        LocalVar->PitCom[K] += LocalVar->IPC_PitComF[K];

        // Hard IPC saturation by peak shaving limit
        if (CntrPar->IPC_SatMode == 1) {
            LocalVar->PitCom[K] = saturate_c(LocalVar->PitCom[K], LocalVar->PC_MinPit, CntrPar->PC_MaxPit);
        }

        // ZeroMQ pitch offset
        LocalVar->PitCom[K] += LocalVar->ZMQ_PitOffset[K];

        // Rate limit per blade
        LocalVar->PitCom[K] = ratelimit_c(LocalVar->PitCom[K], CntrPar->PC_MinRat, CntrPar->PC_MaxRat,
                                           LocalVar->DT, (LocalVar->restart != 0),
                                           &LocalVar->rlP, &objInst->instRL,
                                           1, LocalVar->BlPitch[K]);
    }

    // Open loop pitch control
    if (CntrPar->OL_Mode > 0) {
        if (LocalVar->Time >= CntrPar->OL_Breakpoints[0]) {
            if (CntrPar->Ind_BldPitch[0] > 0) {
                LocalVar->PitCom[0] = interp1d_c(CntrPar->OL_Breakpoints, CntrPar->n_OL_Breakpoints,
                                                   CntrPar->OL_BldPitch1, CntrPar->n_OL_BldPitch1,
                                                   LocalVar->OL_Index, ErrVar);
            }
            if (CntrPar->Ind_BldPitch[1] > 0) {
                LocalVar->PitCom[1] = interp1d_c(CntrPar->OL_Breakpoints, CntrPar->n_OL_Breakpoints,
                                                   CntrPar->OL_BldPitch2, CntrPar->n_OL_BldPitch2,
                                                   LocalVar->OL_Index, ErrVar);
            }
            if (CntrPar->Ind_BldPitch[2] > 0) {
                LocalVar->PitCom[2] = interp1d_c(CntrPar->OL_Breakpoints, CntrPar->n_OL_Breakpoints,
                                                   CntrPar->OL_BldPitch3, CntrPar->n_OL_BldPitch3,
                                                   LocalVar->OL_Index, ErrVar);
            }
        }
    }

    // Active wake control
    if (CntrPar->AWC_Mode > 0) {
        activewakecontrol_c(CntrPar, LocalVar, DebugVar, objInst);
    }

    // Shutdown
    if (LocalVar->SD_Trigger == 0) {
        LocalVar->PitCom_SD[0] = LocalVar->PitCom[0];
        LocalVar->PitCom_SD[1] = LocalVar->PitCom[1];
        LocalVar->PitCom_SD[2] = LocalVar->PitCom[2];
    } else {
        if (CntrPar->SD_Method == 1 || CntrPar->SD_Method == 2) {
            for (int K = 0; K < LocalVar->NumBl; K++) {
                LocalVar->PitCom_SD[K] += LocalVar->SD_MaxPitchRate * LocalVar->DT;
            }
        }
        LocalVar->PitCom[0] = LocalVar->PitCom_SD[0];
        LocalVar->PitCom[1] = LocalVar->PitCom_SD[1];
        LocalVar->PitCom[2] = LocalVar->PitCom_SD[2];
    }

    // Pitch actuator model
    for (int K = 0; K < LocalVar->NumBl; K++) {
        if (CntrPar->PA_Mode > 0) {
            if (CntrPar->PA_Mode == 1) {
                LocalVar->PitComAct[K] = lpfilter_c(
                    LocalVar->PitCom[K], LocalVar->DT, CntrPar->PA_CornerFreq,
                    &LocalVar->FP, LocalVar->iStatus,
                    (LocalVar->restart != 0), &objInst->instLPF,
                    0, 0.0);
            } else if (CntrPar->PA_Mode == 2) {
                LocalVar->PitComAct[K] = seclpfilter_c(
                    LocalVar->PitCom[K], LocalVar->DT,
                    CntrPar->PA_CornerFreq, CntrPar->PA_Damping,
                    &LocalVar->FP, LocalVar->iStatus,
                    (LocalVar->restart != 0), &objInst->instSecLPF,
                    0, 0.0);
            }
        } else {
            LocalVar->PitComAct[K] = LocalVar->PitCom[K];
        }
    }

    // Hardware saturation
    for (int K = 0; K < LocalVar->NumBl; K++) {
        LocalVar->PitComAct[K] = saturate_c(LocalVar->PitComAct[K], CntrPar->PC_MinPit, CntrPar->PC_MaxPit);
        LocalVar->PitComAct[K] = ratelimit_c(LocalVar->PitComAct[K], CntrPar->PC_MinRat, CntrPar->PC_MaxRat,
                                              LocalVar->DT, (LocalVar->restart != 0),
                                              &LocalVar->rlP, &objInst->instRL,
                                              1, LocalVar->BlPitch[K]);
    }

    // Pitch fault modes
    if (CntrPar->PF_Mode == 1) {
        for (int K = 0; K < LocalVar->NumBl; K++) {
            LocalVar->PitComAct[K] += CntrPar->PF_Offsets[K];
        }
    } else if (CntrPar->PF_Mode == 2) {
        for (int K = 0; K < LocalVar->NumBl; K++) {
            if (LocalVar->Time > CntrPar->PF_TimeStuck[K]) {
                LocalVar->PitComAct[K] = LocalVar->BlPitch[K];
            }
        }
    }

    // Command pitch to avrSWAP (Fortran 42-45 → C 41-44)
    avrSWAP[41] = LocalVar->PitComAct[0];
    avrSWAP[42] = LocalVar->PitComAct[1];
    avrSWAP[43] = LocalVar->PitComAct[2];
    avrSWAP[44] = LocalVar->PitComAct[0];  // Collective pitch = blade 1

    // Prepend routine name to error message if aviFAIL < 0
    if (ErrVar->aviFAIL < 0) {
        char tmp[1024];
        snprintf(tmp, sizeof(tmp), "PitchControl:%s", ErrVar->ErrMsg);
        strncpy(ErrVar->ErrMsg, tmp, sizeof(ErrVar->ErrMsg) - 1);
        ErrVar->ErrMsg[sizeof(ErrVar->ErrMsg) - 1] = '\0';
    }
}
