// VIT Translation
// Function: VariableSpeedControl
// Source: Controllers.f90
// Module: Controllers
// Fortran: SUBROUTINE VariableSpeedControl(avrSWAP, CntrPar, LocalVar, objInst, ErrVar)
// Source MD5: cbd745d79f1d
// VIT: 0.1.0
// Status: unverified
// Generated: 2026-03-24T17:15:59Z

// Auto-generated view struct for Fortran TYPE(ControlParameters)
// Generated by VIT (Verified Incremental Translator)
// ALLOCATABLE fields exposed as pointer+size pairs.
// Scalars and CHARACTER fields copied directly.
// 2D arrays use column-major layout: mat[col * n_rows + row]

#ifndef CONTROLPARAMETERS_VIEW_T_H
#define CONTROLPARAMETERS_VIEW_T_H

#include <stdint.h>

typedef struct {
    // --- Scalar and fixed-size fields ---
    int ZMQ_ID;
    int LoggingLevel;
    int Echo;
    int Ext_Interface;
    double DT_Out;
    int n_DT_Out;
    int n_DT_ZMQ;
    int F_LPFType;
    double F_LPFCornerFreq;
    double F_LPFDamping;
    int F_NumNotchFilts;
    int F_GenSpdNotch_N;
    int F_TwrTopNotch_N;
    double F_SSCornerFreq;
    double F_WECornerFreq;
    double F_FlHighPassFreq;
    double F_YawErr;
    double F_VSRefSpdCornerFreq;
    int TRA_Mode;
    double TRA_ExclSpeed;
    double TRA_ExclBand;
    double TRA_RateLimit;
    int TD_Mode;
    double FA_HPFCornerFreq;
    double FA_IntSat;
    double FA_KI;
    int IPC_ControlMode;
    double IPC_IntSat;
    int IPC_SatMode;
    double IPC_CornerFreqAct;
    int PC_ControlMode;
    int PC_GS_n;
    double PC_MaxPit;
    double PC_MinPit;
    double PC_MaxRat;
    double PC_MinRat;
    double PC_RefSpd;
    double PC_FinePit;
    double PC_Switch;
    int VS_ControlMode;
    int VS_ConstPower;
    int VS_FBP;
    double VS_GenEff;
    double VS_ArSatTq;
    double VS_MaxRat;
    double VS_MaxTq;
    double VS_MinTq;
    double VS_MinOMSpd;
    double VS_Rgn2K;
    double VS_RtPwr;
    double VS_RtTq;
    double VS_RefSpd;
    int VS_n;
    double VS_TSRopt;
    int VS_FBP_n;
    int SS_Mode;
    double SS_VSGain;
    double SS_PCGain;
    int PRC_Mode;
    int PRC_Comm;
    int PRC_n;
    double PRC_LPF_Freq;
    double PRC_R_Torque;
    double PRC_R_Speed;
    double PRC_R_Pitch;
    int PRC_Table_n;
    int WE_Mode;
    double WE_BladeRadius;
    int WE_CP_n;
    double WE_Gamma;
    double WE_GearboxRatio;
    double WE_Jtot;
    double WE_RhoAir;
    char PerfFileName[1024];
    int WE_FOPoles_N;
    int Y_ControlMode;
    double Y_uSwitch;
    double Y_Rate;
    double Y_MErrSet;
    double Y_IPC_IntSat;
    double Y_IPC_KP;
    double Y_IPC_KI;
    int PS_Mode;
    int PS_BldPitchMin_N;
    int SU_Mode;
    double SU_StartTime;
    double SU_FW_MinDuration;
    double SU_RotorSpeedThresh;
    double SU_RotorSpeedCornerFreq;
    int SU_LoadStages_N;
    int SD_Mode;
    double SD_TimeActivate;
    int SD_EnablePitch;
    int SD_EnableYawError;
    int SD_EnableGenSpeed;
    int SD_EnableTime;
    double SD_MaxPit;
    double SD_PitchCornerFreq;
    double SD_MaxYawError;
    double SD_YawErrorCornerFreq;
    double SD_MaxGenSpd;
    double SD_GenSpdCornerFreq;
    double SD_Time;
    int SD_Method;
    int SD_Stage_N;
    int Fl_Mode;
    int Fl_n;
    int Flp_Mode;
    double Flp_Angle;
    double Flp_Kp;
    double Flp_Ki;
    double Flp_MaxPit;
    char OL_Filename[1024];
    int OL_Mode;
    int OL_BP_Mode;
    double OL_BP_FiltFreq;
    int Ind_Breakpoint;
    int Ind_GenTq;
    int Ind_YawRate;
    int Ind_R_Speed;
    int Ind_R_Torque;
    int Ind_R_Pitch;
    int Ind_Azimuth;
    int PA_Mode;
    double PA_CornerFreq;
    double PA_Damping;
    int AWC_Mode;
    int AWC_NumModes;
    double AWC_phaseoffset;
    int PF_Mode;
    int Ext_Mode;
    char DLL_FileName[1024];
    char DLL_InFile[1024];
    char DLL_ProcName[1024];
    int ZMQ_Mode;
    char ZMQ_CommAddress[256];
    double ZMQ_UpdatePeriod;
    int CC_Mode;
    int CC_Group_N;
    double CC_ActTau;
    int StC_Mode;
    int StC_Group_N;
    double PC_RtTq99;
    double VS_MaxOMTq;
    double VS_MinOMTq;

    // --- ALLOCATABLE fields (pointer + size) ---
    int* F_GenSpdNotch_Ind;
    int32_t n_F_GenSpdNotch_Ind;
    int* F_TwrTopNotch_Ind;
    int32_t n_F_TwrTopNotch_Ind;
    double* F_NotchFreqs;
    int32_t n_F_NotchFreqs;
    double* F_NotchBetaNum;
    int32_t n_F_NotchBetaNum;
    double* F_NotchBetaDen;
    int32_t n_F_NotchBetaDen;
    double* F_FlCornerFreq;
    int32_t n_F_FlCornerFreq;
    double* F_FlpCornerFreq;
    int32_t n_F_FlpCornerFreq;
    double* IPC_Vramp;
    int32_t n_IPC_Vramp;
    double* IPC_KP;
    int32_t n_IPC_KP;
    double* IPC_KI;
    int32_t n_IPC_KI;
    double* IPC_aziOffset;
    int32_t n_IPC_aziOffset;
    double* PC_GS_angles;
    int32_t n_PC_GS_angles;
    double* PC_GS_KP;
    int32_t n_PC_GS_KP;
    double* PC_GS_KI;
    int32_t n_PC_GS_KI;
    double* PC_GS_KD;
    int32_t n_PC_GS_KD;
    double* PC_GS_TF;
    int32_t n_PC_GS_TF;
    double* VS_KP;
    int32_t n_VS_KP;
    double* VS_KI;
    int32_t n_VS_KI;
    double* VS_FBP_U;
    int32_t n_VS_FBP_U;
    double* VS_FBP_Omega;
    int32_t n_VS_FBP_Omega;
    double* VS_FBP_Tau;
    int32_t n_VS_FBP_Tau;
    double* PRC_WindSpeeds;
    int32_t n_PRC_WindSpeeds;
    double* PRC_GenSpeeds;
    int32_t n_PRC_GenSpeeds;
    double* PRC_Pitch_Table;
    int32_t n_PRC_Pitch_Table;
    double* PRC_R_Table;
    int32_t n_PRC_R_Table;
    double* WE_CP;
    int32_t n_WE_CP;
    int* PerfTableSize;
    int32_t n_PerfTableSize;
    double* WE_FOPoles_v;
    int32_t n_WE_FOPoles_v;
    double* WE_FOPoles;
    int32_t n_WE_FOPoles;
    double* Y_ErrThresh;
    int32_t n_Y_ErrThresh;
    double* PS_WindSpeeds;
    int32_t n_PS_WindSpeeds;
    double* PS_BldPitchMin;
    int32_t n_PS_BldPitchMin;
    double* SU_LoadStages;
    int32_t n_SU_LoadStages;
    double* SU_LoadRampDuration;
    int32_t n_SU_LoadRampDuration;
    double* SU_LoadHoldDuration;
    int32_t n_SU_LoadHoldDuration;
    double* SD_MaxTorqueRate;
    int32_t n_SD_MaxTorqueRate;
    double* SD_MaxPitchRate;
    int32_t n_SD_MaxPitchRate;
    double* SD_StagePitch;
    int32_t n_SD_StagePitch;
    double* SD_StageTime;
    int32_t n_SD_StageTime;
    double* Fl_Kp;
    int32_t n_Fl_Kp;
    double* Fl_U;
    int32_t n_Fl_U;
    int* Ind_BldPitch;
    int32_t n_Ind_BldPitch;
    double* RP_Gains;
    int32_t n_RP_Gains;
    int* Ind_CableControl;
    int32_t n_Ind_CableControl;
    int* Ind_StructControl;
    int32_t n_Ind_StructControl;
    double* OL_Breakpoints;
    int32_t n_OL_Breakpoints;
    double* OL_BldPitch1;
    int32_t n_OL_BldPitch1;
    double* OL_BldPitch2;
    int32_t n_OL_BldPitch2;
    double* OL_BldPitch3;
    int32_t n_OL_BldPitch3;
    double* OL_CableControl;  // column-major
    int32_t n_OL_CableControl_rows;
    int32_t n_OL_CableControl_cols;
    double* OL_StructControl;  // column-major
    int32_t n_OL_StructControl_rows;
    int32_t n_OL_StructControl_cols;
    double* OL_GenTq;
    int32_t n_OL_GenTq;
    double* OL_YawRate;
    int32_t n_OL_YawRate;
    double* OL_Azimuth;
    int32_t n_OL_Azimuth;
    double* OL_R_Speed;
    int32_t n_OL_R_Speed;
    double* OL_R_Torque;
    int32_t n_OL_R_Torque;
    double* OL_R_Pitch;
    int32_t n_OL_R_Pitch;
    double* OL_Channels;  // column-major
    int32_t n_OL_Channels_rows;
    int32_t n_OL_Channels_cols;
    int* AWC_n;
    int32_t n_AWC_n;
    int* AWC_harmonic;
    int32_t n_AWC_harmonic;
    double* AWC_freq;
    int32_t n_AWC_freq;
    double* AWC_amp;
    int32_t n_AWC_amp;
    double* AWC_clockangle;
    int32_t n_AWC_clockangle;
    double* AWC_CntrGains;
    int32_t n_AWC_CntrGains;
    double* PF_Offsets;
    int32_t n_PF_Offsets;
    double* PF_TimeStuck;
    int32_t n_PF_TimeStuck;
    int* CC_GroupIndex;
    int32_t n_CC_GroupIndex;
    int* StC_GroupIndex;
    int32_t n_StC_GroupIndex;
} controlparameters_view_t;

#endif // CONTROLPARAMETERS_VIEW_T_H

// Auto-generated C struct for Fortran TYPE(ErrorVariables)
// Generated by VIT (Verified Incremental Translator)

#ifndef ERRORVARIABLES_T_H
#define ERRORVARIABLES_T_H

typedef struct {
    int size_avcMSG;
    int aviFAIL;
    int ErrStat;
    char ErrMsg[1024];
} errorvariables_t;

#endif // ERRORVARIABLES_T_H

// Auto-generated C struct for Fortran TYPE(FilterParameters)
// Generated by VIT (Verified Incremental Translator)

#ifndef FILTERPARAMETERS_T_H
#define FILTERPARAMETERS_T_H

typedef struct {
    double lpf1_a1[1024];
    double lpf1_a0[1024];
    double lpf1_b1[1024];
    double lpf1_b0[1024];
    double lpf1_InputSignalLast[1024];
    double lpf1_OutputSignalLast[1024];
    double lpf2_a2[1024];
    double lpf2_a1[1024];
    double lpf2_a0[1024];
    double lpf2_b2[1024];
    double lpf2_b1[1024];
    double lpf2_b0[1024];
    double lpf2_InputSignalLast2[1024];
    double lpf2_OutputSignalLast2[1024];
    double lpf2_InputSignalLast1[1024];
    double lpf2_OutputSignalLast1[1024];
    double lpfV_a2[1024];
    double lpfV_a1[1024];
    double lpfV_a0[1024];
    double lpfV_b2[1024];
    double lpfV_b1[1024];
    double lpfV_b0[1024];
    double lpfV_InputSignalLast2[1024];
    double lpfV_OutputSignalLast2[1024];
    double lpfV_InputSignalLast1[1024];
    double lpfV_OutputSignalLast1[1024];
    double hpf_InputSignalLast[1024];
    double hpf_OutputSignalLast[1024];
    double nfs_OutputSignalLast1[1024];
    double nfs_OutputSignalLast2[1024];
    double nfs_InputSignalLast1[1024];
    double nfs_InputSignalLast2[1024];
    double nfs_b2[1024];
    double nfs_b0[1024];
    double nfs_a2[1024];
    double nfs_a1[1024];
    double nfs_a0[1024];
    double nf_OutputSignalLast1[1024];
    double nf_OutputSignalLast2[1024];
    double nf_InputSignalLast1[1024];
    double nf_InputSignalLast2[1024];
    double nf_b2[1024];
    double nf_b1[1024];
    double nf_b0[1024];
    double nf_a1[1024];
    double nf_a0[1024];
} filterparameters_t;

#endif // FILTERPARAMETERS_T_H

// Auto-generated C struct for Fortran TYPE(ObjectInstances)
// Generated by VIT (Verified Incremental Translator)

#ifndef OBJECTINSTANCES_T_H
#define OBJECTINSTANCES_T_H

typedef struct {
    int instLPF;
    int instSecLPF;
    int instSecLPFV;
    int instHPF;
    int instNotchSlopes;
    int instNotch;
    int instPI;
    int instRes;
    int instRL;
} objectinstances_t;

#endif // OBJECTINSTANCES_T_H

// Auto-generated C struct for Fortran TYPE(piParams)
// Generated by VIT (Verified Incremental Translator)

#ifndef PIPARAMS_T_H
#define PIPARAMS_T_H

typedef struct {
    double ITerm[1024];
    double ITermLast[1024];
    double ITerm2[1024];
    double ITermLast2[1024];
    double ELast[1024];
} piparams_t;

#endif // PIPARAMS_T_H

// Auto-generated C struct for Fortran TYPE(resParams)
// Generated by VIT (Verified Incremental Translator)

#ifndef RESPARAMS_T_H
#define RESPARAMS_T_H

typedef struct {
    double res_OutputSignalLast1[1024];
    double res_OutputSignalLast2[1024];
    double res_InputSignalLast1[1024];
    double res_InputSignalLast2[1024];
} resparams_t;

#endif // RESPARAMS_T_H

// Auto-generated C struct for Fortran TYPE(rlParams)
// Generated by VIT (Verified Incremental Translator)

#ifndef RLPARAMS_T_H
#define RLPARAMS_T_H

typedef struct {
    double LastSignal[1024];
} rlparams_t;

#endif // RLPARAMS_T_H

// Auto-generated C struct for Fortran TYPE(WE)
// Generated by VIT (Verified Incremental Translator)
// Note: Fortran uses column-major order.
//   Fortran P(i,j) maps to C P[j-1][i-1].

#ifndef WE_T_H
#define WE_T_H

typedef struct {
    double om_r;
    double v_t;
    double v_m;
    double v_h;
    double P[3][3];
    double xh[3][1];
    double K[3][1];
} we_t;

#endif // WE_T_H

// Auto-generated C struct for Fortran TYPE(LocalVariables)
// Generated by VIT (Verified Incremental Translator)

#ifndef LOCALVARIABLES_T_H
#define LOCALVARIABLES_T_H

typedef struct {
    int iStatus;
    int AlreadyInitialized;
    int RestartWSE;
    double Time;
    double DT;
    int WriteThisStep;
    int n_DT;
    double Time_Last;
    double VS_GenPwr;
    double GenSpeed;
    double RotSpeed;
    double NacHeading;
    double NacVane;
    double NacVaneF;
    double WindDir;
    double HorWindV;
    double HorWindV_F;
    double rootMOOP[3];
    double rootMOOPF[3];
    double BlPitch[3];
    double BlPitchCMeas;
    double Azimuth;
    double OL_Azimuth;
    double AzUnwrapped;
    double AzError;
    double GenTqAz;
    double AzBuffer[2];
    int NumBl;
    double FA_Acc_TT;
    double SS_Acc_TT;
    double FA_Acc_Nac;
    double NacIMU_FA_RAcc;
    double FA_AccHPF;
    double FA_AccHPFI;
    double FA_PitCom[3];
    double VS_RefSpd;
    double VS_RefSpd_TSR;
    double VS_RefSpd_TRA;
    double VS_RefSpd_RL;
    double PC_RefSpd;
    double PC_RefSpd_SS;
    double PC_RefSpd_PRC;
    double RotSpeedF;
    double GenSpeedF;
    double GenTq;
    double GenTqMeas;
    double GenArTq;
    double GenBrTq;
    double VS_KOmega2_GenTq;
    double VS_ConstPwr_GenTq;
    double IPC_PitComF[3];
    double PC_KP;
    double PC_KI;
    double PC_KD;
    double PC_TF;
    double PC_MaxPit;
    double PC_MinPit;
    double PC_PitComT;
    double PC_PitComT_Last;
    double BlPitchCMeasF;
    double PC_PitComT_IPC[3];
    double PC_PwrErr;
    double PC_SpdErr;
    double IPC_AxisTilt_1P;
    double IPC_AxisYaw_1P;
    double IPC_AxisTilt_2P;
    double IPC_AxisYaw_2P;
    double axisTilt_1P;
    double axisYaw_1P;
    double axisYawF_1P;
    double axisTilt_2P;
    double axisYaw_2P;
    double axisYawF_2P;
    double IPC_KI[2];
    double IPC_KP[2];
    double IPC_IntSat;
    int PC_State;
    double PitCom[3];
    double PitCom_SD[3];
    double PitComAct[3];
    double SS_DelOmegaF;
    double TestType;
    double Kp_Float;
    double VS_MaxTq;
    double VS_LastGenTrq;
    double VS_LastGenPwr;
    double VS_MechGenPwr;
    double VS_SpdErrAr;
    double VS_SpdErrBr;
    double VS_SpdErr;
    int VS_State;
    double VS_Rgn3Pitch;
    double WE_Vw;
    double WE_Vw_F;
    double WE_VwI;
    double WE_VwIdot;
    int WE_Op;
    int WE_Op_Last;
    double VS_LastGenTrqF;
    double PRC_WSE_F;
    double PRC_R_Speed;
    double PRC_R_Torque;
    double PRC_R_Pitch;
    double PRC_R_Total;
    double PRC_Min_Pitch;
    double PS_Min_Pitch;
    double OL_Index;
    int SU_Stage;
    double SU_LoadStageStartTime;
    double SU_RotSpeedF;
    int SD_Trigger;
    double SD_BlPitchF;
    double SD_NacVaneF;
    double SD_GenSpeedF;
    int SD_Stage;
    double SD_StageStartTime;
    double SD_MaxPitchRate;
    double SD_MaxTorqueRate;
    double GenTq_SD;
    double Fl_PitCom;
    double NACIMU_FA_AccF;
    double FA_AccF;
    int FA_Hist;
    double TRA_LastRefSpd;
    double VS_RefSpeed;
    double PtfmTDX;
    double PtfmTDY;
    double PtfmTDZ;
    double PtfmRDX;
    double PtfmRDY;
    double PtfmRDZ;
    double PtfmTVX;
    double PtfmTVY;
    double PtfmTVZ;
    double PtfmRVX;
    double PtfmRVY;
    double PtfmRVZ;
    double PtfmTAX;
    double PtfmTAY;
    double PtfmTAZ;
    double PtfmRAX;
    double PtfmRAY;
    double PtfmRAZ;
    double CC_DesiredL[12];
    double CC_ActuatedL[12];
    double CC_ActuatedDL[12];
    double StC_Input[12];
    double Flp_Angle[3];
    double RootMyb_Last[3];
    int ACC_INFILE_SIZE;
    char ACC_INFILE[1024];
    int restart;
    double AWC_complexangle_re[3];
    double AWC_complexangle_im[3];
    double TiltMean;
    double YawMean;
    int ZMQ_ID;
    double ZMQ_YawOffset;
    double ZMQ_TorqueOffset;
    double ZMQ_PitOffset[3];
    double ZMQ_R_Speed;
    double ZMQ_R_Torque;
    double ZMQ_R_Pitch;
    we_t WE;
    filterparameters_t FP;
    piparams_t piP;
    resparams_t resP;
    rlparams_t rlP;
} localvariables_t;

#endif // LOCALVARIABLES_T_H

#include <algorithm>
#include <cstring>
#include <cstdio>
#include "rosco_constants.h"

// Callee entry points — provided by vit_kernel_callees.h (kernel) or
// vit_translated.h (integration). Declared here for standalone compilation.
extern "C" {
    double picontroller_c(double error, double kp, double ki,
                          double minValue, double maxValue, double DT,
                          double I0, piparams_t* piP, int reset, int* inst);
    double saturate_c(double val, double minval, double maxval);
    double ratelimit_c(double inputSignal, double minRate, double maxRate, double DT,
                       int reset, rlparams_t* rlP, int* inst,
                       int has_ResetValue, double ResetValue);
    double interp1d_c(double* xData, int n_xData, double* yData, int n_yData,
                      double xq, errorvariables_t* ErrVar);
}

void VariableSpeedControl(float* avrSWAP, controlparameters_view_t* CntrPar, localvariables_t* LocalVar, objectinstances_t* objInst, errorvariables_t* ErrVar) {
    // VariableSpeedControl: generator torque controller
    // State machine with K*Omega^2 law, PI transitions, constant torque/power modes

    // Pre-compute generator torque values
    LocalVar->VS_KOmega2_GenTq = CntrPar->VS_Rgn2K * LocalVar->GenSpeedF * LocalVar->GenSpeedF;
    LocalVar->VS_ConstPwr_GenTq = (CntrPar->VS_RtPwr / (CntrPar->VS_GenEff / 100.0)) / LocalVar->GenSpeedF * LocalVar->PRC_R_Torque;

    // Determine maximum torque saturation limit
    if (CntrPar->VS_FBP == VS_FBP_Variable_Pitch) {
        if (CntrPar->VS_ConstPower == VS_Mode_ConstPwr) {
            LocalVar->VS_MaxTq = std::min(LocalVar->VS_ConstPwr_GenTq, CntrPar->VS_MaxTq);
        } else {
            LocalVar->VS_MaxTq = CntrPar->VS_RtTq * LocalVar->PRC_R_Torque;
        }
    } else {
        LocalVar->VS_MaxTq = CntrPar->VS_MaxTq;
    }

    // TSR tracking controller modes
    if ((CntrPar->VS_ControlMode == VS_Mode_WSE_TSR) ||
        (CntrPar->VS_ControlMode == VS_Mode_Power_TSR) ||
        (CntrPar->VS_ControlMode == VS_Mode_Torque_TSR)) {

        LocalVar->GenTq = picontroller_c(
            LocalVar->VS_SpdErr,
            CntrPar->VS_KP[0], CntrPar->VS_KI[0],
            CntrPar->VS_MinTq, LocalVar->VS_MaxTq,
            LocalVar->DT, LocalVar->VS_LastGenTrq,
            &LocalVar->piP, (LocalVar->restart != 0), &objInst->instPI);

        if (CntrPar->VS_FBP == VS_FBP_Power_Overspeed) {
            LocalVar->GenTq = std::min(LocalVar->VS_ConstPwr_GenTq, LocalVar->GenTq);
        }

    } else if (CntrPar->VS_ControlMode == VS_Mode_KOmega) {
        // K*Omega^2 with PI transitions
        LocalVar->GenArTq = picontroller_c(
            LocalVar->VS_SpdErrAr,
            CntrPar->VS_KP[0], CntrPar->VS_KI[0],
            CntrPar->VS_MaxOMTq, CntrPar->VS_ArSatTq,
            LocalVar->DT, CntrPar->VS_MaxOMTq,
            &LocalVar->piP, (LocalVar->restart != 0), &objInst->instPI);
        LocalVar->GenBrTq = picontroller_c(
            LocalVar->VS_SpdErrBr,
            CntrPar->VS_KP[0], CntrPar->VS_KI[0],
            CntrPar->VS_MinTq, CntrPar->VS_MinOMTq,
            LocalVar->DT, CntrPar->VS_MinOMTq,
            &LocalVar->piP, (LocalVar->restart != 0), &objInst->instPI);

        // State machine
        if (LocalVar->VS_State == VS_State_Region_1_5) {
            LocalVar->GenTq = LocalVar->GenBrTq;
        } else if (LocalVar->VS_State == VS_State_Region_2) {
            LocalVar->GenTq = LocalVar->VS_KOmega2_GenTq;
        } else if (LocalVar->VS_State == VS_State_Region_2_5) {
            LocalVar->GenTq = LocalVar->GenArTq;
        } else if (LocalVar->VS_State == VS_State_Region_3_ConstTrq) {
            LocalVar->GenTq = CntrPar->VS_RtTq;
        } else if (LocalVar->VS_State == VS_State_Region_3_ConstPwr) {
            LocalVar->GenTq = LocalVar->VS_ConstPwr_GenTq;
        } else if (LocalVar->VS_State == VS_State_Region_3_FBP) {
            if (CntrPar->VS_FBP == VS_FBP_Power_Overspeed) {
                LocalVar->GenTq = std::min(LocalVar->VS_ConstPwr_GenTq, LocalVar->VS_KOmega2_GenTq);
            } else if ((CntrPar->VS_FBP == VS_FBP_WSE_Ref) || (CntrPar->VS_FBP == VS_FBP_Torque_Ref)) {
                LocalVar->GenTq = LocalVar->GenArTq;
            }
        }

    } else {
        // VS_ControlMode of 0
        LocalVar->GenTq = 0.0;
    }

    // Shutdown
    if (LocalVar->SD_Trigger == 0) {
        LocalVar->GenTq_SD = LocalVar->GenTq;
    } else {
        if (CntrPar->SD_Method == 1 || CntrPar->SD_Method == 2) {
            LocalVar->GenTq_SD = LocalVar->GenTq_SD - LocalVar->SD_MaxTorqueRate * LocalVar->DT;
            LocalVar->GenTq_SD = saturate_c(LocalVar->GenTq_SD, CntrPar->VS_MinTq, CntrPar->VS_MaxTq);
        }
        LocalVar->GenTq = LocalVar->GenTq_SD;
    }

    // Saturate based on most stringent defined maximum
    LocalVar->GenTq = saturate_c(LocalVar->GenTq, CntrPar->VS_MinTq,
                                  std::min(CntrPar->VS_MaxTq, LocalVar->VS_MaxTq));

    // Rate limit
    LocalVar->GenTq = ratelimit_c(LocalVar->GenTq, -CntrPar->VS_MaxRat, CntrPar->VS_MaxRat,
                                   LocalVar->DT, (LocalVar->restart != 0),
                                   &LocalVar->rlP, &objInst->instRL,
                                   0, 0.0);  // no ResetValue

    // Open loop torque control
    if ((CntrPar->OL_Mode > 0) && (CntrPar->Ind_GenTq > 0)) {
        if (LocalVar->Time >= CntrPar->OL_Breakpoints[0]) {
            LocalVar->GenTq = interp1d_c(
                CntrPar->OL_Breakpoints, CntrPar->n_OL_Breakpoints,
                CntrPar->OL_GenTq, CntrPar->n_OL_GenTq,
                LocalVar->OL_Index, ErrVar);
        }

        // Azimuth tracking control (OL_Mode == 2) — handled by callee bridges
        // (UNWRAP, PIDController not yet translated, will use Fortran originals)
        if (CntrPar->OL_Mode == 2) {
            // Initialize azimuth buffer
            if (LocalVar->iStatus == 0) {
                LocalVar->AzBuffer[0] = LocalVar->Azimuth;
                LocalVar->AzBuffer[1] = LocalVar->Azimuth;
            }
            // Push/pop buffer
            LocalVar->AzBuffer[0] = LocalVar->AzBuffer[1];
            LocalVar->AzBuffer[1] = LocalVar->Azimuth;
            // UNWRAP and PIDController are untranslated — these branches
            // are not exercised in the golden fixture (OL_Mode=0).
            // They will be bridged to Fortran during kernel verification.
            // For now, skip the azimuth tracking computation.
        }
    }

    // Update last values
    LocalVar->VS_LastGenTrq = LocalVar->GenTq;
    LocalVar->VS_LastGenPwr = LocalVar->VS_GenPwr;

    // Set commanded generator torque (Fortran avrSWAP(47) → C [46])
    avrSWAP[46] = std::max(0.0, LocalVar->VS_LastGenTrq);

    // Prepend routine name to error message if aviFAIL < 0
    if (ErrVar->aviFAIL < 0) {
        char tmp[1024];
        snprintf(tmp, sizeof(tmp), "VariableSpeedControl:%s", ErrVar->ErrMsg);
        strncpy(ErrVar->ErrMsg, tmp, sizeof(ErrVar->ErrMsg) - 1);
        ErrVar->ErrMsg[sizeof(ErrVar->ErrMsg) - 1] = '\0';
    }
}
