#!/usr/bin/env python3
"""Read one clamp census and print the counts this unit's blindness is stated in.

    python3.12 evidence/PIDController/census_report.py evidence/PIDController/clamp_census.before.csv

The CSV is written by `probes/clamp-census.cpp` (generated by `make_census.py`),
one row per call, from a run that changes NO compared output -- so the run that
produces it is GREEN and the census is a reading of the corpus rather than a
perturbation of it.

EVERY NUMBER THIS DISPATCH QUOTES COMES FROM HERE, so that a count in prose can
be re-derived from a committed artifact instead of trusted. The rows are split
by ARM: the reset arm computes none of the three terms and a count over all
4610 rows would divide by a denominator that includes cases the question does
not apply to.
"""
import csv, math, sys

path = sys.argv[1]
rows = list(csv.DictReader(open(path)))


def f(r, k):
    try:
        return float(r[k])
    except ValueError:
        return float("nan")


els = [r for r in rows if r["reset"] == "0"]
print(f"{path}")
print(f"  cases {len(rows)}   ELSE arm {len(els)}   reset arm {len(rows) - len(els)}")


def cnt(name, pred):
    c = sum(1 for r in els if pred(r))
    print(f"  {name:<44} {c:>6} of {len(els)}")


# The bracket. `saturate(x, lo, hi)` is MIN(MAX(x,lo),hi), which returns `hi`
# for every x when lo >= hi -- so the pair has to be an INTERVAL before the
# clamp can be inactive at all.
cnt("minValue < maxValue", lambda r: f(r, "minValue") < f(r, "maxValue"))
# The callee's answer. `LPFilter` divides by `FP%lpf1_a1(inst)`, which is zero
# unless the init branch (iStatus == 0 .OR. reset) has written it -- and the
# harness supplies `LocalVar%FP` zeroed on every case.
cnt("EFilt finite", lambda r: math.isfinite(f(r, "EFilt")))
cnt("raw sum finite", lambda r: math.isfinite(f(r, "raw")))
# The two clamps, independently. STRICT inequalities: at the bound the clamp
# returns the bound and the mutant that moved the value there is invisible.
cnt("outer clamp INACTIVE",
    lambda r: f(r, "minValue") < f(r, "raw") < f(r, "maxValue"))
cnt("ITerm clamp INACTIVE",
    lambda r: f(r, "minValue") < f(r, "ITerm_upd") < f(r, "maxValue"))
cnt("both clamps inactive",
    lambda r: f(r, "minValue") < f(r, "raw") < f(r, "maxValue")
    and f(r, "minValue") < f(r, "ITerm_upd") < f(r, "maxValue"))
# The return value's own degeneracy, which is what six survivors were made of:
# a result that equals a BOUND carries nothing about the three terms.
cnt("return value == a bound",
    lambda r: f(r, "result") == f(r, "minValue")
    or f(r, "result") == f(r, "maxValue"))

fin = sorted(abs(f(r, "raw")) for r in els if math.isfinite(f(r, "raw")))
if fin:
    qs = [0.0, 0.25, 0.5, 0.75, 0.9, 1.0]
    print("  |raw| over the finite cases: "
          + "  ".join(f"q{q:.2f}={fin[min(len(fin) - 1, int(q * (len(fin) - 1)))]:.4g}"
                      for q in qs))
else:
    print("  |raw| over the finite cases: NONE -- every sum is Inf or NaN")
