// Auto-generated C struct for Fortran TYPE(ObjectInstances)
// Generated by VIT (Verified Incremental Translator)

#ifndef OBJECTINSTANCES_T_H
#define OBJECTINSTANCES_T_H

typedef struct {
    int instLPF;
    int instSecLPF;
    int instSecLPFV;
    int instHPF;
    int instNotchSlopes;
    int instNotch;
    int instPI;
    int instRes;
    int instRL;
} objectinstances_t;

#endif // OBJECTINSTANCES_T_H
