#!/usr/bin/env python3
"""Emit the post-integration harness's shim, from VIT's own parameter builder.

WHY THIS EXISTS. `scripts/harness.sh --post-integration` used to write the shim
with a heredoc containing one literal signature:

    void ${UNIT}(double*, double, int, double*, double*);

which is ColemanTransform's, and only ColemanTransform's. Unit #1's
`AddToList(CFI_cdesc_t*, int)` would have produced a shim that does not compile
-- the good outcome -- but any unit whose arity happens to match would have
produced one that compiles and forwards the wrong arguments. A hand-copied ABI
in a shell script is a second spelling of `build_c_params`, and two spellings
agree until they do not.

WHAT THE SHIM IS FOR. After integration the build tree holds a compiled
`<stem>.cpp.o` defining the translation, and the harness compiles its own copy;
linking both is a duplicate definition. The integrated object is dropped from
LIBS and this shim supplies `<name>_c` instead, forwarding to the harness's
copy. The reference side then runs

    Fortran bridge -> integrated Fortran wrapper -> <name>_c -> the translation

so what is under test is the MARSHALLING, not the arithmetic. See harness.sh.

    python3 scripts/_integration_shim.py AddToList \\
        -f rosco/controller/src/ROSCO_Helpers.f90 > shim.cpp
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("unit")
    ap.add_argument("-f", "--file", required=True, help="Fortran source, relative to root")
    ap.add_argument("--root", default=str(ROOT))
    a = ap.parse_args()

    root = Path(a.root).resolve()
    sys.path.insert(0, str(root))

    import yaml
    from vit.derived_type_parser import (apply_type_strategies,
                                         build_derived_type_registry)
    from vit.fortran_parser import parse_signature_from_source
    from vit.interface_gen import (build_c_params, cfi_args,
                                   result_is_out_param)
    from vit.type_map import get_type_mapping

    cfg = yaml.safe_load((root / "vit.yaml").read_text())
    aliases = (cfg.get("fortran") or {}).get("kind_aliases") or {}
    strategies = {k: (v.get("strategy") if isinstance(v, dict) else v)
                  for k, v in (cfg.get("types") or {}).items()}
    strategies = {k: v for k, v in strategies.items() if v}

    src = root / a.file
    sig = parse_signature_from_source(src.read_text(), a.unit)
    if sig is None:
        print(f"{a.unit} not found in {src}", file=sys.stderr)
        return 2
    registry = build_derived_type_registry(sig, str(src.parent))
    if strategies:
        apply_type_strategies(registry, strategies)

    params = build_c_params(sig, aliases, registry)
    ret = "void"
    if sig.is_function and not result_is_out_param(sig, aliases, registry):
        ret = get_type_mapping(sig.result_type or "REAL(8)", aliases, registry).c_type

    decl_types = ", ".join(t for t, _ in params)
    defn = ", ".join(f"{t} a{i}" for i, (t, _) in enumerate(params))
    call = ", ".join(f"a{i}" for i in range(len(params)))

    out = ["// Generated by scripts/_integration_shim.py from VIT's build_c_params.",
           "// Do not hand-edit: the signature is the ABI, and a copy of an ABI drifts.",
           ""]
    if cfi_args(sig):
        out.append("#include <ISO_Fortran_binding.h>")
        out.append("")
    out += [f"{ret} {sig.cpp_impl_name}({decl_types});",
            f'extern "C" {ret} {sig.c_func_name}({defn}) {{',
            f"    {'return ' if ret != 'void' else ''}{sig.cpp_impl_name}({call});",
            "}"]
    print("\n".join(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
