#!/usr/bin/env python3
"""Score the `write_401` mutants against the THIRD oracle: the reference's own
`fort.401` beside the translation's.

WHY THIS IS A SEPARATE SCRIPT FROM score_ld_mutants.py. That one slices the
FORMATTER out of the translation and runs it against 22,526 gfortran records --
it can price a wrong field width or a wrong exponent pad, and it cannot see
`write_401` at all, because `write_401` is not in the slice. What `write_401`
does is the CONNECTION: open the unit once, truncating; write the record; write
the terminator; keep the handle. Those are exactly the mutants the slice misses
and the differential harness also misses, for the harness's usual reason -- no
signature carries a file.

The oracle here is `probes/split_fort401.cpp`'s: send the C++ side's records to
`fort.401.cpp` while the Fortran reference keeps writing `fort.401`, run the
harness, and compare the two files. Unmutated they are byte identical
(md5 d6780bd7, 459 bytes, 17 records).

    python3 evidence/PowerControlSetpoints/score_f401_mutants.py <mid> [<mid>...]

Each mutant is applied to the translation, the split is applied ON TOP of the
mutant, and the pair is run through `run_probe.sh` -- which restores the
translation from HEAD unconditionally when it is done. KILLED means the two
files differ, one is missing, or the run did not produce them.

A MUTANT THAT CRASHES IS KILLED, AND SAYS SO SEPARATELY. `unit401 == nullptr`
inverted leaves the handle null and hands it to `fwrite`, which is undefined
rather than wrong; that is still a kill, but it is a different fact from a
record that came out with the wrong bytes, so the two are not merged.
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
LOOP = ROOT.parent / "translation-loop"
CPP = ROOT / "translations/ControllerBlocks/powercontrolsetpoints.cpp"
TESTDIR = "/workspace/ROSCO-r2/translations/ControllerBlocks/powercontrolsetpoints_test"
CONTAINER = "vit-dev"

sys.path.insert(0, str(LOOP))
from harness.cppmutate import mutants  # noqa: E402


def loop_rev() -> str:
    """The generator revision, read the way the generated artifacts read it, so
    an oracle written here can be asked revcheck's question too. Falls back to
    the string the harness artifacts carry rather than to None: an artifact with
    no recorded input is worse than one with a disagreement (revcheck's (2))."""
    try:
        import json as _json
        from pathlib import Path as _P
        d = _json.loads((_P(ROOT) / "harness/PowerControlSetpoints.json").read_text())
        return d.get("loop_rev", "unknown")
    except Exception:
        return "unknown"


def dexec(script: str) -> tuple[int, str]:
    r = subprocess.run(["docker", "exec", CONTAINER, "bash", "-lc", script],
                       capture_output=True, text=True)
    return r.returncode, r.stdout.strip()


def main() -> int:
    want = set(sys.argv[1:])
    if not want:
        print(__doc__)
        return 2
    original = CPP.read_text()
    # Lowercase unit name: `vit_mutate.py` calls `mutants(args.unit.lower(), ...)`
    # and the unit string goes into the id, so this is the id space
    # mutation/PowerControlSetpoints.json reports.
    ms = {m.mid: m for m in mutants("powercontrolsetpoints", original)}
    missing = sorted(want - set(ms))
    if missing:
        print(f"no such mutant id: {', '.join(missing)}", file=sys.stderr)
        return 2

    tmp = ROOT / "evidence/PowerControlSetpoints/probes/_f401_mutant.cpp"
    rows = []
    for mid in sys.argv[1:]:
        m = ms[mid]
        src = m.source
        assert src.count('std::fopen("fort.401", "w")') == 1, \
            f"{mid}: the split cannot be applied -- the fopen line is not intact"
        tmp.write_text(
            "// GENERATED by score_f401_mutants.py -- mutant %s applied, then the\n"
            "// split that sends the C++ records to fort.401.cpp. Overwritten per run.\n"
            % mid
            + src.replace('std::fopen("fort.401", "w")', 'std::fopen("fort.401.cpp", "w")'))

        dexec(f"rm -f {TESTDIR}/fort.401 {TESTDIR}/fort.401.cpp")
        subprocess.run(
            ["bash", str(ROOT / "evidence/PowerControlSetpoints/run_probe.sh"), str(tmp),
             f"evidence/PowerControlSetpoints/probes/_f401_{mid}.json",
             f"write_401 mutant {mid} ({m.operator}) with the fort.401 split"],
            capture_output=True, text=True)

        rc, out = dexec(
            f"cd {TESTDIR} && "
            f"if [ ! -f fort.401 ]; then echo 'NO-REFERENCE-FILE'; "
            f"elif [ ! -f fort.401.cpp ]; then echo 'NO-TRANSLATION-FILE'; "
            f"elif cmp -s fort.401 fort.401.cpp; then echo \"SAME $(wc -c < fort.401)\"; "
            f"else echo \"DIFFER ref=$(wc -c < fort.401) cpp=$(wc -c < fort.401.cpp)\"; fi")
        verdict = "survived" if out.startswith("SAME") else "killed"
        rows.append({"id": mid, "operator": m.operator, "line": m.line,
                     "before": m.before, "after": m.after,
                     "verdict": verdict, "observed": out})
        print(f"{mid}  {m.operator:<12} line {m.line:>4}  {verdict:<9} {out}")

    if CPP.read_text() != original:
        print("TRANSLATION NOT RESTORED", file=sys.stderr)
        return 3
    tmp.unlink(missing_ok=True)
    json.dump({"unit": "PowerControlSetpoints",
               "loop_rev": loop_rev(),
               "oracle": "the reference's fort.401 against the translation's fort.401.cpp,"
                         " over the 3648-case differential corpus",
               "unmutated": "byte identical, 459 bytes, md5 d6780bd7",
               "scored": len(rows),
               "killed": sum(r["verdict"] == "killed" for r in rows),
               "mutants": rows},
              open(ROOT / "evidence/PowerControlSetpoints/f401_mutants.json", "w"), indent=1)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
